#+TITLE: Algebra: chapter 0
#+DESCRIPTION: Exercises on the Paolo Aluffi's book

#+SETUPFILE: config.setup
#+SETUPFILE: essay.setup
#+LANGUAGE: en,es
#+OPTIONS: toc:nil
#+TODO: TODO WIP | CHECK

* I. Preliminaries: Set theory and categories
** I.5. Universal properties
*** Exercise I.5.12
#+begin_statement
Define notions of /fibered products/ and /coproducts/, as terminal objects of
the categories $C_{\alpha,\beta}$ and $C^{\alpha,\beta}$ considered in Example 3.10, by stating carefully
the corresponding universal properties.

As it happens, $\mathtt{Set}$ has both fibered products and coproducts. Define these
objects 'concretely', in terms of naive set theory.
#+end_statement

**** Fibered products
Given $\alpha\colon A \to C$ and $\beta \colon B \to C$, we take the objects of the category
to be commutative diagrams

\[\begin{tikzcd}[row sep=tiny]
 & A \drar{\alpha} & \\
Z\drar{g}\urar{f} && C\\
& B \urar{\beta} & &.
\end{tikzcd}\]

And morphisms to be of the form

\[\begin{tikzcd}[row sep=tiny]
& & A \drar{\alpha} & \\
Z' \rar{h}\ar[bend right]{drr}{g'} \ar[bend left]{urr}{f'} &
Z\drar{g}\urar{f} && C\\
& & B \urar{\beta} & &.
\end{tikzcd}\]

With the trivial identity $\mathrm{id}_Z \colon (Z,f,g) \to (Z,f,g)$. The terminal object
should be the one such that every other object's morphisms descompose
through it.

\[\begin{tikzcd}[row sep=tiny]
& & A \drar{\alpha} & \\
Z' \rar[dashed]{\exists! h}\ar[bend right]{drr}{g'} \ar[bend left]{urr}{f'} &
F\drar{\pi_{\beta}}\urar{\pi_{\alpha}} && C\\
& & B \urar{\beta} & &.
\end{tikzcd}\]

**** Fibered coproducts
The same idea can be applied to the dual construction

\[\begin{tikzcd}[row sep=tiny]
& & A \dlar{\iota_A}\ar[bend right]{lld}{f'} & \\
Z &
F \lar[dashed]{\exists! h} && 
C \ular{f}\dlar{g}\\
& & B \ular{\iota_B}\ar[bend left]{llu}{g'} & &.
\end{tikzcd}\]

**** In the category of sets
In $\mathtt{Set}$, the fibered product will be

\[
\left\{ (a,b) \in A \times B \mid \alpha(a) = \beta(b) \right\},
\]

as we can show using the product universal property. The fibered coproduct
is the coproduct divided by the equivalence relation generated by the
pairs $a \sim b$ such that $\exists c\colon a = f(c), b = g(c)$.

* II. Groups, first encounter
** II.1. Definition of group
*** Exercise II.1.1
#+begin_statement
Write a careful proof that every group is the group of isomorphisms of a
grupoid. In particular, every group is the group of automorphisms of some
object in some category.
#+end_statement

Given a group $(G,\bullet)$, we can define an object $G$ with morphisms the elements
of the group. Composition will be the binary operation of the group, and we
can check, using the group properties, that category axioms hold

 1. *Identity*, there is an identity element on $G$ which acts as the identity
    morphism: $e \circ a = a = a \circ e$.
 2. *Associativity* holds directly: $a \circ (b\circ c) = (a \circ b)\circ c$.

This only object defines a category which is also a grupoid, as every arrow
has an *inverse* by the last property of groups: every element of the group has
an inverse.

*** Exercise II.1.2
#+begin_statement
Consider the 'sets of numbers' listed in 1.1, and decide which are made into 
groups by conventional operations such as $+$ and $\cdot$. Even if the answer is negative,
see if variations on the definition of these sets lead to groups.
#+end_statement

**** The empty set
It is not a group, as it has no identity.

**** Naturals
They form no group with addition, as not every element has an inverse.

**** Integers
They are a commutative group with the addition.

**** Rational numbers
They are a group with addition, and also a group with multiplication if we
consider $0$ out of the group.

**** Real numbers
They follow the same logic as the rationals.

**** Complex numbers
Same logic as the rationals.

*** Exercise II.1.13
#+begin_statement
Give an example showing that $|gh|$ is not necessarily equal to $\mathrm{lcm}(|g|,|h|)$, even
if $g$ and $h$ commute.
#+end_statement

In $(\mathbb{Z}/\mathbb{Z}_4,+)$, we have $\mathrm{lcm}(|1|,|1|) = |1| = 4$, but $|1+1| = 2$.

*** Exercise II.1.14
#+begin_statement
As a counterpoint to [[*Exercise II.1.13][Exercise 13]], prove that if $g$ and $h$ commute, 
and $\mathrm{gcd}(|g|,|h|) = 1$, then $|gh| = |g||h|$.
#+end_statement

We know that $|gh| = N \mid |g||h|$. If we divide to obtain $g^{N} = (h^{-1})^{N}$, we have

 * $1 = \left( g^{-1} \right)^{N|g|} = h^{N|g|}$
 * $1 = \left( h^{-1} \right)^{N|h|} = g^{N|h|}$

and then, $|h| \mid N|g|$ and they are coprimes, so $|h| \mid N$. Likewise, $|g| \mid N$.
Finally, $|gh| = \mathrm{lcm}(|h|,|g|) \mid N$.

*** Exercise II.1.15
#+begin_statement
Let $G$ a commutative group, and let $g \in G$ be an element of maximal /finite/
order: that is, such that if $h \in G$ has finite order then $|h| \leq |g|$. Prove that
in fact if $h$ has finite order in $G$ then $|h|$ divides $|g|$.
#+end_statement

If $|h|$ does not divide $|g|$, then there is a prime $p$ such that

 * $|h| = p^{a+b}m$
 * $|g| = p^bn$, with $\mathrm{gcd}(n,p) = 1$.

then we know that $|h^m| = p^{a+b}$ and $|g^{p^b}| = n$. Using [[*Exercise II.1.14][exercise 14]] (we are in a
commutative group), we know that $|g^{p^b}h^m| = p^{a+b}n$, contradicting maximality.

** II.2. Examples of groups
*** Exercise II.2.2
#+begin_statement
Prove that if $d \leq n$, then $S_n$ contains elements of order $d$.
#+end_statement

The element $(1\;2\;\dots\;d)$ has order $d$.

*** TODO Exercise II.2.5
** II.3. The category Grp
*** Exercise II.3.1
#+begin_statement
Let $\varphi\colon G \to H$ be a morphism in a category $C$ with products. Explain why there
is a unique morphism

\[(\varphi\times\varphi)\colon G\times G \to H \times H.\]
#+end_statement

The real morphism is $(\varphi\circ \pi_1 \times \varphi \circ \pi_2)$, using the projections from $C$ as presented
in the following diagram

\[\begin{tikzcd}[column sep=small,row sep=tiny]
& G \times G\drar\dlar\ar[dashed]{dd}{\varphi\times\varphi} & \\
G\ar{dd} & & G\ar{dd} \\
& H \times H\drar\dlar & \\
H & & H \\
\end{tikzcd}\]

*** Exercise II.3.8
#+begin_statement
Define a group $G$ with two generators $x,y$, subject (only) to the relations
$x^2=e$, $y^3=e$. Prove that $G$ is a coproduct of $C_2$ and $C_3$ in $\mathtt{Grp}$.
#+end_statement

Given any two morphisms $f\colon C_2 \to H$ and $g \colon C_3 \to H$, we define $h(x) = f(1)$ 
and $h(y) = g(1)$ as it should be to make the diagram commutative. There is
only a possible way to extend this morphism to $h \colon G \to H$.

** II.4. Group homomorphisms
*** Exercise II.4.3
#+begin_statement
Prove that a group of order $n$ is isomorphic to $\mathbb{Z}/n\mathbb{Z}$ if and only if it
contains an element of order $n$.
#+end_statement

If it contains $a$ of order $n$, then $e,a,a^2,\dots,a^{n-1}$ are $n$ different elements.
As the group is of order $n$, they constitute the whole group.

*** Exercise II.4.8
#+begin_statement
Let $G$ be a group, and $g \in G$. Prove that the function $\gamma_g \colon G \to G$ defined
by $\gamma_g(a) = gag^{-1}$ is an automorphism of $G$. Prove that the function $G \to \mathrm{Aut}(G)$
defined by $g \mapsto \gamma_g$ is a homomorphism. Prove that this homomorphism is trivial
if and only if $G$ is abelian.
#+end_statement

The function $\gamma_g$ is trivially a homomorphism, and it has the inverse $\gamma_{g^{-1}}$.
We can check that $g\mapsto \gamma_g$ is a homomorphism, as

\[
\gamma_h\gamma_g(a) = hga(hg)^{-1} = \gamma_{hg}(a).
\]

If the homomorphism is trivial, $a = gag^{-1}$ for any $a,g \in G$; this is 
equivalent to abelianity.

*** Exercise II.4.11
#+begin_statement
In due time, we will prove the easy fact that if $p$ is a prime integer then
the equation $x^d=1$ can have at most $d$ solutions in $\mathbb{Z}/p\mathbb{Z}$. Assume this fact,
and prove that the multiplicative group $G = (\mathbb{Z}/p\mathbb{Z})^{\ast}$ is cyclic.
#+end_statement

If the group is not cyclic there is no element of order $p-1$. So the element
of maximal order has order $d < p-1$, and every other element has a [[*Exercise II.1.15][divisor
of this order]] as its order. Then the equation $x^d = 1$ has more than $p-1$ roots,
contradicting the assumption.

*** TODO Exercise II.4.16
#+begin_statement
Prove /Wilson's theorem/: a positive integer $p$ is prime if and only if

\[(p-1)! \equiv -1  \mod p.
\]
#+end_statement

We are multiplying all elements of $(\mathbb{Z}/p\mathbb{Z})^{\ast} \cong (\mathbb{Z}/(p-1)\mathbb{Z})$

** II.5. Free groups
*** Exercise II.5.3
#+begin_statement
Use the universal property of free groups to prove that the map $j \colon A \to F(A)$ is
injective, for all sets $A$.
#+end_statement

If it were not injective, with $j(a) = j(b)$, every $f \colon A \to G$ should follow 
$f(a)=f(b)$, but given any two $a,b$ we can define $f \colon A \to \mathbb{Z}\times\mathbb{Z}$ by sending
$f(a) = (1,0)$, $f(b) = (0,1)$, and every other element to $0$.

*** Exercise II.5.6
#+begin_statement
Prove that the group $F(\left\{ x,y \right\})$ is a coproduct $\mathbb{Z}\ast\mathbb{Z}$ of $\mathbb{Z}$ by itself in the
category $\mathtt{Grp}$.
#+end_statement

Given $d \colon \left\{ a,b \right\} \to G$, we use the coproduct inclusions on $\mathtt{Set}$ to define 
individual arrows

\[\begin{tikzcd}[column sep=tiny]
& G & \\
& \left\{ a,b \right\}\uar{d} & \\
\left\{ a \right\} \arrow[bend left]{uur} \urar{i} & & 
\left\{ b \right\} \arrow[bend right]{uul} \ular[swap]{i}
\end{tikzcd}\]

and then simply use the universal property of the free modules of one
element as follows

\[\begin{tikzcd}[column sep=small]
& G & \\
& \mathbb{Z}\ast\mathbb{Z} \uar[dashed] & \\
\mathbb{Z}\ar{ur}\ar[dashed,bend left]{uur} & & 
\mathbb{Z}\ar{ul}\ar[dashed,bend right]{uul} \\
& \left\{ a,b \right\} \ar[dashed]{uu} &\\
\left\{ a \right\}\urar \arrow[bend left=90]{uuuur}  \ar{uu} &&
\left\{ b \right\}\ular \arrow[bend right=90]{uuuul} \ar{uu}
\end{tikzcd}\]

*** Exercise II.5.7
#+begin_statement
Extend the result of [[*Exercise II.5.6][Exercise 5.6]] to free groups $F(\left\{ x_1,\dots,x_n \right\})$ and to free
/abelian/ groups $F^{ab}(\left\{ x_1,\dots,x_n \right\})$.
#+end_statement

The same argument can be repeated $n$ times to obtain $\mathbb{Z}\ast \overset{n}\dots \ast\mathbb{Z}$ as free group.
As $\mathbb{Z}\oplus\mathbb{Z}$ is the abelian coproduct, $\mathbb{Z}\oplus\dots\oplus\mathbb{Z}$ is the free group.

** II.6. Subgroups
*** Exercise II.6.1
#+begin_statement
The group of invertible $n \times n$ matrices with entries in $\mathbb{R}$ is denoted $GL_n(\mathbb{R})$.
Similarly, $GL_n(\mathbb{C})$ denotes the group of $n \times n$ invertible matrices with complex
entries. Consider the following sets of matrices:

 * $SL_n(\mathbb{R}) = \left\{ M \in GL_n(\mathbb{R}) \mid \mathrm{det}(M)=1 \right\}$;
 * $SL_n(\mathbb{C}) = \left\{ M \in GL_n(\mathbb{C}) \mid \mathrm{det}(M)=1 \right\}$;
 * $O_n(\mathbb{R}) = \left\{ M \in GL_n(\mathbb{R}) \mid MM^t = M^tM = I_n \right\}$;
 * $SO_n(\mathbb{R}) = \left\{ M \in O_n(\mathbb{R}) \mid \mathrm{det}(M)=1 \right\}$;
 * $U(n) = \left\{ M \in GL_n(\mathbb{C}) \mid MM^{\dag} = M^{\dag}M = I_n \right\}$;
 * $SU(n) = \left\{ M \in U_n(\mathbb{C}) \mid \mathrm{det}(M) = 1 \right\}$;

Here $I_n$ stands for the $n \times n$ identity matrix, $M^t$ is the /transpose/ of $M$,
$M^{\dag}$ is the /conjugate transpose/ of $M$, and $\mathrm{det}(M)$ denotes the /determinant/
of $M$. Find all possible inclusions among these sets, and prove that in every
case the smaller set is a subgroup of the larger one.
#+end_statement

We are dealing with three different properties:

  1. The matrix has entries in $\mathbb{C}$.
  2. The matrix has its conjugate transpose as its inverse, $MM^{\dag}=I_n$.
  3. The matrix has determinant $1$, $\mathrm{det}(M) = 1$.

None of them implies the others. The three properties give rise to this 
three-dimensional cube

\[\begin{tikzcd}[column sep=tiny, every arrow/.append style={dash}]
&& GL(\mathbb{C}) & \\
& U(n) \urar & SL_n(\mathbb{C})\uar & GL(\mathbb{R})\ar{ul} \\
& SU(n) \uar\ar{ur} & O_n(\mathbb{R}) \ular\urar & SL_n(\mathbb{R}) \ular\uar\\
&& SO_n(\mathbb{R})\uar \urar\ular & & .
\end{tikzcd}\]

*** Exercise II.6.3
#+begin_statement
Prove that every matrix in $SU(2)$ may be written in the form

\[\begin{pmatrix}
a+bi & c+di \\
-c+di & a-bi
\end{pmatrix}\]

where $a,b,c,d \in \mathbb{R}$ and $a^2+b^2+c^2+d^2 = 1$. (Thus, $SU(2)$ may be
realized as a three-dimensional sphere embedded in $\mathbb{R}^4$; in particular,
it is /simply connected/.)
#+end_statement

If we take $\alpha,\beta,\gamma,\delta \in \mathbb{C}$, and create a special unitary matrix, we have 
the relationships

 * $|\alpha|+|\beta| = 1$
 * $\alpha\delta-\beta\gamma = 1$
 * $\alpha\overline{\gamma} + \beta\overline{\delta} = 0$

that are solved by $\alpha = \overline{\delta}$ and $\beta = -\overline{\gamma}$, while the first one gives us the
sphere condition.

* III. Rings and modules
** III.1. Definition of a ring
*** Exercise III.1.1
#+begin_statement
Prove that if $0=1$ in a ring $R$, then $R$ is a zero-ring.
#+end_statement

By definition,

\[
r = 1r = 0r = 0r+0r = 0.
\]

** III.5. Modules over a ring
*** Exercise III.5.4
#+begin_statement
Let $R$ be a ring. A nonzero $R\text{-module}$ is /simple/ (or /irreducible/) if its
only submodules are $\left\{ 0 \right\}$ and $M$. Let $M,N$ be simple modules, and let
$\varphi \colon M \to N$ be a homomorphism of $R\text{-modules}$. Prove that either $\varphi = 0$, or
$\varphi$ is an isomorphism. (This rather innocent statement is known as *Schur's 
Lemma*.)
#+end_statement

The kernel and image of $\varphi$ will be submodules, they only can be the total
submodule or the zero submodule, as $M,N$ are simple modules. There are two 
cases

  - If $\operatorname{ker}\phi = \{0\}$, it is a monomorphism. Its image must be different
    from $0$, thus it must be $N$.

  - If $\operatorname{ker} \phi = M$, we have $\phi = 0$.

** III.6. Products and coproducts in R-Mod
*** CHECK Exercise III.6.16
#+begin_statement
Let $R$ be a ring. A (left-)$R\text{-module}$ $M$ is /cyclic/ if $M = \left\langle m \right\rangle$ for
some $m \in M$. Prove that simple modules (cf. Exercise 5.4) are cyclic.
Prove that an $R\text{-module}$ $M$ is cyclic if and only if $M \cong R/I$ for some
(left-)ideal $I$. Prove that every quotient of a cyclic module is cyclic.
#+end_statement

**** Un módulo simple es cíclico
Tomemos un elemento suyo cualquiera y
creamos $<m>$. Ocurre que debe ser un submódulo y por ser simple, todo
el módulo.

**** Un cociente por ideal es cíclico.
 Sea $M = R/I$, un módulo sobre $R$ podemos generarlo simplemente 
 por $<1>$, luego es cíclico.
 Sea $M=<m>$ un módulo cíclico. Podemos tomar un isomorfismo que lleve
 $r \mapsto rm$ y definir $I = \{r\;|\;rm=0\}$. Por 1er Teorema de isomorfía:

 \[M \cong R/ker(\phi) \cong R/I\]

**** Todo cociente de cíclico es cíclico.
Usando el tercer teorema de isomorfía:

\[\frac{\frac{R}{I}}{J} \cong \frac{\frac{R}{I}}{\frac{I+J}{I}} \cong \frac{R}{I+J}\] (?)

** III.7. Complexes and homology
*** Exercise III.7.1. Exactitud entre ceros.

 \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow M \overset{}\longrightarrow 0 \overset{}\longrightarrow \dots \]

 Tenemos que el núcleo de la segunda debe ser igual a la imagen de la primera y
 por tanto, cero. Eso sólo es posible si $M=0$.

*** Exercise III.7.2. Exactitud entre isomorfías
     \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow M \overset{}\longrightarrow M' \overset{}\longrightarrow 0 \longrightarrow \dots\]
 Tenemos por el primer 0 la función inyectiva y por el segundo la función 
 sobreyectiva. Debe ser por tanto isomorfismo.

*** Exercise III.7.3. Kernel y cokernel en secuencia exacta
     \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow L \overset{}\longrightarrow M 
     \overset{\phi}\longrightarrow M' \longrightarrow N \longrightarrow 0 \longrightarrow \dots \]
 Por el primer 0 tengo una inyección $i$ de $L$ en $M$, que lo identifica con
 $im(i) = ker(\phi)$. Del segundo 0 tengo que la imagen de la proyección $\pi$ de
 $M'$ en $N$ es todo $N$. Entonces, por teorema de isomorfía y por exactitud:

 \[N = im(\pi) \cong \frac{M'}{ker(\pi)} = \frac{M'}{im(\phi)} = coker(\phi)\]

*** Exercise III.7.4. Hotel de Hilbert
 Dada una secuencia de enteros, podemos moverla un paso a la derecha:

 \[(a_1,a_2,a_3,\dots) \longrightarrow (0,a_1,a_2,\dots)\] 

 Para tener el morfismo $\alpha$ que nos da la secuencia exacta:

 \[ 0 \overset{}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\alpha}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\pi_1}\longrightarrow \mathbb{Z} \overset{}\longrightarrow 0 \]

 Dada una secuencia de enteros, podemos moverla a los sitios pares y hacer
 proyección de los impares luego:

 \[(a_1,a_2,a_3,\dots) \longrightarrow (0,a_1,0,a_2,0,a_3,\dots)\]

 Para tener los morfismos $\beta$ y $\pi$ que nos dan la secuencia exacta:

 \[ 0 \overset{}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\beta}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\pi}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{}\longrightarrow 0 \] 

*** Exercise III.7.5. Exactitud entre noetherianos
 Tenemos la secuencia exacta:

 \[ \dots \overset{}\longrightarrow L \overset{\alpha}\longrightarrow M \overset{\beta}\longrightarrow N \overset{}\longrightarrow \dots \]

 Y supongamos $L,N$ noetherianos. Sea entonces una sucesión de ideales \(\{M_i\}\),
 tenemos que las sucesiones de ideales \(\{\alpha^{-1}(M_i)\}\) y \(\{\beta(M_i)\}\) se estabilizarán
 a partir de un cierto $j$. Tomando un $i > j$ tendremos que $M_i = M_{i+1}$ y por tanto,
 se estabilizará la secuencia inicial.

 Supongamos que existiera $x \in M_{i+1}$ pero $x \notin M_i$. Dividimos en dos casos:

 *Caso 1*. $x \in im(\alpha)$, tendríamos que existiría algún elemento 
 $a \in \alpha^{-1}(x) \subset \alpha^{-1}(M_{i+1}) = \alpha^{-1}(M_{i})$, pero por definición entonces $x = \alpha(a) \in M_i$.

 *Caso 2*. $x \notin im(\alpha)$, tendríamos $\beta(x) \in \beta(M_{i+1})$. Existe un $y \in M_i$ tal que 
 $\beta(y) = \beta(x)$, es decir, $x-y \in ker(\beta)$. Pero entonces $x-y \in im(\alpha)$ y por tanto,
 $x-y \in M_i$, llevando a $x\in M_i$.

*** Exercise III.7.6. Epimorfismo escindido
 Sea una sucesión:

 \[ 0 \overset{}\longrightarrow ker(\phi) \overset{}\longrightarrow M \overset{\phi}\longrightarrow N \overset{}\longrightarrow 0 \]

 Supongamos que *escinde*, entonces $\phi$ es la proyección hacia $N$ y tiene
 como inversa derecha a la inclusión.

 Supongamos que *tiene inversa* derecha $\psi$, entonces buscamos un isomorfismo
 entre $M \cong ker(\phi) \oplus N$, que tenemos con estos dos morfismos:

 \[(k,n) \mapsto \psi n + k\]
 \[m \mapsto (m-\psi \phi m, \phi m)\]

*** Exercise III.7.10. Lema corto de los cinco 
 Si en el lema de la serpiente son $\lambda$ y $\nu$ isomorfismos, tenemos la sucesión:

 \[0 \longrightarrow 0 \longrightarrow ker(\mu) \longrightarrow 0 \overset{\delta}\longrightarrow
   0 \longrightarrow coker(\mu) \longrightarrow 0 \longrightarrow 0\]

 Por tanto, el kernel y cokernel de $\mu$ son nulos y es isomorfismo.

*** Exercise III.7.11. Todo morfismo de escisión es isomorfismo
 Directamente aplicando el ejercicio anterior, tenemos que $N \cong M_1 \oplus M_2$.

*** Exercise III.7.12. Lema de los cuatro (1)
 Lo probamos por caza del diagrama. Primero tomamos un elemento en el núcleo
 de C y aplicamos:

 - Inyectividad de $\delta$. 
 - Exactitud de $BCD$.
 - Exactitud de $ABC$.
 - Sobreyectividad de $\alpha$.
 - Exactitud de $ABC$.

 Teniendo que el elemento es nulo.

*** Exercise III.7.13. Lema de los cuatro (2)
 Volvemos a cazar diagramas. Tomamos un $c'$ en $coker(\gamma)$ y hacemos:

 - Exactitud de CDE.
 - Inyectividad en E.
 - Sobreyectividad de D.
 - Exactitud de CDE.

 Y así llegamos a un $z \in C$ que tiene como imagen un $z' \in C'$. Tomamos $c'-z'$,
 que tiene imagen nula en $D$ y aplicamos:

 - Exactitud de BCD.
 - Sobreyectividad en $B$.

 Y obtenemos un $x \in C$ que tiene como imagen a $c'-z'$. Finalmente: $\gamma(x+z) = c'$.

*** Exercise III.7.14. Lema de los cinco
 Trivial uniendo ambos lemas de los cuatro.

* VI. Linear Algebra
** VI.1. Free modules revisited
*** Exercise VI.1.1. R y C son isomorfos como espacios vectoriales de Q
Sabemos que $C \cong R \oplus R$. Dada una base $B$ de $\mathbb{R}$, podemos ver que será
infinita y por axioma de elección isomorfa a $B+B$, que será a su
vez una base de $\mathbb{R}^2$. Luego $\mathbb{R} \cong \mathbb{R} \oplus \mathbb{R}$.

*** Exercise VI.1.4. Álgebras de Lie
 Demostramos que $[u,v] = -[v,u]$. Ya que tenemos:

 $$[u,v] + [v,u] = [u,v] + [u,u] + [v,v] + [v,u] = [u+v,v] + [u+v,u] = [u+v,u+v] = 0$$

 Para todas las K-álgebras, tomar $[v,w] = vw-wv$ nos da un álgebra de Lie.
 Podemos verlo porque cumple las tres primeras propiedades que se le piden a un
 álgebra de Lie y además:

 \begin{align*}
 [[u,v],w] + [[v,w],u] + [[w,u],v] & = \\
 (uvw-vuw-wuv+wvu) &+\\
 (vwu-wvu-uvw+uwv) &+\\
 (wuv-uwv-vwu+vuw) &=\\
 0
 \end{align*}

*** Exercise VI.1.5. Sistemas generadores e independientes en dominios de integridad
 Un sistema independiente puede no crecer a base y un sistema generador
 puede no reducirse a base en un dominio de integridad. Como ejemplos
 tenemos $\mathbb{Z}$ con: {2} como sistema independiente y $\{2,3\}$ como sistema generador.
 Ninguno puede crear base porque las únicas bases posibles serían $\{1\}$ y $\{-1\}$.

*** Exercise VI.1.13. Un grupo abeliano con endomorfismos de característica 0.
 Si tiene endomorfismos que forman un cuerpo de característica 0, podemos
 identificar $\mathbb{Z}$ con los endomorfismos por propiedad universal y
 luego podemos extenderlo por contener $Q$ las inversas. De otro modo, 
 $Q$ es inicial en la categoría de cuerpos de característica 0, así, hay
 forma de identificarlo con endomorfismos del cuerpo.

 Así, nuestro grupo $A$ es espacio vectorial sobre $Q$. Y es de dimensión 1,
 porque si tuviera dimensión mayor y una base de más de un elemento, colapsar
 dos elementos de la base en uno sería un endomorfismo sin inversa.

*** Exercise VI.1.14. La potencia de un isomorfismo estabiliza kernel e imagen.
 Tenemos que $ker(\phi^n) \subset ker(\phi^{n+1})$ y que dos subespacios contenidos de la misma
 dimensión deben ser iguales. Por tanto, la dimensión debe crecer o estabilizarse
 a cada paso. Si la dimensión es finita debe estabilizarse en algún punto.

 Por otro lado, tenemos que las imágenes deben estabilizarse en dimensión
 para tener $ker(\phi^n) \oplus im(\phi^{n+1}) = V$. Y entonces, para que el kernel no crezca,
 ninguno de los vectores que forman la base de $im(\phi^n)$ pueden tener como
 imagen algo que esté en $ker(\phi)$, así que vuelven a tener como imagen algo en
 $im(\phi^{n+1})$, que debe estar contenido en $im(\phi^n)$ y ser de la misma
 dimensión.

** VI.2. Homomorphisms of free modules I
*** Exercise VI.2.1. Grupo isomorfo a la suma
 Tenemos que:

 \[
 \left( \begin{matrix} 1 & 0 \\ r & 1 \end{matrix} \right)
 \left( \begin{matrix} 1 & 0 \\ p & 1 \end{matrix} \right) =
 \left( \begin{matrix} 1 & 0 \\ r+p & 1 \end{matrix} \right)
 \]

 Luego la proyección del tercer elemento es un isomorfismo
 de grupos.

*** Exercise VI.2.6. Row echelon form
 Cuando trabajamos en un cuerpo podemos pasar a /row echelon form/ usando
 los siguientes pasos:

  - Pasamos el primer elemento no nulo a la fila más alta.
  - Lo hacemos uno con su inversa y reducimos toda la columna restante.
  - Hacemos lo mismo con la submatriz a la derecha y debajo de ese 1.

 Esto debe dejarnos sólo ceros debajo y encima de los 1 pivotes.

** VI.4. Presentations and resolutions
*** Exercise VI.4.1. Tor(M) es submódulo de M cuando R es dominio de integridad.
 Tenemos $Tor(M) = \{ m | \exists r \in R : r \neq 0, rm = 0\}$, y siendo dos elementos $m,n$ en $Tor(M)$, 
 que cumplen que $rm = 0$ y $qn = 0$, podemos
 ver que su suma será cerrada y que el producto por $r\in R$ será cerrado cuando
 $R$ es conmutativo:

  - $rq(m+n) = rqm+qrn = 0+0 = 0$
  - $r(pm) = p(rm) = 0$

 Usando aquí que es dominio de integridad y por tanto $rq \neq 0$.

*** Exercise VI.4.2. Hom(M,N) es libre de torsión cuando lo es N.
 Supongamos que no lo fuera, existiría un $f \in Hom_R(M,N)$ tal que 
 $rf = 0$ para algún $r$ no divisor de $0$. Pero entonces, esto haría
 que en el anillo $N$ existiese $rf(m) = 0$ para cualquier $m$, y por 
 ser libre de torsión, se tendría $f(m) = 0$ para todo $m$.
 Luego $f=0$.

 En particular $Hom_R(M,R)$ es libre de torsión.

*** Exercise VI.4.4. Propiedades del anulador
 Suponiendo $p,q \in Ann(R)$, tenemos que para todo $m \in M$ se tendrá
 $pm=0$ y $qm=0$. Por lo tanto $(p+q)m=0$ y $rpm = 0$, haciéndolo ideal.

**** M de torsión si y sólo si el anulador es no nulo.
 Si $Ann(M) \neq 0$, existe un elemento de $R$ que anula todo $M$, como
 además $R$ es dominio de integridad, este elemento no será divisor de 0, y $M$
 será torsión. Si $M$ es torsión y finitamente generado, tendrá un elemento
 $r_i$ que anulará cada uno de sus generadores $m_i$. Siendo $R$ conmutativo,
 el elemento producto estará en el anulador

                      \[
 \prod_{i} r_i
 \] 

 Nótese que si quitamos la condición de que $M$ sea finitamente generado, existen
 módulos como \(\mathbb{Z}_2 \oplus \mathbb{Z}_4 \oplus \mathbb{Z}_8 \dots\) que son torsión porque todo elemento se anula pero
 tienen anulador vacío porque no existen elementos que anulen todo el módulo.

*** Exercise VI.4.13. Complejo de Koszul

**** Es un complejo.
 Comprobamos que es un complejo viendo que las siguientes composiciones son $0$:

  - \(d_1 \circ d_2 (t) = bta - atb = 0\)
  - \(\pi \circ d_1 (r,s) = (ra+sb)\ mod(a,b)) = 0 \)

**** Es un complejo exacto cuando la secuencia es regular.
 Y comprobamos que es exacto en el caso en el que la secuencia es regular viendo
 que:

 - \(ker(d_2) = 0\), ya que $a$ no es divisor de cero.
 - \(ker(d_1) = <(b,-a)>\). Tenemos que $b$ no es divisor de cero módulo $a$, así, para que
   sea linealmente dependiente con $a$ necesitamos algo que sea cero módulo $a$. Este
   caso requiere $s$ múltiplo de $a$. Esto requiere estar dentro del ideal generado por
   $(b,-a)$.
 - Que la imagen de $d_1$ es el núcleo de $\pi$ y que la proyección es sobreyectiva
   es trivial.

*** Exercise VI.4.14. Complejo de Koszul en el caso de 3 elementos
**** Es un complejo
 Volvemos a comprobar que las composiciones son nulas. Tenemos de hecho que:

 \[d_2 \circ d_1 = d_3 \circ d_2 = 0\]

 Y que la proyección coincide con el generado por $d_1$.

**** Es un complejo exacto cuando la secuencia es regular
 Otra vez, como $c$ no es divisor de cero módulo $(a,b)$, tenemos que el kernel
 de $d_3$ es nulo. De la misma forma, se tiene que el $ker(d_2)=im(d_3)$, aplicando
 en cada caso el no ser divisor de cero. Vuelve a tenerse una ecuación similar
 que demuestra $ker(d_1) = im(d_2)$. El caso de la proyección es trivial.
*** Exercise VI.4.15. Resolución de Z sobre Z[x,y]
 Podemos encontrar una resolución como:

 \[0 \longrightarrow 
 \mathbb{Z}[x,y] \overset{\phi} \longrightarrow 
 \mathbb{Z}[x,y]^2 \overset{\delta} \longrightarrow 
 \mathbb{Z}[x,y] \overset{\pi} \longrightarrow 
 \mathbb{Z} \longrightarrow 0 \]

 Donde $\pi$ es un morfismo que cancela $x,y$. $\delta$ es un morfismo que lleva
 cada una de las copias del $1$ a $x$ e $y$. Finalmente, $\phi$ es monomorfismo
 que lleva $1$ a $(y,-x)$ que es generador de $ker(\delta)$.

* VIII. Linear algebra, reprise
** VIII.1. Preliminaries, reprise
*** Exercise VIII.1.2. Funtor plenamente fiel respeta isomorfías 
 Sea ${\cal F}(A) \cong {\cal F}(B)$, gracias a dos morfismos inversos $\alpha,\beta$. Como
 el funtor es pleno, existen dos morfismos preimagen de ambos
 llamados $\alpha',\beta'$ y tenemos que:

 \[{\cal F}(\alpha' \circ \beta') = \alpha \circ \beta = 1\]

 Por ser fiel, debemos tener $\alpha' \circ \beta' = 1$.
*** Exercise VIII.1.3. Acción de grupo como funtor
 Sea $G$ un grupo. Su acción sobre un objeto $C$ será un morfismo que
 envíe cada elemento del grupo a un isomorfismo de $C$. Es decir, un
 homomorfismo de grupos:

 \[(G,\ast) \longrightarrow (Aut(C),\circ)\]

 Pero como podemos ver $G$ como un objeto tal que cada uno de sus elementos
 sea un isomorfismo, tenemos claramente un isomorfismo:

 \[(Aut(G),\circ) \cong (G,\ast) \longrightarrow (Aut(C),\circ)\]

 Y podemos definir el funtor que lleva $G$ a $C$ y que lleva cada endomorfismo
 de $G$ a uno de $C$.

*** Exercise VIII.1.17. Compleción de un álgebra
 Tenemos que los $R/I^n$ son módulos en R-Mod, por tanto, la cadena siguiente
 tendrá límite. Donde los morfismos serán las inclusiones naturales:

 \[\dots \longrightarrow R/I^3 \longrightarrow R/I^2 \longrightarrow R/I \]

 Ese límite lo llamamos $R_I$, y es el submódulo de secuencias coherentes de $\prod_i R/I^i$.
 Es decir, un elemento suyo es una secuencia tal que cada elemento es la proyección
 del siguiente. Este submódulo es conmutativo porque lo es el producto de todos los módulos.

 Podemos incluir $R$ en $R_I$ llevando el $1$ a $(1,1,1,\dots)$. Y esto conmutará con las
 proyecciones naturales que nos daba la propiedad universal.
 Para que $x$ se anule al incluirlo en $R_I$ desde $R$, necesitamos que todas las proyecciones
 de su imagen sean $0$, así que necesitamos que pertenezca a $I_n$ para cada $n$.

*** Exercise VIII.1.19. Enteros p-ádicos
 Llamamos enteros p-ádicos al límite $\mathbb{Z}_p = \varprojlim \mathbb{Z}/p^i\mathbb{Z}$, y números p-ádicos a su cuerpo de fracciones
 $\mathbb{Q}_p$. Por definición, un entero p-ádico es una secuencia de enteros $\{a_i\}$ tales que:

 \[ a_s \equiv a_r  \mod (p^s)\]

 Para cualesquiera $s \leq r$. De otra forma, cada entero tiene una expansión única:

 \[ A = b_0 + b_1 p + b_2 p^2 + b_3 p^3 + \dots\]

 Donde $b_i < p$. Esto es así porque dada una secuencia $(a_i)$, tenemos la igualdad:

 \[b_0 = a_0\]
 \[b_i p^i + a_{i+1} = a_i\]

 Y se puede construir una desde la otra usando que $a_i - a_{i+1} \equiv_{p^i} 0$. 

 A partir de aquí podemos hacer aritmética como usualmente desde estos desarrollos de los
 números p-ádicos.
** VIII.2. Tensor products, and the Tor functors
*** Exercise VIII.2.14. Tor en 0 es el producto tensor
 La definición inicial de Tor es como:

 \[Tor^R_i(M,N) = H_i(M_\bullet \otimes N)\]

 Y como tenemos que el complejo $M_\bullet \otimes N$ es el siguiente,
 siendo $S_0$ una base de $M$, y $S_1$ base de las relaciones de $M$:

 \[ \dots \overset{}\longrightarrow N^{\oplus S_2} 
 \overset{\phi_2}\longrightarrow N^{\oplus S_1} 
 \overset{\phi_1}\longrightarrow N^{\oplus S_0} 
 \overset{}\longrightarrow 0 \]

 Que ha salido de tensar el siguiente complejo exacto:

 \[ \dots \overset{}\longrightarrow R^{\oplus S_1} \overset{\psi_2}\longrightarrow R^{\oplus S_0} \overset{\psi_1}\longrightarrow M \overset{}\longrightarrow 0 \]

 Tenemos que:

 \[H_i(M_\bullet \otimes N) \cong \frac{N^{\otimes S_0}}{im(\phi_1)} \cong 
 \frac{R^{\otimes S_0}}{im(\psi_2)} \otimes N \cong M \otimes N \]

 Donde usamos la exactitud de la segunda secuencia con el primer teorema de isomorfía
 y el hecho de que el functor $\otimes N$ respeta los colímites y por tanto el cociente, que puede
 verse como coecualizador.

