#+TITLE: Algebra: chapter 0
#+DESCRIPTION: Exercises on the Paolo Aluffi's book

#+SETUPFILE: config.setup
#+SETUPFILE: essay.setup
#+LANGUAGE: en,es
#+OPTIONS: toc:nil
#+TODO: TODO WIP | CHECK

* I. Preliminaries: Set theory and categories
** I.5. Universal properties
*** Exercise I.5.12
#+begin_statement
Define notions of /fibered products/ and /coproducts/, as terminal objects of
the categories $C_{\alpha,\beta}$ and $C^{\alpha,\beta}$ considered in Example 3.10, by stating carefully
the corresponding universal properties.

As it happens, $\mathtt{Set}$ has both fibered products and coproducts. Define these
objects 'concretely', in terms of naive set theory.
#+end_statement

**** Fibered products
Given $\alpha\colon A \to C$ and $\beta \colon B \to C$, we take the objects of the category
to be commutative diagrams

\[\begin{tikzcd}[row sep=tiny]
 & A \drar{\alpha} & \\
Z\drar{g}\urar{f} && C\\
& B \urar{\beta} & &.
\end{tikzcd}\]

And morphisms to be of the form

\[\begin{tikzcd}[row sep=tiny]
& & A \drar{\alpha} & \\
Z' \rar{h}\ar[bend right]{drr}{g'} \ar[bend left]{urr}{f'} &
Z\drar{g}\urar{f} && C\\
& & B \urar{\beta} & &.
\end{tikzcd}\]

With the trivial identity $\mathrm{id}_Z \colon (Z,f,g) \to (Z,f,g)$. The terminal object
should be the one such that every other object's morphisms descompose
through it.

\[\begin{tikzcd}[row sep=tiny]
& & A \drar{\alpha} & \\
Z' \rar[dashed]{\exists! h}\ar[bend right]{drr}{g'} \ar[bend left]{urr}{f'} &
F\drar{\pi_{\beta}}\urar{\pi_{\alpha}} && C\\
& & B \urar{\beta} & &.
\end{tikzcd}\]

**** Fibered coproducts
The same idea can be applied to the dual construction

\[\begin{tikzcd}[row sep=tiny]
& & A \dlar{\iota_A}\ar[bend right]{lld}{f'} & \\
Z &
F \lar[dashed]{\exists! h} && 
C \ular{f}\dlar{g}\\
& & B \ular{\iota_B}\ar[bend left]{llu}{g'} & &.
\end{tikzcd}\]

**** In the category of sets
In $\mathtt{Set}$, the fibered product will be

\[
\left\{ (a,b) \in A \times B \mid \alpha(a) = \beta(b) \right\},
\]

as we can show using the product universal property. The fibered coproduct
is the coproduct divided by the equivalence relation generated by the
pairs $a \sim b$ such that $\exists c\colon a = f(c), b = g(c)$.

* II. Groups, first encounter
** II.1. Definition of group
*** Exercise II.1.1
#+begin_statement
Write a careful proof that every group is the group of isomorphisms of a
grupoid. In particular, every group is the group of automorphisms of some
object in some category.
#+end_statement

Given a group $(G,\bullet)$, we can define an object $G$ with morphisms the elements
of the group. Composition will be the binary operation of the group, and we
can check, using the group properties, that category axioms hold

 1. *Identity*, there is an identity element on $G$ which acts as the identity
    morphism: $e \circ a = a = a \circ e$.
 2. *Associativity* holds directly: $a \circ (b\circ c) = (a \circ b)\circ c$.

This only object defines a category which is also a grupoid, as every arrow
has an *inverse* by the last property of groups: every element of the group has
an inverse.

*** Exercise II.1.2
#+begin_statement
Consider the 'sets of numbers' listed in 1.1, and decide which are made into 
groups by conventional operations such as $+$ and $\cdot$. Even if the answer is negative,
see if variations on the definition of these sets lead to groups.
#+end_statement

**** The empty set
It is not a group, as it has no identity.

**** Naturals
They form no group with addition, as not every element has an inverse.

**** Integers
They are a commutative group with the addition.

**** Rational numbers
They are a group with addition, and also a group with multiplication if we
consider $0$ out of the group.

**** Real numbers
They follow the same logic as the rationals.

**** Complex numbers
Same logic as the rationals.

*** Exercise II.1.13
#+begin_statement
Give an example showing that $|gh|$ is not necessarily equal to $\mathrm{lcm}(|g|,|h|)$, even
if $g$ and $h$ commute.
#+end_statement

In $(\mathbb{Z}/\mathbb{Z}_4,+)$, we have $\mathrm{lcm}(|1|,|1|) = |1| = 4$, but $|1+1| = 2$.

*** Exercise II.1.14
#+begin_statement
As a counterpoint to [[*Exercise II.1.13][Exercise 13]], prove that if $g$ and $h$ commute, 
and $\mathrm{gcd}(|g|,|h|) = 1$, then $|gh| = |g||h|$.
#+end_statement

We know that $|gh| = N \mid |g||h|$. If we divide to obtain $g^{N} = (h^{-1})^{N}$, we have

 * $1 = \left( g^{-1} \right)^{N|g|} = h^{N|g|}$
 * $1 = \left( h^{-1} \right)^{N|h|} = g^{N|h|}$

and then, $|h| \mid N|g|$ and they are coprimes, so $|h| \mid N$. Likewise, $|g| \mid N$.
Finally, $|gh| = \mathrm{lcm}(|h|,|g|) \mid N$.

** 2. Examples of groups
*** Exercise 2
#+begin_statement
Prove that if $d \leq n$, then $S_n$ contains elements of order $d$.
#+end_statement

The element $(1\;2\;\dots\;d)$ has order $d$.

*** TODO Exercise 5
** 3. The category Grp
*** Exercise 1
#+begin_statement
Let $\varphi\colon G \to H$ be a morphism in a category $C$ with products. Explain why there
is a unique morphism

\[(\varphi\times\varphi)\colon G\times G \to H \times H.\]
#+end_statement

The real morphism is $(\varphi\circ \pi_1 \times \varphi \circ \pi_2)$, using the projections from $C$ as presented
in the following diagram

\[\begin{tikzcd}[column sep=small,row sep=tiny]
& G \times G\drar\dlar\ar[dashed]{dd}{\varphi\times\varphi} & \\
G\ar{dd} & & G\ar{dd} \\
& H \times H\drar\dlar & \\
H & & H \\
\end{tikzcd}\]

*** Exercise II.3.8
#+begin_statement
Define a group $G$ with two generators $x,y$, subject (only) to the relations
$x^2=e$, $y^3=e$. Prove that $G$ is a coproduct of $C_2$ and $C_3$ in $\mathtt{Grp}$.
#+end_statement

Given any two morphisms $f\colon C_2 \to H$ and $g \colon C_3 \to H$, we define $h(x) = f(1)$ 
and $h(y) = g(1)$ as it should be to make the diagram commutative. There is
only a possible way to extend this morphism to $h \colon G \to H$.

* III. Rings and modules
** 5. Modules over a ring
*** 4. Simple modules. Lema de Schur
 Tenemos que, siendo kernel e imagen submódulos, serán,
 o bien $\{0\}$, o bien $M$. Dividiendo por casos:
  - $ker \phi = \{0\}$, nos da un monomorfismo. Como su imagen debe ser
    distinta de $0$ para algún elemento y es submódulo, debe ser $N$.
  - $ker \phi = M$, nos da $\phi = 0$.

** 6. Products and coproducts in R-Mod
*** 16. Cyclic modules
**** Un módulo simple es cíclico
 Tomemos un elemento suyo cualquiera y
 creamos $<m>$. Ocurre que debe ser un submódulo y por ser simple, todo
 el módulo.

**** Un cociente por ideal es cíclico.
 Sea $M = R/I$, un módulo sobre $R$ podemos generarlo simplemente 
 por $<1>$, luego es cíclico.
 Sea $M=<m>$ un módulo cíclico. Podemos tomar un isomorfismo que lleve
 $r \mapsto rm$ y definir $I = \{r\;|\;rm=0\}$. Por 1er Teorema de isomorfía:

 \[M \cong R/ker(\phi) \cong R/I\]

**** Todo cociente de cíclico es cíclico.
 Usando el tercer teorema de isomorfía:

 \[\frac{\frac{R}{I}}{J} \cong \frac{\frac{R}{I}}{\frac{I+J}{I}} \cong \frac{R}{I+J}\] (?)

** 7. Complexes and homology
*** 1. Exactitud entre ceros.
 \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow M \overset{}\longrightarrow 0 \overset{}\longrightarrow \dots \]
 Tenemos que el núcleo de la segunda debe ser igual a la imagen de la primera y
 por tanto, cero. Eso sólo es posible si $M=0$.

*** 2. Exactitud entre isomorfías
     \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow M \overset{}\longrightarrow M' \overset{}\longrightarrow 0 \longrightarrow \dots\]
 Tenemos por el primer 0 la función inyectiva y por el segundo la función 
 sobreyectiva. Debe ser por tanto isomorfismo.

*** 3. Kernel y cokernel en secuencia exacta
     \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow L \overset{}\longrightarrow M 
     \overset{\phi}\longrightarrow M' \longrightarrow N \longrightarrow 0 \longrightarrow \dots \]
 Por el primer 0 tengo una inyección $i$ de $L$ en $M$, que lo identifica con
 $im(i) = ker(\phi)$. Del segundo 0 tengo que la imagen de la proyección $\pi$ de
 $M'$ en $N$ es todo $N$. Entonces, por teorema de isomorfía y por exactitud:

 \[N = im(\pi) \cong \frac{M'}{ker(\pi)} = \frac{M'}{im(\phi)} = coker(\phi)\]

*** 4. Hotel de Hilbert
 Dada una secuencia de enteros, podemos moverla un paso a la derecha:

 \[(a_1,a_2,a_3,\dots) \longrightarrow (0,a_1,a_2,\dots)\] 

 Para tener el morfismo $\alpha$ que nos da la secuencia exacta:

 \[ 0 \overset{}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\alpha}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\pi_1}\longrightarrow \mathbb{Z} \overset{}\longrightarrow 0 \]

 Dada una secuencia de enteros, podemos moverla a los sitios pares y hacer
 proyección de los impares luego:

 \[(a_1,a_2,a_3,\dots) \longrightarrow (0,a_1,0,a_2,0,a_3,\dots)\]

 Para tener los morfismos $\beta$ y $\pi$ que nos dan la secuencia exacta:

 \[ 0 \overset{}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\beta}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\pi}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{}\longrightarrow 0 \] 

*** 5. Exactitud entre noetherianos
 Tenemos la secuencia exacta:

 \[ \dots \overset{}\longrightarrow L \overset{\alpha}\longrightarrow M \overset{\beta}\longrightarrow N \overset{}\longrightarrow \dots \]

 Y supongamos $L,N$ noetherianos. Sea entonces una sucesión de ideales \(\{M_i\}\),
 tenemos que las sucesiones de ideales \(\{\alpha^{-1}(M_i)\}\) y \(\{\beta(M_i)\}\) se estabilizarán
 a partir de un cierto $j$. Tomando un $i > j$ tendremos que $M_i = M_{i+1}$ y por tanto,
 se estabilizará la secuencia inicial.

 Supongamos que existiera $x \in M_{i+1}$ pero $x \notin M_i$. Dividimos en dos casos:

 *Caso 1*. $x \in im(\alpha)$, tendríamos que existiría algún elemento 
 $a \in \alpha^{-1}(x) \subset \alpha^{-1}(M_{i+1}) = \alpha^{-1}(M_{i})$, pero por definición entonces $x = \alpha(a) \in M_i$.

 *Caso 2*. $x \notin im(\alpha)$, tendríamos $\beta(x) \in \beta(M_{i+1})$. Existe un $y \in M_i$ tal que 
 $\beta(y) = \beta(x)$, es decir, $x-y \in ker(\beta)$. Pero entonces $x-y \in im(\alpha)$ y por tanto,
 $x-y \in M_i$, llevando a $x\in M_i$.

*** 6. Epimorfismo escindido
 Sea una sucesión:

 \[ 0 \overset{}\longrightarrow ker(\phi) \overset{}\longrightarrow M \overset{\phi}\longrightarrow N \overset{}\longrightarrow 0 \]

 Supongamos que *escinde*, entonces $\phi$ es la proyección hacia $N$ y tiene
 como inversa derecha a la inclusión.

 Supongamos que *tiene inversa* derecha $\psi$, entonces buscamos un isomorfismo
 entre $M \cong ker(\phi) \oplus N$, que tenemos con estos dos morfismos:

 \[(k,n) \mapsto \psi n + k\]
 \[m \mapsto (m-\psi \phi m, \phi m)\]

*** 10. Lema corto de los cinco 
 Si en el lema de la serpiente son $\lambda$ y $\nu$ isomorfismos, tenemos la sucesión:

 \[0 \longrightarrow 0 \longrightarrow ker(\mu) \longrightarrow 0 \overset{\delta}\longrightarrow
   0 \longrightarrow coker(\mu) \longrightarrow 0 \longrightarrow 0\]

 Por tanto, el kernel y cokernel de $\mu$ son nulos y es isomorfismo.

*** 11. Todo morfismo de escisión es isomorfismo
 Directamente aplicando el ejercicio anterior, tenemos que $N \cong M_1 \oplus M_2$.

*** 12. Lema de los cuatro (1)
 Lo probamos por caza del diagrama. Primero tomamos un elemento en el núcleo
 de C y aplicamos:

 - Inyectividad de $\delta$. 
 - Exactitud de $BCD$.
 - Exactitud de $ABC$.
 - Sobreyectividad de $\alpha$.
 - Exactitud de $ABC$.

 Teniendo que el elemento es nulo.

*** 13. Lema de los cuatro (2)
 Volvemos a cazar diagramas. Tomamos un $c'$ en $coker(\gamma)$ y hacemos:

 - Exactitud de CDE.
 - Inyectividad en E.
 - Sobreyectividad de D.
 - Exactitud de CDE.

 Y así llegamos a un $z \in C$ que tiene como imagen un $z' \in C'$. Tomamos $c'-z'$,
 que tiene imagen nula en $D$ y aplicamos:

 - Exactitud de BCD.
 - Sobreyectividad en $B$.

 Y obtenemos un $x \in C$ que tiene como imagen a $c'-z'$. Finalmente: $\gamma(x+z) = c'$.

*** 14. Lema de los cinco
 Trivial uniendo ambos lemas de los cuatro.

* VI. Linear Algebra
** 1. Free modules revisited
*** 1. R y C son isomorfos como espacios vectoriales de Q
 Sabemos que $C \cong R \oplus R$. Dada una base $B$ de $\mathbb{R}$, podemos ver que será
 infinita y por axioma de elección isomorfa a $B+B$, que será a su
 vez una base de $\mathbb{R}^2$. Luego $\mathbb{R} \cong \mathbb{R} \oplus \mathbb{R}$.

*** 4. Álgebras de Lie
 Demostramos que $[u,v] = -[v,u]$. Ya que tenemos:

 $$[u,v] + [v,u] = [u,v] + [u,u] + [v,v] + [v,u] = [u+v,v] + [u+v,u] = [u+v,u+v] = 0$$

 Para todas las K-álgebras, tomar $[v,w] = vw-wv$ nos da un álgebra de Lie.
 Podemos verlo porque cumple las tres primeras propiedades que se le piden a un
 álgebra de Lie y además:

 \begin{align*}
 [[u,v],w] + [[v,w],u] + [[w,u],v] & = \\
 (uvw-vuw-wuv+wvu) &+\\
 (vwu-wvu-uvw+uwv) &+\\
 (wuv-uwv-vwu+vuw) &=\\
 0
 \end{align*}

*** 5. Sistemas generadores e independientes en dominios de integridad
 Un sistema independiente puede no crecer a base y un sistema generador
 puede no reducirse a base en un dominio de integridad. Como ejemplos
 tenemos $\mathbb{Z}$ con: {2} como sistema independiente y $\{2,3\}$ como sistema generador.
 Ninguno puede crear base porque las únicas bases posibles serían $\{1\}$ y $\{-1\}$.

*** 13. Un grupo abeliano con endomorfismos de característica 0.
 Si tiene endomorfismos que forman un cuerpo de característica 0, podemos
 identificar $\mathbb{Z}$ con los endomorfismos por propiedad universal y
 luego podemos extenderlo por contener $Q$ las inversas. De otro modo, 
 $Q$ es inicial en la categoría de cuerpos de característica 0, así, hay
 forma de identificarlo con endomorfismos del cuerpo.

 Así, nuestro grupo $A$ es espacio vectorial sobre $Q$. Y es de dimensión 1,
 porque si tuviera dimensión mayor y una base de más de un elemento, colapsar
 dos elementos de la base en uno sería un endomorfismo sin inversa.

*** 14. La potencia de un isomorfismo estabiliza kernel e imagen.
 Tenemos que $ker(\phi^n) \subset ker(\phi^{n+1})$ y que dos subespacios contenidos de la misma
 dimensión deben ser iguales. Por tanto, la dimensión debe crecer o estabilizarse
 a cada paso. Si la dimensión es finita debe estabilizarse en algún punto.

 Por otro lado, tenemos que las imágenes deben estabilizarse en dimensión
 para tener $ker(\phi^n) \oplus im(\phi^{n+1}) = V$. Y entonces, para que el kernel no crezca,
 ninguno de los vectores que forman la base de $im(\phi^n)$ pueden tener como
 imagen algo que esté en $ker(\phi)$, así que vuelven a tener como imagen algo en
 $im(\phi^{n+1})$, que debe estar contenido en $im(\phi^n)$ y ser de la misma
 dimensión.

** 2. Homomorphisms of free modules I
*** 1. Grupo isomorfo a la suma
 Tenemos que:

 \[
 \left( \begin{matrix} 1 & 0 \\ r & 1 \end{matrix} \right)
 \left( \begin{matrix} 1 & 0 \\ p & 1 \end{matrix} \right) =
 \left( \begin{matrix} 1 & 0 \\ r+p & 1 \end{matrix} \right)
 \]

 Luego la proyección del tercer elemento es un isomorfismo
 de grupos.

*** 6. Row echelon form
 Cuando trabajamos en un cuerpo podemos pasar a /row echelon form/ usando
 los siguientes pasos:

  - Pasamos el primer elemento no nulo a la fila más alta.
  - Lo hacemos uno con su inversa y reducimos toda la columna restante.
  - Hacemos lo mismo con la submatriz a la derecha y debajo de ese 1.

 Esto debe dejarnos sólo ceros debajo y encima de los 1 pivotes.

** 4. Presentations and resolutions
*** 1. Tor(M) es submódulo de M cuando R es dominio de integridad.
 Tenemos $Tor(M) = \{ m | \exists r \in R : r \neq 0, rm = 0\}$, y siendo dos elementos $m,n$ en $Tor(M)$, 
 que cumplen que $rm = 0$ y $qn = 0$, podemos
 ver que su suma será cerrada y que el producto por $r\in R$ será cerrado cuando
 $R$ es conmutativo:

  - $rq(m+n) = rqm+qrn = 0+0 = 0$
  - $r(pm) = p(rm) = 0$

 Usando aquí que es dominio de integridad y por tanto $rq \neq 0$.

*** 2. Hom(M,N) es libre de torsión cuando lo es N.
 Supongamos que no lo fuera, existiría un $f \in Hom_R(M,N)$ tal que 
 $rf = 0$ para algún $r$ no divisor de $0$. Pero entonces, esto haría
 que en el anillo $N$ existiese $rf(m) = 0$ para cualquier $m$, y por 
 ser libre de torsión, se tendría $f(m) = 0$ para todo $m$.
 Luego $f=0$.

 En particular $Hom_R(M,R)$ es libre de torsión.

*** 4. Propiedades del anulador
 Suponiendo $p,q \in Ann(R)$, tenemos que para todo $m \in M$ se tendrá
 $pm=0$ y $qm=0$. Por lo tanto $(p+q)m=0$ y $rpm = 0$, haciéndolo ideal.

**** M de torsión si y sólo si el anulador es no nulo.
 Si $Ann(M) \neq 0$, existe un elemento de $R$ que anula todo $M$, como
 además $R$ es dominio de integridad, este elemento no será divisor de 0, y $M$
 será torsión. Si $M$ es torsión y finitamente generado, tendrá un elemento
 $r_i$ que anulará cada uno de sus generadores $m_i$. Siendo $R$ conmutativo,
 el elemento producto estará en el anulador

                      \[
 \prod_{i} r_i
 \] 

 Nótese que si quitamos la condición de que $M$ sea finitamente generado, existen
 módulos como \(\mathbb{Z}_2 \oplus \mathbb{Z}_4 \oplus \mathbb{Z}_8 \dots\) que son torsión porque todo elemento se anula pero
 tienen anulador vacío porque no existen elementos que anulen todo el módulo.

*** 13. Complejo de Koszul

**** Es un complejo.
 Comprobamos que es un complejo viendo que las siguientes composiciones son $0$:

  - \(d_1 \circ d_2 (t) = bta - atb = 0\)
  - \(\pi \circ d_1 (r,s) = (ra+sb)\ mod(a,b)) = 0 \)

**** Es un complejo exacto cuando la secuencia es regular.
 Y comprobamos que es exacto en el caso en el que la secuencia es regular viendo
 que:

 - \(ker(d_2) = 0\), ya que $a$ no es divisor de cero.
 - \(ker(d_1) = <(b,-a)>\). Tenemos que $b$ no es divisor de cero módulo $a$, así, para que
   sea linealmente dependiente con $a$ necesitamos algo que sea cero módulo $a$. Este
   caso requiere $s$ múltiplo de $a$. Esto requiere estar dentro del ideal generado por
   $(b,-a)$.
 - Que la imagen de $d_1$ es el núcleo de $\pi$ y que la proyección es sobreyectiva
   es trivial.

*** 14. Complejo de Koszul en el caso de 3 elementos
**** Es un complejo
 Volvemos a comprobar que las composiciones son nulas. Tenemos de hecho que:

 \[d_2 \circ d_1 = d_3 \circ d_2 = 0\]

 Y que la proyección coincide con el generado por $d_1$.

**** Es un complejo exacto cuando la secuencia es regular
 Otra vez, como $c$ no es divisor de cero módulo $(a,b)$, tenemos que el kernel
 de $d_3$ es nulo. De la misma forma, se tiene que el $ker(d_2)=im(d_3)$, aplicando
 en cada caso el no ser divisor de cero. Vuelve a tenerse una ecuación similar
 que demuestra $ker(d_1) = im(d_2)$. El caso de la proyección es trivial.
*** 15. Resolución de Z sobre Z[x,y]
 Podemos encontrar una resolución como:

 \[0 \longrightarrow 
 \mathbb{Z}[x,y] \overset{\phi} \longrightarrow 
 \mathbb{Z}[x,y]^2 \overset{\delta} \longrightarrow 
 \mathbb{Z}[x,y] \overset{\pi} \longrightarrow 
 \mathbb{Z} \longrightarrow 0 \]

 Donde $\pi$ es un morfismo que cancela $x,y$. $\delta$ es un morfismo que lleva
 cada una de las copias del $1$ a $x$ e $y$. Finalmente, $\phi$ es monomorfismo
 que lleva $1$ a $(y,-x)$ que es generador de $ker(\delta)$.

* VIII. Linear algebra, reprise
** 1. Preliminaries, reprise
*** 1.2. Funtor plenamente fiel respeta isomorfías 
 Sea ${\cal F}(A) \cong {\cal F}(B)$, gracias a dos morfismos inversos $\alpha,\beta$. Como
 el funtor es pleno, existen dos morfismos preimagen de ambos
 llamados $\alpha',\beta'$ y tenemos que:

 \[{\cal F}(\alpha' \circ \beta') = \alpha \circ \beta = 1\]

 Por ser fiel, debemos tener $\alpha' \circ \beta' = 1$.
*** 1.3. Acción de grupo como funtor
 Sea $G$ un grupo. Su acción sobre un objeto $C$ será un morfismo que
 envíe cada elemento del grupo a un isomorfismo de $C$. Es decir, un
 homomorfismo de grupos:

 \[(G,\ast) \longrightarrow (Aut(C),\circ)\]

 Pero como podemos ver $G$ como un objeto tal que cada uno de sus elementos
 sea un isomorfismo, tenemos claramente un isomorfismo:

 \[(Aut(G),\circ) \cong (G,\ast) \longrightarrow (Aut(C),\circ)\]

 Y podemos definir el funtor que lleva $G$ a $C$ y que lleva cada endomorfismo
 de $G$ a uno de $C$.

*** 1.17. Compleción de un álgebra
 Tenemos que los $R/I^n$ son módulos en R-Mod, por tanto, la cadena siguiente
 tendrá límite. Donde los morfismos serán las inclusiones naturales:

 \[\dots \longrightarrow R/I^3 \longrightarrow R/I^2 \longrightarrow R/I \]

 Ese límite lo llamamos $R_I$, y es el submódulo de secuencias coherentes de $\prod_i R/I^i$.
 Es decir, un elemento suyo es una secuencia tal que cada elemento es la proyección
 del siguiente. Este submódulo es conmutativo porque lo es el producto de todos los módulos.

 Podemos incluir $R$ en $R_I$ llevando el $1$ a $(1,1,1,\dots)$. Y esto conmutará con las
 proyecciones naturales que nos daba la propiedad universal.
 Para que $x$ se anule al incluirlo en $R_I$ desde $R$, necesitamos que todas las proyecciones
 de su imagen sean $0$, así que necesitamos que pertenezca a $I_n$ para cada $n$.

*** 1.19. Enteros p-ádicos
 Llamamos enteros p-ádicos al límite $\mathbb{Z}_p = \varprojlim \mathbb{Z}/p^i\mathbb{Z}$, y números p-ádicos a su cuerpo de fracciones
 $\mathbb{Q}_p$. Por definición, un entero p-ádico es una secuencia de enteros $\{a_i\}$ tales que:

 \[ a_s \equiv a_r  \mod (p^s)\]

 Para cualesquiera $s \leq r$. De otra forma, cada entero tiene una expansión única:

 \[ A = b_0 + b_1 p + b_2 p^2 + b_3 p^3 + \dots\]

 Donde $b_i < p$. Esto es así porque dada una secuencia $(a_i)$, tenemos la igualdad:

 \[b_0 = a_0\]
 \[b_i p^i + a_{i+1} = a_i\]

 Y se puede construir una desde la otra usando que $a_i - a_{i+1} \equiv_{p^i} 0$. 

 A partir de aquí podemos hacer aritmética como usualmente desde estos desarrollos de los
 números p-ádicos.
** 2. Tensor products, and the Tor functors
*** 2.14. Tor en 0 es el producto tensor
 La definición inicial de Tor es como:

 \[Tor^R_i(M,N) = H_i(M_\bullet \otimes N)\]

 Y como tenemos que el complejo $M_\bullet \otimes N$ es el siguiente,
 siendo $S_0$ una base de $M$, y $S_1$ base de las relaciones de $M$:

 \[ \dots \overset{}\longrightarrow N^{\oplus S_2} 
 \overset{\phi_2}\longrightarrow N^{\oplus S_1} 
 \overset{\phi_1}\longrightarrow N^{\oplus S_0} 
 \overset{}\longrightarrow 0 \]

 Que ha salido de tensar el siguiente complejo exacto:

 \[ \dots \overset{}\longrightarrow R^{\oplus S_1} \overset{\psi_2}\longrightarrow R^{\oplus S_0} \overset{\psi_1}\longrightarrow M \overset{}\longrightarrow 0 \]

 Tenemos que:

 \[H_i(M_\bullet \otimes N) \cong \frac{N^{\otimes S_0}}{im(\phi_1)} \cong 
 \frac{R^{\otimes S_0}}{im(\psi_2)} \otimes N \cong M \otimes N \]

 Donde usamos la exactitud de la segunda secuencia con el primer teorema de isomorfía
 y el hecho de que el functor $\otimes N$ respeta los colímites y por tanto el cociente, que puede
 verse como coecualizador.
* Notes
** III. Anillos y módulos
*** 7. Complejos y homología
**** 7.1. Complejos y secuencias exactas.
 #+begin_definition
 *Complejo*. Un complejo es una serie de morfismos $d_i$ entre R-Módulos:

 \[\dots \longrightarrow M_{i+1} \longrightarrow M_i \longrightarrow M_{i-1} \longrightarrow \dots\]

 tales que $d_i \circ d_{i+1} = 0$.
 #+end_definition

 Además lo llamamos *exacto* cuando $im (d_{i+1}) = ker (d_i)$.

 #+begin_proposition
 *Exactitud de monomorfismos y epimorfismos*. Dos complejos de la forma:

 \[ \dots \longrightarrow 0 \longrightarrow L \overset{\alpha}\longrightarrow M \longrightarrow \dots \]
 \[ \dots \longrightarrow M \overset{\beta} \longrightarrow N \longrightarrow 0 \longrightarrow \dots \]

 Son exactos en $L$ y $N$ ssi $\alpha$ y $\beta$ son monomorfismo y epimorfismo, 
 respectivamente.
 #+end_proposition

 #+begin_definition
 *Secuencia exacta corta*. Una secuencia exacta corta es un complejo de la forma:

 \[ 0 \longrightarrow L \overset{\alpha}\longrightarrow M \overset{\beta}\longrightarrow N \longrightarrow 0 \]
 #+end_definition

 El primer teorema de isomorfía nos dice que $N \cong \frac{M}{ker(\beta)} = \frac{M}{im(\alpha)}$ lo que nos 
 lleva a identificar   $N \cong \frac{M}{L}$. De hecho, cada monomorfismo da lugar a una 
 secuencia exacta corta:

 \[ 0 \longrightarrow \ker(\phi) \longrightarrow M \longrightarrow im(\phi) \longrightarrow 0 \]

**** 7.2. Secuencias exactas escindidas
 #+begin_definition
 *Secuencia escindida*. Una secuencia exacta corta:

 \[ 0 \longrightarrow M_1 \longrightarrow N \longrightarrow M_2 \longrightarrow 0 \]

 es escindida si es isomorfa a una secuencia de la forma siguiente:

 \[ \begin{tikzcd}
 0   \arrow{r}{} & 
 M_1 \arrow{d}{\sim}\arrow{r}{} & 
 N   \arrow{d}{\sim}\arrow{r}{} & 
 M_2 \arrow{d}{\sim}\arrow{r}{} & 
 0 \\
 0   \arrow{r}{} & 
 M_1 \arrow{r}{} & 
 M_1 \oplus M_2   \arrow{r}{} & 
 M_2 \arrow{r}{} & 
 0
 \end{tikzcd} \]

 Es decir, hay un isomorfismo entre secuencias.
 #+end_definition

 #+begin_theorem
 *Relación entre secuencias escindidas e inversas*. Sea $\phi$ un homomorfismo;
 entonces tiene inversa izquierda ssi la secuencia siguiente escinde:

 \[ 0 \longrightarrow M \overset{\phi}\longrightarrow N \longrightarrow coker(\phi) \longrightarrow 0 \]

 Y tiene inversa derecha si la secuencia siguiente escinde:

 \[ 0 \longrightarrow ker(\phi) \longrightarrow M \overset{\phi}\longrightarrow N \longrightarrow 0 \]
 #+end_theorem

**** 7.3. Homología, y el lema de la serpiente
 #+begin_definition
 *Homología*. La i-ésima homología de un complejo,

 \[ \dots \longrightarrow M_{i+1} \overset{d_{i+1}}\longrightarrow M_i \overset{d_i}\longrightarrow M_{i-1} \longrightarrow \dots \]

 es el R-módulo:

 \[H_i(M) = \frac{ker(d_i)}{im(d_{i+1})}\]
 #+end_definition

 La homología mide lo que se aleja de ser exacto en un punto determinado, y
 es $0$ cuando el complejo es exacto. Puede verse como una generalización de
 kernel y cokernel; que los realiza en este caso extremo:

 \[ 0 \longrightarrow M_1 \overset{\phi}\longrightarrow M_0 \longrightarrow 0 \]

 En el que $H_1(M) \cong ker(\phi)$ y $H_0(M) \cong coker(\phi)$.

 #+begin_theorem
 *Lema de la serpiente*. Teniendo dos secuencias exactas en el diagrama 
 conmutativo siguiente:

 \[ \begin{tikzcd}
 0 \rar & L_1 \rar{\alpha_1}\arrow{d}{\lambda} & M_1 \rar{\beta_1}\arrow{d}{\mu} & N_1 \rar\arrow{d}{\eta} & 0 \\
 0 \rar & L_0 \rar{\alpha_0}                   & M_0 \rar{\beta_0}               & N_0 \rar                & 0
 \end{tikzcd} \]

 Existe una secuencia exacta de la forma:

 \[ 0 \overset{}\longrightarrow 
 ker(\lambda) \overset{}\longrightarrow 
 ker(\mu) \overset{}\longrightarrow 
 ker(\eta) \overset{\delta}\longrightarrow 
 coker(\lambda) \overset{}\longrightarrow 
 coker(\mu) \overset{}\longrightarrow 
 coker(\eta) \overset{}\longrightarrow 
 0\]
 #+end_theorem

 El diagrama desde el que se deduce todo esto, con columnas exactas, es
 el siguiente:

 \[ \begin{tikzcd}
	& 0 \dar              & 0 \dar            & 0 \dar           &   \\
 0 \rar & ker(\lambda) \rar \dar  & ker(\mu) \rar \dar    & ker(\eta) \dar \ar[out=355, in=175,looseness=1, overlay, swap]{dddll}{\delta}       &   \\
 0 \rar & L_1 \rar{\alpha_1} \dar{\lambda}  & M_1 \rar{\beta_1} \dar{\mu} & N_1 \rar \dar{\eta}        & 0 \\
 0 \rar & L_0 \rar{\alpha_0} \dar & M_0 \rar{\beta_0} \dar & N_0 \rar \dar        & 0 \\
	& coker(\lambda) \rar \dar & coker(\mu) \rar \dar  & coker(\eta) \rar \dar & 0 \\
	& 0                   & 0                 & 0                &
 \end{tikzcd} \]

** IV. Álgebra lineal
*** 4. Presentaciones y resoluciones
**** 4.1. Torsión
 #+begin_definition
 *Torsión*. Un elemento $m \in M$ módulo de $R$ es de *torsión* si $\{m\}$ es linealmente
 dependiente. Es decir,

   \[ \exists r \in R,\ r \neq 0\ :\ rm = 0 \]

 El conjunto de elementos de torsión se llama $Tor(M)$. Un módulo es *libre de torsión*
 si $Tor(M) = 0$ y *de torsión* si $Tor(M)=M$.
 #+end_definition

 Un anillo conmutativo es libre de torsión sobre sí mismo si y sólo si es dominio de
 integridad. Cuando esto ocurre, $Tor(M)$ es siempre submódulo de $M$. Submódulos o
 sumas de módulos libres de tensión serán libres de torsión, y por todo esto, los módulos
 libres sobre dominios de integridad serán libres de torsión.

 #+begin_definition
 *Cíclico*. Un módulo es *cíclico* cuando es generado por un elemento. Es decir,
 cuando $M \cong R/I$ para algún ideal.
 #+end_definition

 Cuando en un dominio de integridad todos sus
 módulos cíclicos son libres de torsión, es un cuerpo. Otra forma de pensar sobre un módulo
 cíclico es como aquel que admite un epimorfismo:

 \[ R \longrightarrow M \longrightarrow 0 \]

**** 4.2. Módulos finitamente presentados y resoluciones libres
 #+begin_definition
 *Anulador.* El anulador de un módulo $M$ es:

 \[Ann_R(M) = \{ r \in R\ |\ \forall m \in M, rm = 0 \}\]
 #+end_definition

 Es un ideal de $R$. Cuando $M$ es finitamente generado y $R$ es dominio de integridad,
 $M$ es de torsión si y sólo si $Ann(M) \neq 0$.

 #+begin_definition
 *Módulos finitamente generados y presentados*. Sabemos que todos los módulos admiten un
 epimorfismo de la forma:

 \[ R^{\oplus A} \longrightarrow M \longrightarrow 0\]

 Cuando lo admiten con $A$ finito, se tiene $M$ *finitamente generado*. Un módulo se dice
 *finitamente presentado* si hay una secuencia exacta de la forma:

 \[R^n \overset{\phi}\longrightarrow R^m \longrightarrow M \longrightarrow 0\]

 .
 #+end_definition

 Si $R$ es Noetheriano, todo módulo finitamente generado es finitamente presentado.

 #+begin_definition
 *Resolución*. Una resolución de $M$ mediante módulos libres finitamente generados es
 un complejo exacto:

 \[ \dots \rightarrow R^{m_3} \rightarrow R^{m_2} \rightarrow R^{m_1} \rightarrow R^{m_0} \rightarrow M \rightarrow 0 \]
 #+end_definition

 Aquí podemos entender que $R^{m_0}$ contiene los generadores, $R^{m_1}$ las relaciones
 entre los generadores, $R^{m_2}$ las relaciones entre relaciones, y así sucesivamente.

 Un dominio de integridad es *cuerpo si y sólo si todos sus módulos son finitamente generados*,
 esto es equivalente a tener:

 \[ 0 \longrightarrow R^m \longrightarrow M \longrightarrow 0 \]

 para cualquier módulo.

 Un dominio de integridad es *PID si todas las resoluciones como finitamente generado 
 extienden a finitamente presentado*, de la forma:

 \[0 \longrightarrow R^{m_1} \longrightarrow R^{m_0} \overset{\pi}\longrightarrow M \longrightarrow 0\]

 esto equivale a pedir que $\ker(\pi)$ sea libre.

**** 4.3. Leyendo una presentación
 Hemos visto que podemos estudiar un módulo finitamente presentado por un
 morfismo $\phi: R^n \longrightarrow R^m$, donde $M = coker(\phi)$. Esto quiere decir que 
 podemos asignarle una matriz explícita.

 #+begin_theorem
 *Producto de módulos en matrices*. Sean $M,N$ módulos con matrices $A,B$.
 Tenemos $M \oplus N$ con matriz:

 \[\left(\begin{array}{c|c}
 A & 0 \\ \hline 0 & B 
 \end{array}\right)\]
 #+end_theorem

 Además nótese que las *matrices equivalentes* representan el mismo 
 homeomorfismo, y por tanto el mismo módulo.

 #+begin_theorem
 *Transformaciones de matrices de módulos*. Una matriz representa el mismo módulo
 tras las transformaciones de:
  - Permutar filas o columnas
  - Añadir filas o columnas linealmente dependientes
  - Multiplicar filas o columnas por una unidad
  - Quitar una fila y columna en la que sólo queda una unidad
 #+end_theorem

 Las primeras son consecuencia de la equivalencia. La última puede colocarse como
 una parte de identidad en una matriz de la forma:

 \[A = \left(\begin{array}{c|c}
 u & 0 \\ \hline 0 & A' 
 \end{array}\right)\]

 Que no afecta al cokernel.

** VII. Cuerpos
*** 1. Extensiones de cuerpos I
**** 1.1. Definiciones básicas
***** Categoría de los cuerpos
Los cuerpos forman la *categoría $\mathtt{Fld}$* con los homomorfismos de 
anillos entre ellos. Todo homomorfismo de anillos entre cuerpos
es inyectivo y todo morfismo en esta categoría es monomorfismo.

Así, todo morfismo entre cuerpos en $Hom(k,K)$ es una extensión $K/k$.

***** Característica de un cuerpo
      La *característica* de $K$ es el generador de $ker(i)$ para 
      $i : \mathbb{Z} \longrightarrow K$. Las extensiones preservan la 
      característica, así que podemos particionar la categoría en categorías 
      $\mathtt{Fld}_p$.

***** Cuerpos primos
      El inicial de $\mathtt{Fld}_0$ es $\mathbb{Q}$, y el de $\mathtt{Fld}_p$ es $\mathbb{F}_p = \mathbb{Z}/p\mathbb{Z}$. Todos los
      cuerpos son extensiones de uno de estos llamados *cuerpos primos*.

***** Grado de una extensión
El *grado*, $[F : K]$, de una extensión es su dimensión como espacio
vectorial sobre la base. Es *finita* o *infinita* si lo es su grado.

**** 1.2. Extensiones simples
***** Extensión simple
Una extensión es *simple* si es de la forma $K(\alpha)$ donde 
$K(\alpha)$ es la intersección de todos los subcuerpos de algún
$F$ conteniendo al cuerpo $K$ y el elemento $\alpha$.

***** Polinomio irreducible mínimo
Dada una extensión simple $K(\alpha)$, consideramos la evaluación
$\epsilon : K[X] \longrightarrow K(\alpha)$ por casos:

 - Es *inyectiva* ssi es una *extensión infinita*. En este
   caso $K(\alpha) \cong K(X)$ es el cuerpo de funciones racionales.
 - No es *inyectiva*. Existe un único polinomio mónico
   irreducible $p$ que genera el núcleo,

   \[ K(\alpha) \cong \frac{K[t]}{(p(t))}\]

   Se le llama *polinomio mínimo*.

***** TODO Extensión de isomorfismos a extensiones simples
Proposition 1.5
***** Automorfismos de una extensión
El *grupo de automorfismos* de una extensión $Aut_K(F)$, es el
grupo de los automorfismos de cuerpos que dejan fijo $K$.
***** Automorfismos y raíces
Sea $K(\alpha)$ con $p$ polinomio mínimo. Entonces $p$ tiene $|Aut_K(K(\alpha))|$ raíces
distintas en $K(\alpha)$. En particular,

\[ |Aut_K(K(\alpha))| \leq [K(\alpha):K] \]

y el caso de igualdad se tiene con $p$ factorizando en factores 
lineales sobre $F$.
**** 1.3. Extensiones finitas y algebraicas
***** Elementos algebraicos y trascendentes
Sea $F/K$ una extensión con $\alpha \in F$, entonces $\alpha$ es *algebraico*
cuando $K(\alpha)/K$ es finita, y *trascendente* si no. Una extensión
es *algebraica* si todos sus elementos lo son.

*** 6. Un poco de teoría de Galois
**** 6.1. Correspondencia de Galois y extensiones de Galois
***** Cuerpo fijo
Sea $F/k$ extensión y $G \subseteq Aut_k(F)$. Llamamos *cuerpo fijo* de $G$ a:

\[ F^G = \{ \alpha\in F \mid \forall g \in G, g\alpha=\alpha\}\]

***** Correspondencia de Galois
Hay correspondencia entre los cuerpos intermedios de la extensión
y los subgrupos del grupo de automorfismos.

Dado $E$ cuerpo intermedio, lo enviamos a $Aut_E(F)$. Dado $G$ lo enviamos
a $F^G$.

***** Inclusión y correspondencia
Para cualesquiera subgrupo $G$ y cuerpo intermedio $E$:

 - $E \subseteq F^{Aut_E(F)}$
 - $G \subseteq Aut_{F^G}(F)$

Si llamamos $E_1E_2$ al menor subcuerpo de $F$ conteniendo $E_1,E_2$ y llamamos
$<G_1,G_2>$ al menor subgrupo de los automorfismos conteniendo $G_1,G_2$:

 - $Aut_{E_1E_2}(F) = Aut_{E_1}(F) \cap Aut_{E_2}(F)$
 - $F^{<G_1,G_2>} = F^{G_1} \cap F^{G_2}$

***** Extensiones de Galois
Sea $F/k$ extensión, equivalen:

 - $F$ es cuerpo de descomposición de algún $f \in k[t]$.
 - $F/k$ es normal y separable.
 - $|Aut_k(F)| = [F : k]$.
 - La correspondencia de Galois es biyección.
 - $F/k$ separable y, si $E/F$ es algebraica con $\sigma \in Aut_k(E)$, $\sigma(F)=F$.

Llamamos a esto una *extensión de Galois*.
** VIII. Vuelta al álgebra lineal
*** 1. Preliminares
**** 1.1. Funtores
 #+begin_definition
 *Funtor*. Un funtor covariante:

 \[{\cal F} : C \longrightarrow D\]

 Asigna a cada $A \in C$ un ${\cal F}(A) \in D$ y mapea los morfismos entre cada par de objetos:

 \[Hom_C(A,B) \rightarrow Hom_D({\cal F}(A),{\cal F}(B))\]

 Respetando la identidad y la composición de morfismos. 

 Un *funtor contravariante* es un funtor desde la categoría opuesta:

 \[{\cal F} : C^{op} \longrightarrow D\]
 #+end_definition

 Los funtores preservan los diagramas conmutativos. Llamamos *prehaz* a un funtor
 contravariante $C \longrightarrow \mathtt{Set}$.

 #+begin_definition
 *Funtor aditivo*. Llamamos a un funtor 
 ${\cal F}: R-\mathtt{Mod} \longrightarrow S-\mathtt{Mod}$ *aditivo* cuando
 la función $Hom_{R}(A,B) \rightarrow Hom_{S}({\cal F}(A),{\cal F}(B))$ es homomorfismo de grupos.
 #+end_definition

**** 1.3. Equivalencia de categorías
 #+begin_definition
 *Funtores plenamente fieles*. Dada la función inducida:
 \[Hom_C(A,B) \rightarrow Hom_D({\cal F}(A),{\cal F}(B))\]
 Un funtor es *fiel* si es inyectiva, *pleno* si es sobreyectiva y *plenamente fiel*
 si es biyectiva.
 #+end_definition

 #+begin_definition
 *Equivalencia de categorías*. Un funtor es una equivalencia de categorías si 
 es plenamente fiel y esencialmente sobreyectivo, es decir, para cada $Y \in D$,
 existe un $X \in C$ tal que $F(X) \cong Y$.
 #+end_definition

**** 1.4. Límites y colímites

 #+begin_definition
 *Límite*. Para un funtor ${\cal F}: {\cal I} \longrightarrow C$, su límite es
 un objeto $L \in C$ con morfismos $\lambda_I: L \longrightarrow {\cal F}(I)$ tales que

 - Conmuta el siguiente diagrama para cualquier $\alpha : I \longrightarrow J$:

 \[ \begin{tikzcd}[column sep=1.5em]
  & L \arrow{dr}{\lambda_J} \arrow{dl}[swap]{\lambda_I} \\
 {\cal F}(I) \arrow{rr}{{\cal F}(\alpha)} && {\cal F}(J)
 \end{tikzcd} \]

 - $L$ es final en este diagrama.
 #+end_definition

 Será esencialmente único y puede notarse por $\varprojlim {\cal F}$.

 #+begin_theorem
 *Límites sobre cadenas en R-Mod*. En R-Mod siempre existe un límite llamado \(\varprojlim {\cal A}_i\) sobre una
 cadena de la forma:

 \[ \begin{tikzcd}
 & & A 
 \arrow{lld}[swap]{\phi_5}
 \arrow{ld}{\phi_4}
 \arrow{d}{\phi_3}
 \arrow{rd}[swap]{\phi_2}
 \arrow{rrd}{\phi_1} 
 & & \\
 \dots \arrow{r}[swap]{\phi_{45}}  &
 A_4 \arrow{r}[swap]{\phi_{34}} &
 A_3 \arrow{r}[swap]{\phi_{23}} &
 A_2 \arrow{r}[swap]{\phi_{12}} &
 A_1
 \end{tikzcd} \]
 #+end_theorem

 Este límite es el submódulo de las /secuencias coherentes/ en $\prod_i A_i$, es decir, de
 aquellas tales que $a_i = \phi_{i,i+1}(a_{i+1})$; teniendo como morfismos $\phi_i$ las proyecciones
 canónicas


 #+begin_definition
 *Colímite*. La noción dual de límite es el *colímite*, es decir, para
 un funtor ${\cal F} : I \longrightarrow C$, su colímite es un objeto $L \in C$ con morfismos $\gamma_i : {\cal F}(I) \longrightarrow L$
 tales que

 - Conmuta el siguiente diagrama para cualquier $\alpha : I \longrightarrow J$:

 \[ \begin{tikzcd}[column sep=1.5em]
  & L  \\
 {\cal F}(I) \arrow{ur}{\gamma_I} \arrow{rr}{{\cal F}(\alpha)} && {\cal F}(J) \arrow{ul}[swap]{\gamma_J}
 \end{tikzcd} \]

 - $L$ es inicial en este diagrama.
 #+end_definition

**** 1.5. Comparando funtores
 #+begin_definition
 *Transformación natural*. Una transformación natural entre dos funtores ${\cal F} \Longrightarrow {\cal G}$ 
 consiste en morfismos $\upsilon_X : {\cal F}(X) \longrightarrow {\cal G}(X)$ tales que conmuta el diagrama:

 \[ \begin{tikzcd}
 {\cal F}(X) \arrow{r}{{\cal F}(\alpha)} \arrow{d}{\upsilon_X} & {\cal F}(Y) \arrow{d}{\upsilon_Y} \\
 {\cal G}(X) \arrow{r}{{\cal G}(\alpha)} & {\cal G}(Y)
 \end{tikzcd}
 \]

 para cualquier morfismo $\alpha$.

 Llamamos *isomorfismo natural* a una transformación natural donde cada $\upsilon$
 es un isomorfismo.
 #+end_definition

 #+begin_definition
 *Funtor adjunto*. Llamamos ${F}$ y ${G}$ adjuntos si tenemos:

 \[ Hom_C(X,GY) \cong Hom_D(FX,Y) \]

 Isomorfismos naturales.
 #+end_definition

 Lo que nos da realmente un isormorfismo natural de $Hom_C(F-,-)$ con $Hom_D(-,G-)$,
 entendidos como funtores. Llamamos aquí adjunto izquierdo a $F$ y adjunto derecho a $G$.
 Tenemos más sobre funtores adjuntos en la lista de reproducción de [[https://www.youtube.com/playlist?list=PL54B49729E5102248][The Catsters]].

 #+begin_theorem
 *Continuidad de adjuntos*. Los funtores adjuntos derechos son continuos, los adjuntos
 izquierdos son cocontinuos. Es decir, para $I : {\cal I}\longrightarrow D$, $J : {\cal J}\longrightarrow C$

 \[G(\varprojlim I) = \varprojlim (G \circ I)\]
 \[F(\varinjlim J) = \varinjlim (F \circ J)\]
 #+end_theorem

 Siempre que existan los límites. La demostración de esto se puede hacer aplicando los
 funtores en los diagramas conmutativos y usando las propiedades universales de los límites.

 #+begin_definition
 *Funtor exacto*. Un funtor exacto respeta la exactitud de las secuencias. Es decir,
 siendo la siguiente secuencia exacta:

 \[ 0 \longrightarrow A \overset{\phi}\longrightarrow B \overset{\psi}\longrightarrow C \longrightarrow 0\]

 La siguiente secuencia será exacta:

 \[ 0 \longrightarrow FA \overset{F\phi}\longrightarrow FB \overset{F\psi}\longrightarrow FC \longrightarrow 0\]
 #+end_definition

 En particular, lo llamamos /exacto a la izquierda/ si preserva la exactitud de:

 \[ 0 \longrightarrow A \overset{\phi}\longrightarrow B \overset{\psi}\longrightarrow C\]

 Y /exacto a la derecha/ si preserva la exactitud de:

 \[ A \overset{\phi}\longrightarrow B \overset{\psi}\longrightarrow C \longrightarrow 0\]

*** 2. Producto tensor y el funtor Tor
**** 2.1. Aplicaciones bilineales
 #+begin_definition
 *Aplicación bilineal*. Una aplicación $\phi:M\times N \longrightarrow P$ es bilineal si
 son lineales $\phi(\_,n)$ y $\phi(m,\_)$ para cualesquiera $m,n$.
 #+end_definition

 #+begin_definition
 *Producto tensor*. $M \otimes_R N$ es el producto tensor de $M$ y $N$ como módulos de $R$
 si cualquier aplicación bilineal factoriza de forma única a través de él:

 \[ \begin{tikzcd}
 M \times N \arrow{r}{\phi} \arrow{d}{\otimes} & P \\
 M \otimes N \arrow{ru}[swap]{\exists! \overline\phi} &
 \end{tikzcd} \]
 #+end_definition

 Usando universalidad podemos ver que $R \otimes N \cong N$ y que $M\otimes N \cong N\otimes M$. La construcción
 explícita del producto tensor se hace sobre el módulo libre sobre $M \times N$ provocando un
 cociente sobre los submódulos generados por:

 \[(m,r_1n_1+r_2n_2) - r_1(m,n_1) - r_2(m,n_2)\]
 \[(r_1m_1+r_2m_2,n) - r_1(m_1,n) - r_2(m_2,n)\]

 Lo que nos permite actuar con ellos de forma bilineal. La demostración se basa en usar
 la propiedad universal de la proyección sobre ese cociente.

**** 2.2. Adjunción con Hom
 Dado un módulo $N$ de $R$, tenemos un funtor covariante $\otimes_R N$, que será *adjunto izquierdo*
 a $Hom_{R-mod}(N,-)$. Podemos observar simplemente que una aplicación bilineal, al currificarse,
 determina una función que va de $M$ a $Hom(N,P)$, y que es lineal. Sabiendo esto, es trivial
 que:

 \[ Hom_R(M, Hom_R(N,P)) \cong Hom_R(M \otimes N, P)\]

 La naturalidad y el hecho de que es un isomorfismo se comprueban fácilmente. El hecho de
 que exista una adjunción nos dice además que $\otimes_R N$, o $N\otimes_R$ por la isomorfía anterior,
 son cocontinuos.

 #+begin_fact
 Para cualesquiera \(R\)-módulos, se tiene:

 \[(M_1 \oplus M_2) \otimes N \cong (M_1 \otimes N) \oplus (M_2 \otimes N)\]

 \[N \otimes (M_1 \oplus M_2) \cong (N \otimes M_1) \oplus (N \otimes M_2)\]

 \[(\oplus_\alpha M_\alpha) \otimes N \cong \oplus_\alpha (M_\alpha \otimes N)\]
 #+end_fact

 Por cocontinuidad.

 #+begin_fact
 Para cualesquiera dos conjuntos $A,B$, se tiene:

 \[R^{\oplus A} \otimes R^{\oplus B} \cong R^{\oplus A \times B}\]
 #+end_fact

 Teniendo \(R^{\oplus n} \otimes R^{\oplus m} \cong R^{\oplus nm}\). De hecho, la base del espacio producto
 tensor la forman los vectores puros que emparejan elementos de las 
 bases de cada uno de los espacios.

 #+begin_theorem
 *Producto tensor de cocientes*. Dado un $N$ módulo de $R$, e $I$ ideal,
 tenemos:

 \[\frac{R}{I}\otimes N \cong \frac{N}{IN}\]

 Y desde ahí, aplicando además el tercer teorema de isomorfía, tenemos:

 \[\frac{R}{I} \otimes \frac{R}{J} \cong \frac{R}{I+J}\]
 #+end_theorem

 Esto se deduce de aplicar el funtor $\_ \otimes N$ a la secuencia exacta del 
 ideal:

 \[I \longrightarrow R \longrightarrow \frac{R}{I} \longrightarrow 0\]
 
 \[I \otimes N \longrightarrow N \longrightarrow \frac{R}{I} \otimes N \longrightarrow 0\]

 Desde donde se obtiene $IN$ como inclusión de $I\otimes N$ en $N$.

**** 2.3. Exactitud y planitud
 #+begin_definition
 *Módulo plano*. El módulo $N$ es *plano* si el funtor $\_ \otimes N$ es un
 funtor exacto.
 #+end_definition

 Un *módulo libre* será siempre plano.

**** 2.4. Los funtores Tor
 #+begin_definition
 *El funtor Tor*. Lo que se aleja de la exactitud el funtor $\_ \otimes N$
 es medido por el funtor $Tor_1(\_,N)$. De hecho, si tenemos una secuencia
 exacta:

 \[0\longrightarrow A \longrightarrow B \longrightarrow C \longrightarrow 0\]

 Obtenemos aplicando el funtor $\otimes N$ esta otra secuencia:

 \[Tor_1(C,N) \longrightarrow A \otimes N \longrightarrow B \otimes N \longrightarrow C \otimes N \longrightarrow 0\]

 Y de hecho, esta secuencia podrá extenderse aún más con /funtores derivados/,
 que se definen como:

 \[Tor_i^R(M,N) = H_i(M_{\bullet} \otimes N)\]
 #+end_definition

 Aquí entendemos $M_\bullet \otimes N$ como el complejo que se obtiene tomando una resolución
 libre de $M$:

 \[\dots \longrightarrow R^{\otimes S_2} \longrightarrow R^{\otimes S_1} 
 \longrightarrow R^{\otimes S_0} \longrightarrow M \longrightarrow 0}\]

 Y retirando $M$ y tensando sobre $N$, para tener:

 \[\dots \longrightarrow N^{\otimes S_2} \longrightarrow N^{\otimes S_1} 
 \longrightarrow N^{\otimes S_0} \longrightarrow 0}\]

 Todo esto se obtendrá de manera natural aplicando el lema de la serpiente a una secuencia
 de resoluciones compatibles, algo que, si los módulos fueran PID y tuvieran una resolución
 de grado 2, sería de la forma:

 \[ \begin{tikzcd}
    & 0 \dar & 0 \dar & 0 \dar &   \\
 0 \rar & R^{\oplus a_1}\rar\dar & R^{\oplus b_1} \rar\dar & R^{\oplus c_1} \rar\dar & 0 \\
 0 \rar & R^{\oplus a_0}\rar\dar & R^{\oplus b_0} \rar\dar & R^{\oplus c_0} \rar\dar & 0 \\
 0 \rar & A\rar\dar & B \rar\dar & C \rar\dar & 0 \\
  & 0 & 0 & 0 & 
 \end{tikzcd} \]

 Tensando las dos filas superiores, que son libres, nos quedarían dos filas sobre las que aplicar
 el lema de la serpiente y obtener los funtores derivados tal y como los hemos definido.

*** 5. Funtor Hom y dualidad 
**** 5.1. Adjunciones, de nuevo
 Ya sabemos que el funtor $Hom(N,\_)$ es adjunto derecho a $\_\otimes N$, ahora
 estudiamos el funtor $Hom(\_,N)$.

 #+begin_theorem
 *Adjunción de Hom contravariante*. El funtor $Hom(\_,N)$ es adjunto derecho
 de su funtor opuesto, $Hom^{op}(\_,N)$.
 #+end_theorem

 Aplicando currificación tenemos trivialmente:

 \[Hom(L,Hom(M,N)) \cong Hom(M,Hom(L,N))\]

 Que, teniendo en cuenta que estamos usando la categoría opuesta, prueba la
 adjunción.

 #+begin_proposition
 *Exactitud de Hom*. Ambos funtores $Hom$ son adjuntos derechos y por tanto,
 exactos por la izquierda. Teniendo en cuenta que uno es contravariante, quiere
 decir que:

 \[ A \overset{}\longrightarrow B \overset{}\longrightarrow C \overset{}\longrightarrow 0\]

 Lleva a:

 \[ 0 \overset{}\longrightarrow Hom(C,N) \overset{}\longrightarrow 
 Hom(B,N) \overset{}\longrightarrow Hom(A,N)\]
 #+end_proposition

**** 5.2. Módulos duales.
 #+begin_definition
 *Módulo dual*. El dual de un R-módulo $M$ es el módulo $M^{\vee} = Hom_R(M,R)$.
 #+end_definition

 Tenemos que $Hom(M,R^n) \cong M^{\vee} \otimes R^n$.

*** 6. Módulos proyectivos e inyectivos, y el funtor Ext
**** 6.1. Proyectividad e inyectividad
 #+begin_definition
 *Módulos proyectivos e inyectivos*. Un R-módulo es /proyectivo/ si $Hom(P,\_)$
 es exacto; e /inyectivo/ si $Hom(\_,P)$ es exacto.
 #+end_definition

 Esto es equivalente a decir que cada epimorfismo $M \longrightarrow N$ lleva un
 morfismo $P \longrightarrow N$ a $P \longrightarrow M$, en el caso de /proyectividad/:

 \[ \begin{tikzcd}
  & P \dlar[swap,dashed]{\exists p'} \dar[swap]{p} \drar{0} & \\
 M \rar & N \rar & 0
 \end{tikzcd} \]

 O que cada monomorfismo $L \longrightarrow M$ lleva un morfismo $L \longrightarrow Q$ a
 un monomorfismo $M \longrightarrow Q$, en el de la /inyectividad/:

 \[ \begin{tikzcd}
  & Q & \\
 0 \urar{0} \rar & N \rar \uar[swap]{q} & M \ular[dashed,swap]{\exists q'}
 \end{tikzcd} \]

 Además, esto es equivalente a decir que un módulo $P$ es /proyectivo/ si toda secuencia

 \[ 0 \overset{}\longrightarrow L \overset{}\longrightarrow M \overset{}\longrightarrow P \overset{}\longrightarrow 0 \]

 es escindida, y $Q$ es /inyectivo/ si toda secuencia:

 \[ 0 \overset{}\longrightarrow Q \overset{}\longrightarrow M \overset{}\longrightarrow N \overset{}\longrightarrow 0 \]

 es escindida.

**** 6.2. Módulos proyectivos
 #+begin_theorem
 *Caracterización de proyectividad*. Un módulo es proyectivo ssi es el sumando
 directo de un módulo libre.
 #+end_theorem

 Así, la suma directa de dos módulos proyectivos es proyectiva; el producto tensor
 de dos módulos proyectivos es proyectivo, y todo módulo proyectivo es plano.

**** 6.3. Módulos inyectivos
 #+begin_theorem
 *Caracterización de inyectividad*. Un módulo es *inyectivo* ssi toda aplicación
 $f : I \longrightarrow Q$ extiende a una aplicación $\hat f : R \longrightarrow Q$, donde I es ideal de R.
 #+end_theorem

**** 6.4. El funtor Ext
 Existirían dos formas naturales de definir *Ext*, que coinciden no trivialmente:

 #+begin_definition
 *Funtor Ext*. Dado $M$ con una resolución proyectiva:

 \[ \dots \overset{}\longrightarrow P_1 \overset{}\longrightarrow P_0 \overset{}\longrightarrow M \overset{}\longrightarrow 0 \]

 aplicamos el funtor contravariante $Hom(\_,N)$ eliminando $M$ para obtener:

 \[ 0 \overset{}\longrightarrow Hom(P_0,N) \overset{}\longrightarrow Hom(P_1,N) \overset{}\longrightarrow Hom(P_2,N) \overset{}\longrightarrow \dots \]

 Y tomamos la cohomología de este complejo $Hom(M_\bullet,N)$, dejando como definición:

 \[Ext^i_R(M,N) = H^i(Hom(M_\bullet,N))\]
 #+end_definition

 #+begin_definition
 *Funtor Ext*. Dado $N$ con una resolución inyectiva:

 \[ 0 \overset{}\longrightarrow N \overset{}\longrightarrow Q_0 \overset{}\longrightarrow Q_1 \overset{}\longrightarrow \dots \]

 aplicamos el funtor covariante $Hom(M,\_)$ eliminando $N$ para obtener:

 \[ 0 \overset{}\longrightarrow 
 Hom(M,Q_0) \overset{}\longrightarrow 
 Hom(M,Q_1) \overset{}\longrightarrow 
 Hom(M,Q_2) \overset{}\longrightarrow \dots \]

 Y tomamos la cohomología de este complejo $Hom(M,N_\bullet)$, dejando como definición:

 \[Ext^i_R(M,N) = H^i(Hom(M,N_\bullet))\]
 #+end_definition

** IX. Álgebra homológica
*** Complejos y homología, de nuevo
**** 3.1. Recordatorio de definiciones básicas
 #+begin_definition
 *Resolución*. La /resolución/ de un objeto $A$ es un complejo
 exacto excepto en un punto, donde es isomorfa a $A$.
 #+end_definition

 Esto es equivalente a tener un complejo exacto de la forma:

 \[ \dots \overset{}\longrightarrow 
 M_2 \overset{}\longrightarrow 
 M_1 \overset{}\longrightarrow 
 M_0 \overset{}\longrightarrow 
 A \longrightarrow
 0\]

**** 3.2. La categoría de los complejos
 #+begin_definition
 *Categoría de complejos de cocadenas*. La categoría $C(A)$ tiene como objetos
 los complejos de cocadenas en una categoría $A$; y como morfismos entre dos 
 cocadenas,   $Hom(M^\bullet,N^\bullet)$, los diagramas conmutativos entre ellas. Por ejemplo:

 \[ \begin{tikzcd}
 \dots \rar & M^{i-1} \rar\dar{\alpha^{i-1}} & M^{i} \rar\dar{\alpha^{i}} &  M^{i+1} \rar\dar{\alpha^{i+1}} & \dots \\
 \dots \rar & N^{i-1} \rar & N^{i} \rar & N^{i+1} \rar & \dots
 \end{tikzcd} \]

 representa el morfismo $\alpha_\bullet$.
 #+end_definition

 Esta es una categoría abeliana. De ella definiremos además dos variantes:

 - $C^+(A)$, subcategoría plena de los complejos acotados por debajo.
 - $C^-(A)$, subcategoría plena de los complejos acotados por arriba.
