#+TITLE: Algebra: Chapter 0
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS: num:nil toc:nil
#+LANGUAGE: es

#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}

* IV. Álgebra lineal
** 4. Presentaciones y resoluciones
*** 4.1. Torsión
#+begin_definition
*Torsión*. Un elemento $m \in M$ módulo de $R$ es de *torsión* si $\{m\}$ es linealmente
dependiente. Es decir,

  \[ \exists r \in R,\ r \neq 0\ :\ rm = 0 \]

El conjunto de elementos de torsión se llama $Tor(M)$. Un módulo es *libre de torsión*
si $Tor(M) = 0$ y *de torsión* si $Tor(M)=M$.
#+end_definition

Un anillo conmutativo es libre de torsión sobre sí mismo si y sólo si es dominio de
integridad. Cuando esto ocurre, $Tor(M)$ es siempre submódulo de $M$. Submódulos o
sumas de módulos libres de tensión serán libres de torsión, y por todo esto, los módulos
libres sobre dominios de integridad serán libres de torsión.

#+begin_definition
*Cíclico*. Un módulo es *cíclico* cuando es generado por un elemento. Es decir,
cuando $M \cong R/I$ para algún ideal.
#+end_definition

La equivalencia se ve en este [[file:aluffi.org::*Un%20cociente%20por%20ideal%20es%20c%C3%ADclico.][ejercicio]]. Cuando en un dominio de integridad todos sus
módulos cíclicos son libres de torsión, es un cuerpo. Otra forma de pensar sobre un módulo
cíclico es como aquel que admite un epimorfismo:

\[ R \longrightarrow M \longrightarrow 0 \]

*** 4.2. Módulos finitamente presentados y resoluciones libres
#+begin_definition
*Anulador.* El anulador de un módulo $M$ es:

\[Ann_R(M) = \{ r \in R\ |\ \forall m \in M, rm = 0 \}\]
#+end_definition

Es un ideal de $R$. Cuando $M$ es finitamente generado y $R$ es dominio de integridad,
$M$ es de torsión si y sólo si $Ann(M) \neq 0$. Puede verse en este [[file:aluffi.org::*M%20de%20torsi%C3%B3n%20si%20y%20s%C3%B3lo%20si%20el%20anulador%20es%20no%20nulo.][ejercicio]].

#+begin_definition
*Módulos finitamente generados y presentados*. Sabemos que todos los módulos admiten un
epimorfismo de la forma:

\[ R^{\oplus A} \longrightarrow M \longrightarrow 0\]

Cuando lo admiten con $A$ finito, se tiene $M$ *finitamente generado*. Un módulo se dice
*finitamente presentado* si hay una secuencia exacta de la forma:

\[R^n \overset{\phi}\longrightarrow R^m \longrightarrow M \longrightarrow 0\]
#+end_definition

Si $R$ es Noetheriano, todo módulo finitamente generado es finitamente presentado.

#+begin_definition
*Resolución*. Una resolución de $M$ mediante módulos libres finitamente generados es
un complejo exacto:

\[ \dots \rightarrow R^{m_3} \rightarrow R^{m_2} \rightarrow R^{m_1} \rightarrow R^{m_0} \rightarrow M \rightarrow 0 \]
#+end_definition

Aquí podemos entender que $R^{m_0}$ contiene los generadores, $R^{m_1}$ las relaciones
entre los generadores, $R^{m_2}$ las relaciones entre relaciones, y así sucesivamente.

Un dominio de integridad es *cuerpo si y sólo si todos sus módulos son finitamente generados*,
esto es equivalente a tener:

\[ 0 \longrightarrow R^m \longrightarrow M \longrightarrow 0 \]

para cualquier módulo.

Un dominio de integridad es *PID si todas las resoluciones como finitamente generado 
extienden a finitamente presentado*, de la forma:

\[0 \longrightarrow R^{m_1} \longrightarrow R^{m_0} \overset{\pi}\longrightarrow M \longrightarrow 0\]

esto equivale a pedir que $\ker(\pi)$ sea libre.


*** 4.3. Leyendo una presentación
Hemos visto que podemos estudiar un módulo finitamente presentado por un
morfismo $\phi: R^n \longrightarrow R^m$, donde $M = coker(\phi)$. Esto quiere decir que 
podemos asignarle una matriz explícita.

#+begin_theorem
*Producto de módulos en matrices*. Sean $M,N$ módulos con matrices $A,B$.
Tenemos $M \oplus N$ con matriz:

\[\left(\begin{array}{c|c}
A & 0 \\ \hline 0 & B 
\end{array}\right)\]
#+end_theorem

Además nótese que las *matrices equivalentes* representan el mismo 
homeomorfismo, y por tanto el mismo módulo.

#+begin_theorem
*Transformaciones de matrices de módulos*. Una matriz representa el mismo módulo
tras las transformaciones de:
 - Permutar filas o columnas
 - Añadir filas o columnas linealmente dependientes
 - Multiplicar filas o columnas por una unidad
 - Quitar una fila y columna en la que sólo queda una unidad
#+end_theorem

Las primeras son consecuencia de la equivalencia. La última puede colocarse como
una parte de identidad en una matriz de la forma:

\[A = \left(\begin{array}{c|c}
u & 0 \\ \hline 0 & A' 
\end{array}\right)\]

Que no afecta al cokernel.

* VIII. Vuelta al álgebra lineal
** 1. Preliminares
*** 1.1. Funtores
#+begin_definition
*Funtor*. Un funtor covariante:

\[{\cal F} : C \longrightarrow D\]

Asigna a cada $A \in C$ un ${\cal F}(A) \in D$ y mapea los morfismos entre cada par de objetos:

\[Hom_C(A,B) \rightarrow Hom_D({\cal F}(A),{\cal F}(B))\]

Respetando la identidad y la composición de morfismos. 

Un *funtor contravariante* es un funtor desde la categoría opuesta:

\[{\cal F} : C^{op} \longrightarrow D\]
#+end_definition

Los funtores preservan los diagramas conmutativos. Llamamos *prehaz* a un funtor
contravariante $C \longrightarrow \mathtt{Set}$.

#+begin_definition
*Funtor aditivo*. Llamamos a un funtor 
${\cal F}: R-\mathtt{Mod} \longrightarrow S-\mathtt{Mod}$ *aditivo* cuando
la función $Hom_{R}(A,B) \rightarrow Hom_{S}({\cal F}(A),{\cal F}(B))$ es homomorfismo de grupos.
#+end_definition

*** 1.3. Equivalencia de categorías
#+begin_definition
*Funtores plenamente fieles*. Dada la función inducida:
\[Hom_C(A,B) \rightarrow Hom_D({\cal F}(A),{\cal F}(B))\]
Un funtor es *fiel* si es inyectiva, *pleno* si es sobreyectiva y *plenamente fiel*
si es biyectiva.
#+end_definition

#+begin_definition
*Equivalencia de categorías*. Un funtor es una equivalencia de categorías si 
es plenamente fiel y esencialmente sobreyectivo, es decir, para cada $Y \in D$,
existe un $X \in C$ tal que $F(X) \cong Y$.
#+end_definition

*** 1.4. Límites y colímites

#+begin_definition
*Límite*. Para un funtor ${\cal F}: {\cal I} \longrightarrow C$, su límite es
un objeto $L \in C$ con morfismos $\lambda_I: L \longrightarrow {\cal F}(I)$ tales que

- Conmuta el siguiente diagrama para cualquier $\alpha : I \longrightarrow J$:

\[ \begin{tikzcd}[column sep=1.5em]
 & L \arrow{dr}{\lambda_J} \arrow{dl}[swap]{\lambda_I} \\
{\cal F}(I) \arrow{rr}{{\cal F}(\alpha)} && {\cal F}(J)
\end{tikzcd} \]

- $L$ es final en este diagrama.
#+end_definition

Será esencialmente único y puede notarse por $\varprojlim {\cal F}$.

#+begin_theorem
*Límites sobre cadenas en R-Mod*. En R-Mod siempre existe un límite llamado \(\varprojlim {\cal A}_i\) sobre una
cadena de la forma:

\[ \begin{tikzcd}
& & A 
\arrow{lld}[swap]{\phi_5}
\arrow{ld}{\phi_4}
\arrow{d}{\phi_3}
\arrow{rd}[swap]{\phi_2}
\arrow{rrd}{\phi_1} 
& & \\
\dots \arrow{r}[swap]{\phi_{45}}  &
A_4 \arrow{r}[swap]{\phi_{34}} &
A_3 \arrow{r}[swap]{\phi_{23}} &
A_2 \arrow{r}[swap]{\phi_{12}} &
A_1
\end{tikzcd} \]
#+end_theorem

Este límite es el submódulo de las /secuencias coherentes/ en $\prod_i A_i$, es decir, de
aquellas tales que $a_i = \phi_{i,i+1}(a_{i+1})$; teniendo como morfismos $\phi_i$ las proyecciones
canónicas


#+begin_definition
*Colímite*. La noción dual de límite es el *colímite*, es decir, para
un funtor ${\cal F} : I \longrightarrow C$, su colímite es un objeto $L \in C$ con morfismos $\gamma_i : {\cal F}(I) \longrightarrow L$
tales que

- Conmuta el siguiente diagrama para cualquier $\alpha : I \longrightarrow J$:

\[ \begin{tikzcd}[column sep=1.5em]
 & L  \\
{\cal F}(I) \arrow{ur}{\gamma_I} \arrow{rr}{{\cal F}(\alpha)} && {\cal F}(J) \arrow{ul}[swap]{\gamma_J}
\end{tikzcd} \]

- $L$ es inicial en este diagrama.
#+end_definition

*** 1.5. Comparando funtores
#+begin_definition
*Transformación natural*. Una transformación natural entre dos funtores ${\cal F} \Longrightarrow {\cal G}$ 
consiste en morfismos $\upsilon_X : {\cal F}(X) \longrightarrow {\cal G}(X)$ tales que conmuta el diagrama:

\[ \begin{tikzcd}
{\cal F}(X) \arrow{r}{{\cal F}(\alpha)} \arrow{d}{\upsilon_X} & {\cal F}(Y) \arrow{d}{\upsilon_Y} \\
{\cal G}(X) \arrow{r}{{\cal G}(\alpha)} & {\cal G}(Y)
\end{tikzcd}
\]

para cualquier morfismo $\alpha$.

Llamamos *isomorfismo natural* a una transformación natural donde cada $\upsilon$
es un isomorfismo.
#+end_definition

#+begin_definition
*Funtor adjunto*. Llamamos ${F}$ y ${G}$ adjuntos si tenemos:

\[ Hom_C(X,GY) \cong Hom_D(FX,Y) \]

Isomorfismos naturales.
#+end_definition

Lo que nos da realmente un isormorfismo natural de $Hom_C(F-,-)$ con $Hom_D(-,G-)$,
entendidos como funtores. Llamamos aquí adjunto izquierdo a $F$ y adjunto derecho a $G$.
Tenemos más sobre funtores adjuntos en la lista de reproducción de [[https://www.youtube.com/playlist?list=PL54B49729E5102248][The Catsters]].

#+begin_theorem
*Continuidad de adjuntos*. Los funtores adjuntos derechos son continuos, los adjuntos
izquierdos son cocontinuos. Es decir, para $I : {\cal I}\longrightarrow D$, $J : {\cal J}\longrightarrow C$

\[G(\varprojlim I) = \varprojlim (G \circ I)\]
\[F(\varinjlim J) = \varinjlim (F \circ J)\]
#+end_theorem

Siempre que existan los límites. La demostración de esto se puede hacer aplicando los
funtores en los diagramas conmutativos y usando las propiedades universales de los límites.

#+begin_definition
*Funtor exacto*. Un funtor exacto respeta la exactitud de las secuencias. Es decir,
siendo la siguiente secuencia exacta:

\[ 0 \longrightarrow A \overset{\phi}\longrightarrow B \overset{\psi}\longrightarrow C \longrightarrow 0\]

La siguiente secuencia será exacta:

\[ 0 \longrightarrow FA \overset{F\phi}\longrightarrow FB \overset{F\psi}\longrightarrow FC \longrightarrow 0\]
#+end_definition

En particular, lo llamamos /exacto a la izquierda/ si preserva la exactitud de:

\[ 0 \longrightarrow A \overset{\phi}\longrightarrow B \overset{\psi}\longrightarrow C\]

Y /exacto a la derecha/ si preserva la exactitud de:

\[ A \overset{\phi}\longrightarrow B \overset{\psi}\longrightarrow C \longrightarrow 0\]


** 2. Producto tensor y el funtor Tor
*** 2.1. Aplicaciones bilineales
#+begin_definition
*Aplicación bilineal*. Una aplicación $\phi:M\times N \longrightarrow P$ es bilineal si
son lineales $\phi(\_,n)$ y $\phi(m,\_)$ para cualesquiera $m,n$.
#+end_definition

#+begin_definition
*Producto tensor*. $M \otimes_R N$ es el producto tensor de $M$ y $N$ como módulos de $R$
si cualquier aplicación bilineal factoriza de forma única a través de él:

\[ \begin{tikzcd}
M \times N \arrow{r}{\phi} \arrow{d}{\otimes} & P \\
M \otimes N \arrow{ru}[swap]{\exists! \overline\phi} &
\end{tikzcd} \]
#+end_definition

Usando universalidad podemos ver que $R \otimes N \cong N$ y que $M\otimes N \cong N\otimes M$. La construcción
explícita del producto tensor se hace sobre el módulo libre sobre $M \times N$ provocando un
cociente sobre los submódulos generados por:

\[(m,r_1n_1+r_2n_2) - r_1(m,n_1) - r_2(m,n_2)\]
\[(r_1m_1+r_2m_2,n) - r_1(m_1,n) - r_2(m_2,n)\]

Lo que nos permite actuar con ellos de forma bilineal. La demostración se basa en usar
la propiedad universal de la proyección sobre ese cociente.

* Extra
** Adjuntos. The Catsters.
Serie de [[https://www.youtube.com/playlist?list=PL54B49729E5102248][vídeos]] sobre funtores adjuntos.

*** Adjuntions 1
Tenemos varias nociones de igualdad entre categorías.

#+begin_definition
*Isomorfismo de categorías*. Ocurre con dos functores:

\[ \begin{tikzcd}
{\cal C} \arrow[bend left]{r}{F} & {\cal D} \arrow[bend left]{l}{G}
\end{tikzcd}
\]

Tales que $1_C = GF$ y $FG = 1_D$.
#+end_definition

#+begin_definition
*Equivalencia de categorías*. Ocurre con dos functores:

\[ \begin{tikzcd}
{\cal C} \arrow[bend left]{r}{F} & {\cal D} \arrow[bend left]{l}{G}
\end{tikzcd}
\]

Tales que $1_C \cong GF$ y $FG \cong 1_D$. Entendiendo la isomorfía en la 
categoría de funtores, es decir, una [[https://ncatlab.org/nlab/show/natural+isomorphism][isomorfía natural]].
#+end_definition

#+begin_definition
*Adjunción*. Ocurre con dos functores:

\[ \begin{tikzcd}
{\cal C} \arrow[bend left]{r}{F} & {\cal D} \arrow[bend left]{l}{G}
\end{tikzcd}
\]

Tales que tenemos transformaciones naturales $1_C \overset{\eta}\Longrightarrow GF$ y 
$FG \overset{\epsilon}\Longrightarrow 1_D$ que cumplen las dos identidades triangulares siguientes:
 
\[ \begin{tikzcd}
F \arrow{r}{\eta} \arrow{dr}{id} & FGF \arrow{d}{\epsilon} \\
 & F
\end{tikzcd}   
\]     \[ \begin{tikzcd}
G \arrow{r}{\eta} \arrow{dr}{id} & GFG \arrow{d}{\epsilon} \\
 & G
\end{tikzcd}
\]
#+end_definition

En este caso escribimos $F \dashv G$, y $F$ es funtor adjunto de $G$.

*** Adjuntions 2
Damos una definición equivalente de funtores adjuntos.

#+begin_definition
*Adjunción*. Una adjunción es un isomorfismo natural:

\[Hom_D(FX,Y) \cong Hom_C(X,GY)\]

Natural sobre $X$ fijado cualquier $Y$ y natural sobre $Y$ fijado 
cualquier $X$. Entendiendo que usamos los funtores contravariantes $Hom(F-,Y)$,
$Hom(-,GY)$ por un lado y los funtores covariantes $Hom(FX,-)$ y $Hom(X,G-)$;
que nos dan los siguientes cuadrados de naturalidad:

\[ \begin{tikzcd}
Hom_D(FX',Y) \arrow{d}[swap]{Hom_D(Ff,Y)} \arrow{r}{\alpha_{X'}} & Hom_C(X',GY) \arrow{d}{Hom_C(f,GY)}\\
Hom_D(FX, Y) \arrow{r}{\alpha_{X}}& Hom_C(X,GY)
\end{tikzcd}
\] 

\[ \begin{tikzcd}
Hom_D(FX,Y) \arrow{d}[swap]{Hom_D(FX,g)} \arrow{r}{\beta_{Y}} & Hom_C(X,GY) \arrow{d}{Hom_C(X,Gf)}\\
Hom_D(FX,Y') \arrow{r}{\beta_{Y'}}& Hom_C(X,GY')
\end{tikzcd}
\] 
#+end_definition

Esta definición es equivalente intuitivamente a la anterior porque podemos crear $\eta$ y $\epsilon$
desde las identidades usando las siguientes transformaciones naturales: 

\[Hom_D(FX,FX) \cong Hom_C(X,GFX)\]

\[Hom_D(FGY,Y) \cong Hom_C(GY,GY)\]

*** Adjuntions 3

Podemos presentar ejemplos de adjunciones.
Los *funtores libres y de olvido* suelen ser adjuntos. Entre $Set$ y $Monoid$ tenemos:

\[ \begin{tikzcd}
{Set} \arrow[bend left]{r}{Free} & {Monoid} \arrow[bend left]{l}{Forget}
\end{tikzcd}
\]

Con la adjunción $Free \dashv Forget$. 

#+begin_theorem
*Mónada de una adjunción*. Cada adjunción da lugar a una mónada.
#+end_theorem

Tenemos un funtor $T = GF : {\cal C}  \longrightarrow {\cal C}$. Podemos definir la unidad de
la mónada como la unidad de la adjunción $\eta : 1_C \Longrightarrow T$ y la
multiplicación podemos definirla usando $id \ast \epsilon \ast id : GFGF \Longrightarrow GF$.

Ahora debemos comprobar que cumple los axiomas de mónada. El primero
se obtiene directamente desde los triángulos de la adjunción:

\[ \begin{tikzcd}
T \arrow{r}{T\eta} \arrow{dr}{id} & T^2 \arrow{d}{\mu} \\
 & T
\end{tikzcd}   
\]   \[ \begin{tikzcd}
GF \arrow{r}{GF\eta} \arrow{dr}{id} & GFGF \arrow{d}{G \epsilon F} \\
 & GF
\end{tikzcd}   
\]

Donde el segundo es resultado de aplicar el funtor $G$ a uno de los triángulos conmutativos
de la adjunción. Comprobamos el segundo axioma:

\[ \begin{tikzcd}
T^2 \arrow{d}{\mu} & T \arrow{dl}{id} \arrow{l}[swap]{\eta T} \\
T
\end{tikzcd}   
\]   \[ \begin{tikzcd}
GFGF \arrow{d}{G \epsilon F} & GF \arrow{dl}{id} \arrow{l}[swap]{\eta GF} \\
GF
\end{tikzcd}   
\]

Donde tenemos el resultado de aplicar $F$ por la derecha al otro triángulo conmutativo.

Y finalmente el axioma de conmutatividad de la mónada se comprueba como:

\[ \begin{tikzcd}
T^3 \arrow{d}{T \mu} \arrow{r}{\mu T} & T^2 \arrow{d}{\mu} \\
T^2 \arrow{r}{\mu} & T
\end{tikzcd} \]  \[ \begin{tikzcd}
GFGFGF \arrow{d}{GFG \epsilon F} \arrow{r}{G \epsilon FGF} & GFGF \arrow{d}{G\epsilon F} \\
GFGF \arrow{r}{G \epsilon F} & GF
\end{tikzcd} \] 

Donde el segundo diagrama se obtiene desde la naturalidad de $\epsilon$ aplicando funtores.

*** Adjuntions 4

Vamos a probar la igualdad entre las dos definiciones de adjunción.
Supongamos primero que tenemos el isomorfismo natural entre los dos 
conjuntos de morfismos, es decir, tenemos:

\[ \(-\) : Hom_D(FX,Y) \cong Hom_C(X,GY) \]

Si tomamos ahora los dos cuadrados naturales que teníamos por este 
isomorfismo y tomamos en ellos los casos particulares $Y = FX$ primero,
y $X = GY$ después:


\[ \begin{tikzcd}
Hom_D(FX,FX) \arrow{d}[swap]{\_ \circ Ff} \arrow{r}{(-)} & Hom_C(X,GFX) \arrow{d}{\_\circ f}\\
Hom_D(FX', FX) \arrow{r}{(-)}& Hom_C(X',GFX)
\end{tikzcd}
\]

Si tomamos la identidad $1_{FX}$ y llamamos $\eta_X = \overline{1_{FX}}$, tenemos que
\(\eta \circ f = \overline{Ff}\). Ahora, si damos la vuelta al isomorfismo $(-)$ en este 
diagrama a la vez que hacemos $X = GY$:

\[ \begin{tikzcd}
Hom_D(FGY,Y) \arrow{d}[swap]{\_ \circ Ff}  & Hom_C(GY,GY) \arrow{l}[swap]{(-)} \arrow{d}{\_\circ f}\\
Hom_D(FGY',Y) & Hom_C(GY',GY) \arrow{l}[swap]{(-)}
\end{tikzcd}
\]

Volviendo a tomar la identidad $1_{GY}$ y llamando $\epsilon_Y = \overline{1_{GY}}$, tenemos
$\epsilon \circ Ff = \overline{f}$.

Ahora tomamos el segundo cuadrado natural, y repetimos el mismo
proceso.

\[ \begin{tikzcd}
Hom_D(FX,FX) \arrow{d}[swap]{g \circ \_} \arrow{r}{(-)} & Hom_C(X,GFX) \arrow{d}{Gg\circ \_}\\
Hom_D(FX,FX') \arrow{r}{(-)}& Hom_C(X,GFX')
\end{tikzcd}
\] 

Obteniendo desde la identidad en $FX$ la ecuación $\overline{g} = Gg \circ \eta$. Y volviendo
a dar la vuelta a los isomorfimos llegamos a:

\[ \begin{tikzcd}
Hom_D(FGY,Y) \arrow{d}[swap]{g \circ \_}  & Hom_C(GY,GY) \arrow{l}[swap]{(-)} \arrow{d}{Gg \circ \_}\\
Hom_D(FGY,Y') & \arrow{l}[swap]{(-)} Hom_C(GY,GY')
\end{tikzcd}
\]

Obteniendo finalmente $\overline{Gg} = g \circ \epsilon$. De este proceso hemos obtenido finalmente
las siguientes ecuaciones:

\[ \begin{align*}
\eta \circ f &= \overline{Ff} \\
\epsilon \circ Ff &= \overline{f} \\
Gg \circ \eta &= \overline{g} \\
g \circ  \epsilon &= \overline{Gg} 
\end{align*} \]

Con ellas podemos probar la naturalidad de $\eta$ y la naturalidad de
$\epsilon$:

\[ \begin{tikzcd}
GFX  \arrow{r}{GFf} & GFY \\
X \arrow{u}[swap]{\eta_X} \arrow{r}[swap]{f} & Y \arrow{u}{\eta_Y}
\end{tikzcd}
\]   \[ \begin{tikzcd}
FGX \arrow{d}[swap]{\epsilon_X} \arrow{r}{FGg} & FGY \arrow{d}{\epsilon_Y}\\
X \arrow{r}[swap]{g} & Y
\end{tikzcd}
\]

Ya que $\eta \circ f = \overline{Ff} = GFf \circ \eta$ y $f \circ \epsilon = \overline{Gf} = \epsilon \circ FGf$. Y además podemos probar
los dos triángulos de naturalidad.

\[ \begin{tikzcd}
F \arrow{r}{F \eta_X} \arrow{dr}{id} & FGF \arrow{d}{\epsilon_{FX}} \\
 & F
\end{tikzcd}   
\]     \[ \begin{tikzcd}
G \arrow{r}{\eta_{GX}} \arrow{dr}{id} & GFG \arrow{d}{G\epsilon_X} \\
 & G
\end{tikzcd}
\]

Teniendo finalmente que:


\[\begin{align*}
\epsilon \circ F\eta &= \overline{\eta} = 1 \\
G\epsilon \circ \eta &= \overline{\epsilon} = 1
\end{align*}\]

El otro sentido de la demostración se tiene llegando primero a las cuatro ecuaciones,
y usándolas para definir el isomorfismo $(-)$. Falta entonces demostrar su naturalidad.

