#+TITLE: Ejercicios: Algebra Chapter 0
#+AUTHOR: Mario Román
#+OPTIONS: num:nil

* III. Rings and modules
** 5. Modules over a ring
*** 4. Simple modules. Lema de Schur
Tenemos que, siendo kernel e imagen submódulos, serán,
o bien $\{0\}$, o bien $M$. Dividiendo por casos:
 - $ker \phi = \{0\}$, nos da un monomorfismo. Como su imagen debe ser
   distinta de $0$ para algún elemento y es submódulo, debe ser $N$.
 - $ker \phi = M$, nos da $\phi = 0$.


** 6. Products and coproducts in R-Mod
*** 16. Cyclic modules
**** Un módulo simple es cíclico
Tomemos un elemento suyo cualquiera y
creamos $<m>$. Ocurre que debe ser un submódulo y por ser simple, todo
el módulo.

**** Un cociente por ideal es cíclico.
Sea $M = R/I$, un módulo sobre $R$ podemos generarlo simplemente 
por $<1>$, luego es cíclico.
Sea $M=<m>$ un módulo cíclico. Podemos tomar un isomorfismo que lleve
$r \mapsto rm$ y definir $I = \{r\;|\;rm=0\}$. Por 1er Teorema de isomorfía:

\[M \cong R/ker(\phi) \cong R/I\]

**** Todo cociente de cíclico es cíclico.
Usando el tercer teorema de isomorfía:

\[\frac{\frac{R}{I}}{J} \cong \frac{\frac{R}{I}}{\frac{I+J}{I}} \cong \frac{R}{I+J}\] (?)

** 7. Complexes and homology
*** 1. Exactitud entre ceros.
\[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow M \overset{}\longrightarrow 0 \overset{}\longrightarrow \dots \]
Tenemos que el núcleo de la segunda debe ser igual a la imagen de la primera y
por tanto, cero. Eso sólo es posible si $M=0$.

*** 2. Exactitud entre isomorfías
    \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow M \overset{}\longrightarrow M' \overset{}\longrightarrow 0 \longrightarrow \dots\]
Tenemos por el primer 0 la función inyectiva y por el segundo la función 
sobreyectiva. Debe ser por tanto isomorfismo.

*** 3. Kernel y cokernel en secuencia exacta
    \[ \dots \overset{}\longrightarrow 0 \overset{}\longrightarrow L \overset{}\longrightarrow M 
    \overset{\phi}\longrightarrow M' \longrightarrow N \longrightarrow 0 \longrightarrow \dots \]
Por el primer 0 tengo una inyección $i$ de $L$ en $M$, que lo identifica con
$im(i) = ker(\phi)$. Del segundo 0 tengo que la imagen de la proyección $\pi$ de
$M'$ en $N$ es todo $N$. Entonces, por teorema de isomorfía y por exactitud:

\[N = im(\pi) \cong \frac{M'}{ker(\pi)} = \frac{M'}{im(\phi)} = coker(\phi)\]

*** 4. Hotel de Hilbert
Dada una secuencia de enteros, podemos moverla un paso a la derecha:

\[(a_1,a_2,a_3,\dots) \longrightarrow (0,a_1,a_2,\dots)\] 

Para tener el morfismo $\alpha$ que nos da la secuencia exacta:

\[ 0 \overset{}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\alpha}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\pi_1}\longrightarrow \mathbb{Z} \overset{}\longrightarrow 0 \]

Dada una secuencia de enteros, podemos moverla a los sitios pares y hacer
proyección de los impares luego:

\[(a_1,a_2,a_3,\dots) \longrightarrow (0,a_1,0,a_2,0,a_3,\dots)\]

Para tener los morfismos $\beta$ y $\pi$ que nos dan la secuencia exacta:

\[ 0 \overset{}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\beta}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{\pi}\longrightarrow \mathbb{Z}^{\oplus \mathbb{N}} \overset{}\longrightarrow 0 \] 

*** 5. Exactitud entre noetherianos
Tenemos la secuencia exacta:

\[ \dots \overset{}\longrightarrow L \overset{\alpha}\longrightarrow M \overset{\beta}\longrightarrow N \overset{}\longrightarrow \dots \]

Y supongamos $L,N$ noetherianos. Sea entonces una sucesión de ideales \(\{M_i\}\),
tenemos que las sucesiones de ideales \(\{\alpha^{-1}(M_i)\}\) y \(\{\beta(M_i)\}\) se estabilizarán
a partir de un cierto $j$. Tomando un $i > j$ tendremos que $M_i = M_{i+1}$ y por tanto,
se estabilizará la secuencia inicial.

Supongamos que existiera $x \in M_{i+1}$ pero $x \notin M_i$. Dividimos en dos casos:

*Caso 1*. $x \in im(\alpha)$, tendríamos que existiría algún elemento 
$a \in \alpha^{-1}(x) \subset \alpha^{-1}(M_{i+1}) = \alpha^{-1}(M_{i})$, pero por definición entonces $x = \alpha(a) \in M_i$.

*Caso 2*. $x \notin im(\alpha)$, tendríamos $\beta(x) \in \beta(M_{i+1})$. Existe un $y \in M_i$ tal que 
$\beta(y) = \beta(x)$, es decir, $x-y \in ker(\beta)$. Pero entonces $x-y \in\im(\alpha)$ y por tanto,
$x-y \in M_i$, llevando a $x\in M_i$.

*** 6. Epimorfismo escindido
Sea una sucesión:

\[ 0 \overset{}\longrightarrow ker(\phi) \overset{}\longrightarrow M \overset{\phi}\longrightarrow N \overset{}\longrightarrow 0 \]

Supongamos que *escinde*, entonces $\phi$ es la proyección hacia $N$ y tiene
como inversa derecha a la inclusión.

Supongamos que *tiene inversa* derecha $\psi$, entonces buscamos un isomorfismo
entre $M \cong ker(\phi) \oplus N$, que tenemos con estos dos morfismos:

\[(k,n) \mapsto \psi n + k\]
\[m \mapsto (m-\psi \phi m, \phi m)\]

*** 10. Lema corto de los cinco 
Si en el lema de la serpiente son $\lambda$ y $\nu$ isomorfismos, tenemos la sucesión:

\[0 \longrightarrow 0 \longrightarrow ker(\mu) \longrightarrow 0 \overset{\delta}\longrightarrow
  0 \longrightarrow coker(\mu) \longrightarrow 0 \longrightarrow 0\]

Por tanto, el kernel y cokernel de $\mu$ son nulos y es isomorfismo.

* VI. Linear Algebra
** 1. Free modules revisited
*** 1. R y C son isomorfos como espacios vectoriales de Q
Sabemos que $C \cong R \oplus R$. Dada una base $B$ de $\mathbb{R}$, podemos ver que será
infinita y por axioma de elección isomorfa a $B+B$, que será a su
vez una base de $\mathbb{R}^2$. Luego $\mathbb{R} \cong \mathbb{R} \oplus \mathbb{R}$.

*** 4. Álgebras de Lie
Demostramos que $[u,v] = -[v,u]$. Ya que tenemos:

$$[u,v] + [v,u] = [u,v] + [u,u] + [v,v] + [v,u] = [u+v,v] + [u+v,u] = [u+v,u+v] = 0$$

Para todas las K-álgebras, tomar $[v,w] = vw-wv$ nos da un álgebra de Lie.
Podemos verlo porque cumple las tres primeras propiedades que se le piden a un
álgebra de Lie y además:

\begin{align*}
[[u,v],w] + [[v,w],u] + [[w,u],v] & = \\
(uvw-vuw-wuv+wvu) &+\\
(vwu-wvu-uvw+uwv) &+\\
(wuv-uwv-vwu+vuw) &=\\
0
\end{align*}

*** 5. Sistemas generadores e independientes en dominios de integridad
Un sistema independiente puede no crecer a base y un sistema generador
puede no reducirse a base en un dominio de integridad. Como ejemplos
tenemos $\mathbb{Z}$ con: {2} como sistema independiente y $\{2,3\}$ como sistema generador.
Ninguno puede crear base porque las únicas bases posibles serían $\{1\}$ y $\{-1\}$.

*** 13. Un grupo abeliano con endomorfismos de característica 0.
Si tiene endomorfismos que forman un cuerpo de característica 0, podemos
identificar $\mathbb{Z}$ con los endomorfismos por propiedad universal y
luego podemos extenderlo por contener $Q$ las inversas. De otro modo, 
$Q$ es inicial en la categoría de cuerpos de característica 0, así, hay
forma de identificarlo con endomorfismos del cuerpo.

Así, nuestro grupo $A$ es espacio vectorial sobre $Q$. Y es de dimensión 1,
porque si tuviera dimensión mayor y una base de más de un elemento, colapsar
dos elementos de la base en uno sería un endomorfismo sin inversa.

*** 14. La potencia de un isomorfismo estabiliza kernel e imagen.
Tenemos que $ker(\phi^n) \subset ker(\phi^{n+1})$ y que dos subespacios contenidos de la misma
dimensión deben ser iguales. Por tanto, la dimensión debe crecer o estabilizarse
a cada paso. Si la dimensión es finita debe estabilizarse en algún punto.

Por otro lado, tenemos que las imágenes deben estabilizarse en dimensión
para tener $ker(\phi^n) \oplus im(\phi^{n+1}) = V$. Y entonces, para que el kernel no crezca,
ninguno de los vectores que forman la base de $im(\phi^n)$ pueden tener como
imagen algo que esté en $ker(\phi)$, así que vuelven a tener como imagen algo en
$im(\phi^{n+1})$, que debe estar contenido en $im(\phi^n)$ y ser de la misma
dimensión.


** 2. Homomorphisms of free modules I
*** 1. Grupo isomorfo a la suma
Tenemos que:

\[
\left( \begin{matrix} 1 & 0 \\ r & 1 \end{matrix} \right)
\left( \begin{matrix} 1 & 0 \\ p & 1 \end{matrix} \right) =
\left( \begin{matrix} 1 & 0 \\ r+p & 1 \end{matrix} \right)
\]

Luego la proyección del tercer elemento es un isomorfismo
de grupos.

*** 6. Row echelon form
Cuando trabajamos en un cuerpo podemos pasar a /row echelon form/ usando
los siguientes pasos:

 - Pasamos el primer elemento no nulo a la fila más alta.
 - Lo hacemos uno con su inversa y reducimos toda la columna restante.
 - Hacemos lo mismo con la submatriz a la derecha y debajo de ese 1.

Esto debe dejarnos sólo ceros debajo y encima de los 1 pivotes.


** 4. Presentations and resolutions
*** 1. Tor(M) es submódulo de M cuando R es dominio de integridad.
Tenemos $Tor(M) = \{ m | \exists r \in R : r \neq 0, rm = 0\}$, y siendo dos elementos $m,n$ en $Tor(M)$, 
que cumplen que $rm = 0$ y $qn = 0$, podemos
ver que su suma será cerrada y que el producto por $r\in R$ será cerrado cuando
$R$ es conmutativo:

 - $rq(m+n) = rqm+qrn = 0+0 = 0$
 - $r(pm) = p(rm) = 0$

Usando aquí que es dominio de integridad y por tanto $rq \neq 0$.

*** 2. Hom(M,N) es libre de torsión cuando lo es N.
Supongamos que no lo fuera, existiría un $f \in Hom_R(M,N)$ tal que 
$rf = 0$ para algún $r$ no divisor de $0$. Pero entonces, esto haría
que en el anillo $N$ existiese $rf(m) = 0$ para cualquier $m$, y por 
ser libre de torsión, se tendría $f(m) = 0$ para todo $m$.
Luego $f=0$.

En particular $Hom_R(M,R)$ es libre de torsión.

*** 4. Propiedades del anulador
Suponiendo $p,q \in Ann(R)$, tenemos que para todo $m \in M$ se tendrá
$pm=0$ y $qm=0$. Por lo tanto $(p+q)m=0$ y $rpm = 0$, haciéndolo ideal.

**** M de torsión si y sólo si el anulador es no nulo.
Si $Ann(M) \neq 0$, existe un elemento de $R$ que anula todo $M$, como
además $R$ es dominio de integridad, este elemento no será divisor de 0, y $M$
será torsión. Si $M$ es torsión y finitamente generado, tendrá un elemento
$r_i$ que anulará cada uno de sus generadores $m_i$. Siendo $R$ conmutativo,
el elemento producto estará en el anulador

                     \[
\prod_{i} r_i
\] 

Nótese que si quitamos la condición de que $M$ sea finitamente generado, existen
módulos como \(\mathbb{Z}_2 \oplus \mathbb{Z}_4 \oplus \mathbb{Z}_8 \dots\) que son torsión porque todo elemento se anula pero
tienen anulador vacío porque no existen elementos que anulen todo el módulo.

*** 13. Complejo de Koszul

**** Es un complejo.
Comprobamos que es un complejo viendo que las siguientes composiciones son $0$:

 - \(d_1 \circ d_2 (t) = bta - atb = 0\)
 - \(\pi \circ d_1 (r,s) = (ra+sb)\ mod(a,b)) = 0 \)

**** Es un complejo exacto cuando la secuencia es regular.
Y comprobamos que es exacto en el caso en el que la secuencia es regular viendo
que:

- \(ker(d_2) = 0\), ya que $a$ no es divisor de cero.
- \(ker(d_1) = <(b,-a)>\). Tenemos que $b$ no es divisor de cero módulo $a$, así, para que
  sea linealmente dependiente con $a$ necesitamos algo que sea cero módulo $a$. Este
  caso requiere $s$ múltiplo de $a$. Esto requiere estar dentro del ideal generado por
  $(b,-a)$.
- Que la imagen de $d_1$ es el núcleo de $\pi$ y que la proyección es sobreyectiva
  es trivial.

*** 14. Complejo de Koszul en el caso de 3 elementos
**** Es un complejo
Volvemos a comprobar que las composiciones son nulas. Tenemos de hecho que:

\[d_2 \circ d_1 = d_3 \circ d_2 = 0\]

Y que la proyección coincide con el generado por $d_1$.

**** Es un complejo exacto cuando la secuencia es regular
Otra vez, como $c$ no es divisor de cero módulo $(a,b)$, tenemos que el kernel
de $d_3$ es nulo. De la misma forma, se tiene que el $ker(d_2)=im(d_3)$, aplicando
en cada caso el no ser divisor de cero. Vuelve a tenerse una ecuación similar
que demuestra $ker(d_1) = im(d_2)$. El caso de la proyección es trivial.
*** 15. Resolución de Z sobre Z[x,y]
Podemos encontrar una resolución como:

\[0 \longrightarrow 
\mathbb{Z}[x,y] \overset{\phi} \longrightarrow 
\mathbb{Z}[x,y]^2 \overset{\delta} \longrightarrow 
\mathbb{Z}[x,y] \overset{\pi} \longrightarrow 
\mathbb{Z} \longrightarrow 0 \]

Donde $\pi$ es un morfismo que cancela $x,y$. $\delta$ es un morfismo que lleva
cada una de las copias del $1$ a $x$ e $y$. Finalmente, $\phi$ es monomorfismo
que lleva $1$ a $(y,-x)$ que es generador de $ker(\delta)$.


* VIII. Linear algebra, reprise
** 1. Preliminaries, reprise
*** 2. Funtor plenamente fiel respeta isomorfías 
Sea ${\cal F}(A) \cong {\cal F}(B)$, gracias a dos morfismos inversos $\alpha,\beta$. Como
el funtor es pleno, existen dos morfismos preimagen de ambos
llamados $\alpha',\beta'$ y tenemos que:

\[{\cal F}(\alpha' \circ \beta') = \alpha \circ \beta = 1\]

Por ser fiel, debemos tener $\alpha' \circ \beta' = 1$.
*** 3. Acción de grupo como funtor
Sea $G$ un grupo. Su acción sobre un objeto $C$ será un morfismo que
envíe cada elemento del grupo a un isomorfismo de $C$. Es decir, un
homomorfismo de grupos:

\[(G,\ast) \longrightarrow (Aut(C),\circ)\]

Pero como podemos ver $G$ como un objeto tal que cada uno de sus elementos
sea un isomorfismo, tenemos claramente un isomorfismo:

\[(Aut(G),\circ) \cong (G,\ast) \longrightarrow (Aut(C),\circ)\]

Y podemos definir el funtor que lleva $G$ a $C$ y que lleva cada endomorfismo
de $G$ a uno de $C$.

*** 17. Compleción de un álgebra
Tenemos que los $R/I^n$ son módulos en R-Mod, por tanto, la cadena siguiente
tendrá límite. Donde los morfismos serán las inclusiones naturales:

\[\dots \longrightarrow R/I^3 \longrightarrow R/I^2 \longrightarrow R/I \]

Ese límite lo llamamos $R_I$, y es el submódulo de secuencias coherentes de $\prod_i R/I^i$.
Es decir, un elemento suyo es una secuencia tal que cada elemento es la proyección
del siguiente. Este submódulo es conmutativo porque lo es el producto de todos los módulos.

Podemos incluir $R$ en $R_I$ llevando el $1$ a $(1,1,1,\dots)$. Y esto conmutará con las
proyecciones naturales que nos daba la propiedad universal.
Para que $x$ se anule al incluirlo en $R_I$ desde $R$, necesitamos que todas las proyecciones
de su imagen sean $0$, así que necesitamos que pertenezca a $I_n$ para cada $n$.

*** 19. Enteros p-ádicos
Llamamos enteros p-ádicos al límite $\mathbb{Z}_p = \varprojlim \mathbb{Z}/p^i\mathbb{Z}$, y números p-ádicos a su cuerpo de fracciones
$\mathbb{Q}_p$. Por definición, un entero p-ádico es una secuencia de enteros $\{a_i\}$ tales que:

\[ a_s \equiv a_r  \mod (p^s)\]

Para cualesquiera $s \leq r$. De otra forma, cada entero tiene una expansión única:

\[ A = b_0 + b_1 p + b_2 p^2 + b_3 p^3 + \dots\]

Donde $b_i < p$. Esto es así porque dada una secuencia $(a_i)$, tenemos la igualdad:

\[b_0 = a_0\]
\[b_i p^i + a_{i+1} = a_i\]

Y se puede construir una desde la otra usando que $a_i - a_{i+1} \equiv_{p^i} 0$. 

A partir de aquí podemos hacer aritmética como usualmente desde estos desarrollos de los
números p-ádicos.
