#+TITLE: Algebra: Chapter 0
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS: num:nil toc:nil
#+LANGUAGE: es

#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}

* IV. Álgebra lineal
** 4. Presentaciones y resoluciones
*** 4.1. Torsión
#+begin_definition
*Torsión*. Un elemento $m \in M$ módulo de $R$ es de *torsión* si $\{m\}$ es linealmente
dependiente. Es decir,

  \[ \exists r \in R,\ r \neq 0\ :\ rm = 0 \]

El conjunto de elementos de torsión se llama $Tor(M)$. Un módulo es *libre de torsión*
si $Tor(M) = 0$ y *de torsión* si $Tor(M)=M$.
#+end_definition

Un anillo conmutativo es libre de torsión sobre sí mismo si y sólo si es dominio de
integridad. Cuando esto ocurre, $Tor(M)$ es siempre submódulo de $M$. Submódulos o
sumas de módulos libres de tensión serán libres de torsión, y por todo esto, los módulos
libres sobre dominios de integridad serán libres de torsión.

#+begin_definition
*Cíclico*. Un módulo es *cíclico* cuando es generado por un elemento. Es decir,
cuando $M \cong R/I$ para algún ideal.
#+end_definition

La equivalencia se ve en este [[file:aluffi.org::*Un%20cociente%20por%20ideal%20es%20c%C3%ADclico.][ejercicio]]. Cuando en un dominio de integridad todos sus
módulos cíclicos son libres de torsión, es un cuerpo. Otra forma de pensar sobre un módulo
cíclico es como aquel que admite un epimorfismo:

\[ R \longrightarrow M \longrightarrow 0 \]

*** 4.2. Módulos finitamente presentados y resoluciones libres
#+begin_definition
*Anulador.* El anulador de un módulo $M$ es:

\[Ann_R(M) = \{ r \in R\ |\ \forall m \in M, rm = 0 \}\]
#+end_definition

Es un ideal de $R$. Cuando $M$ es finitamente generado y $R$ es dominio de integridad,
$M$ es de torsión si y sólo si $Ann(M) \neq 0$. Puede verse en este [[file:aluffi.org::*M%20de%20torsi%C3%B3n%20si%20y%20s%C3%B3lo%20si%20el%20anulador%20es%20no%20nulo.][ejercicio]].

#+begin_definition
*Módulos finitamente generados y presentados*. Sabemos que todos los módulos admiten un
epimorfismo de la forma:

\[ R^{\oplus A} \longrightarrow M \longrightarrow 0\]

Cuando lo admiten con $A$ finito, se tiene $M$ *finitamente generado*. Un módulo se dice
*finitamente presentado* si hay una secuencia exacta de la forma:

\[R^n \overset{\phi}\longrightarrow R^m \longrightarrow M \longrightarrow 0\]
#+end_definition

Si $R$ es Noetheriano, todo módulo finitamente generado es finitamente presentado.

#+begin_definition
*Resolución*. Una resolución de $M$ mediante módulos libres finitamente generados es
un complejo exacto:

\[ \dots \rightarrow R^{m_3} \rightarrow R^{m_2} \rightarrow R^{m_1} \rightarrow R^{m_0} \rightarrow M \rightarrow 0 \]
#+end_definition

Aquí podemos entender que $R^{m_0}$ contiene los generadores, $R^{m_1}$ las relaciones
entre los generadores, $R^{m_2}$ las relaciones entre relaciones, y así sucesivamente.

Un dominio de integridad es *cuerpo si y sólo si todos sus módulos son finitamente generados*,
esto es equivalente a tener:

\[ 0 \longrightarrow R^m \longrightarrow M \longrightarrow 0 \]

para cualquier módulo.

Un dominio de integridad es *PID si todas las resoluciones como finitamente generado 
extienden a finitamente presentado*, de la forma:

\[0 \longrightarrow R^{m_1} \longrightarrow R^{m_0} \overset{\pi}\longrightarrow M \longrightarrow 0\]

esto equivale a pedir que $\ker(\pi)$ sea libre.


*** 4.3. Leyendo una presentación
Hemos visto que podemos estudiar un módulo finitamente presentado por un
morfismo $\phi: R^n \longrightarrow R^m$, donde $M = coker(\phi)$. Esto quiere decir que 
podemos asignarle una matriz explícita.

#+begin_theorem
*Producto de módulos en matrices*. Sean $M,N$ módulos con matrices $A,B$.
Tenemos $M \oplus N$ con matriz:

\[\left(\begin{array}{c|c}
A & 0 \\ \hline 0 & B 
\end{array}\right)\]
#+end_theorem

Además nótese que las *matrices equivalentes* representan el mismo 
homeomorfismo, y por tanto el mismo módulo.

#+begin_theorem
*Transformaciones de matrices de módulos*. Una matriz representa el mismo módulo
tras las transformaciones de:
 - Permutar filas o columnas
 - Añadir filas o columnas linealmente dependientes
 - Multiplicar filas o columnas por una unidad
 - Quitar una fila y columna en la que sólo queda una unidad
#+end_theorem

Las primeras son consecuencia de la equivalencia. La última puede colocarse como
una parte de identidad en una matriz de la forma:

\[A = \left(\begin{array}{c|c}
u & 0 \\ \hline 0 & A' 
\end{array}\right)\]

Que no afecta al cokernel.
