#+TITLE: Ejercicios: Algebra Chapter 0
#+AUTHOR: Mario Román
#+OPTIONS: num:nil

* III. Rings and modules
** 5. Modules over a ring
*** 4. Simple modules. Lema de Schur
Tenemos que, siendo kernel e imagen submódulos, serán,
o bien $\{0\}$, o bien $M$. Dividiendo por casos:
 - $ker \phi = \{0\}$, nos da un monomorfismo. Como su imagen debe ser
   distinta de $0$ para algún elemento y es submódulo, debe ser $N$.
 - $ker \phi = M$, nos da $\phi = 0$.


** 6. Products and coproducts in R-Mod
*** 16. Cyclic modules
**** Un módulo simple es cíclico
Tomemos un elemento suyo cualquiera y
creamos $<m>$. Ocurre que debe ser un submódulo y por ser simple, todo
el módulo.

**** Un cociente por ideal es cíclico.
Sea $M = R/I$, un módulo sobre $R$ podemos generarlo simplemente 
por $<1>$, luego es cíclico.
Sea $M=<m>$ un módulo cíclico. Podemos tomar un isomorfismo que lleve
$r \mapsto rm$ y definir $I = \{r\;|\;rm=0\}$. Por 1er Teorema de isomorfía:

\[M \cong R/ker(\phi) \cong R/I\]

**** Todo cociente de cíclico es cíclico.
Usando el tercer teorema de isomorfía:

\[\frac{\frac{R}{I}}{J} \cong \frac{\frac{R}{I}}{\frac{I+J}{I}} \cong \frac{R}{I+J}\] (?)


* VI. Linear Algebra
** 1. Free modules revisited
*** 1. R y C son isomorfos como espacios vectoriales de Q
Sabemos que $C \cong R \oplus R$. Dada una base $B$ de $\mathbb{R}$, podemos ver que será
infinita y por axioma de elección isomorfa a $B+B$, que será a su
vez una base de $\mathbb{R}^2$. Luego $\mathbb{R} \cong \mathbb{R} \oplus \mathbb{R}$.

*** 4. Álgebras de Lie
Demostramos que $[u,v] = -[v,u]$. Ya que tenemos:

$$[u,v] + [v,u] = [u,v] + [u,u] + [v,v] + [v,u] = [u+v,v] + [u+v,u] = [u+v,u+v] = 0$$

Para todas las K-álgebras, tomar $[v,w] = vw-wv$ nos da un álgebra de Lie.
Podemos verlo porque cumple las tres primeras propiedades que se le piden a un
álgebra de Lie y además:

\begin{align*}
[[u,v],w] + [[v,w],u] + [[w,u],v] & = \\
(uvw-vuw-wuv+wvu) &+\\
(vwu-wvu-uvw+uwv) &+\\
(wuv-uwv-vwu+vuw) &=\\
0
\end{align*}

*** 5. Sistemas generadores e independientes en dominios de integridad
Un sistema independiente puede no crecer a base y un sistema generador
puede no reducirse a base en un dominio de integridad. Como ejemplos
tenemos $\mathbb{Z}$ con: {2} como sistema independiente y $\{2,3\}$ como sistema generador.
Ninguno puede crear base porque las únicas bases posibles serían $\{1\}$ y $\{-1\}$.

*** 13. Un grupo abeliano con endomorfismos de característica 0.
Si tiene endomorfismos que forman un cuerpo de característica 0, podemos
identificar $\mathbb{Z}$ con los endomorfismos por propiedad universal y
luego podemos extenderlo por contener $Q$ las inversas. De otro modo, 
$Q$ es inicial en la categoría de cuerpos de característica 0, así, hay
forma de identificarlo con endomorfismos del cuerpo.

Así, nuestro grupo $A$ es espacio vectorial sobre $Q$. Y es de dimensión 1,
porque si tuviera dimensión mayor y una base de más de un elemento, colapsar
dos elementos de la base en uno sería un endomorfismo sin inversa.

*** 14. La potencia de un isomorfismo estabiliza kernel e imagen.
Tenemos que $ker(\phi^n) \subset ker(\phi^{n+1})$ y que dos subespacios contenidos de la misma
dimensión deben ser iguales. Por tanto, la dimensión debe crecer o estabilizarse
a cada paso. Si la dimensión es finita debe estabilizarse en algún punto.

Por otro lado, tenemos que las imágenes deben estabilizarse en dimensión
para tener $ker(\phi^n) \oplus im(\phi^{n+1}) = V$. Y entonces, para que el kernel no crezca,
ninguno de los vectores que forman la base de $im(\phi^n)$ pueden tener como
imagen algo que esté en $ker(\phi)$, así que vuelven a tener como imagen algo en
$im(\phi^{n+1})$, que debe estar contenido en $im(\phi^n)$ y ser de la misma
dimensión.


** 2. Homomorphisms of free modules I
*** 1. Grupo isomorfo a la suma
Tenemos que:

\[
\left( \begin{matrix} 1 & 0 \\ r & 1 \end{matrix} \right)
\left( \begin{matrix} 1 & 0 \\ p & 1 \end{matrix} \right) =
\left( \begin{matrix} 1 & 0 \\ r+p & 1 \end{matrix} \right)
\]

Luego la proyección del tercer elemento es un isomorfismo
de grupos.

*** 6. Row echelon form
Cuando trabajamos en un cuerpo podemos pasar a /row echelon form/ usando
los siguientes pasos:

 - Pasamos el primer elemento no nulo a la fila más alta.
 - Lo hacemos uno con su inversa y reducimos toda la columna restante.
 - Hacemos lo mismo con la submatriz a la derecha y debajo de ese 1.

Esto debe dejarnos sólo ceros debajo y encima de los 1 pivotes.


** 4. Presentations and resolutions
*** 1. Tor(M) es submódulo de M cuando R es dominio de integridad.
Tenemos $Tor(M) = \{ m | \exists r \in R : r \neq 0, rm = 0\}$, y siendo dos elementos $m,n$ en $Tor(M)$, 
que cumplen que $rm = 0$ y $qn = 0$, podemos
ver que su suma será cerrada y que el producto por $r\in R$ será cerrado cuando
$R$ es conmutativo:

 - $rq(m+n) = rqm+qrn = 0+0 = 0$
 - $r(pm) = p(rm) = 0$

Usando aquí que es dominio de integridad y por tanto $rq \neq 0$.

*** 2. Hom(M,N) es libre de torsión cuando lo es N.
Supongamos que no lo fuera, existiría un $f \in Hom_R(M,N)$ tal que 
$rf = 0$ para algún $r$ no divisor de $0$. Pero entonces, esto haría
que en el anillo $N$ existiese $rf(m) = 0$ para cualquier $m$, y por 
ser libre de torsión, se tendría $f(m) = 0$ para todo $m$.
Luego $f=0$.

En particular $Hom_R(M,R)$ es libre de torsión.

*** 4. Propiedades del anulador
Suponiendo $p,q \in Ann(R)$, tenemos que para todo $m \in M$ se tendrá
$pm=0$ y $qm=0$. Por lo tanto $(p+q)m=0$ y $rpm = 0$, haciéndolo ideal.

**** M de torsión si y sólo si el anulador es no nulo.
Si $Ann(M) \neq 0$, existe un elemento de $R$ que anula todo $M$, como
además $R$ es dominio de integridad, este elemento no será divisor de 0, y $M$
será torsión. Si $M$ es torsión y finitamente generado, tendrá un elemento
$r_i$ que anulará cada uno de sus generadores $m_i$. Siendo $R$ conmutativo,
el elemento producto estará en el anulador

                     \[
\prod_{i} r_i
\] 

Nótese que si quitamos la condición de que $M$ sea finitamente generado, existen
módulos como \(\mathbb{Z}_2 \oplus \mathbb{Z}_4 \oplus \mathbb{Z}_8 \dots\) que son torsión porque todo elemento se anula pero
tienen anulador vacío porque no existen elementos que anulen todo el módulo.

*** 13. Complejo de Koszul

**** Es un complejo.
Comprobamos que es un complejo viendo que las siguientes composiciones son $0$:

 - \(d_1 \circ d_2 (t) = bta - atb = 0\)
 - \(\pi \circ d_1 (r,s) = (ra+sb)\ mod(a,b)) = 0 \)

**** Es un complejo exacto cuando la secuencia es regular.
Y comprobamos que es exacto en el caso en el que la secuencia es regular viendo
que:

- \(ker(d_2) = 0\), ya que $a$ no es divisor de cero.
- \(ker(d_1) = <(b,-a)>\). Tenemos que $b$ no es divisor de cero módulo $a$, así, para que
  sea linealmente dependiente con $a$ necesitamos algo que sea cero módulo $a$. Este
  caso requiere $s$ múltiplo de $a$. Esto requiere estar dentro del ideal generado por
  $(b,-a)$.
- Que la imagen de $d_1$ es el núcleo de $\pi$ y que la proyección es sobreyectiva
  es trivial.

*** 14. Complejo de Koszul en el caso de 3 elementos
**** Es un complejo
Volvemos a comprobar que las composiciones son nulas. Tenemos de hecho que:

\[d_2 \circ d_1 = d_3 \circ d_2 = 0\]

Y que la proyección coincide con el generado por $d_1$.

**** Es un complejo exacto cuando la secuencia es regular
Otra vez, como $c$ no es divisor de cero módulo $(a,b)$, tenemos que el kernel
de $d_3$ es nulo. De la misma forma, se tiene que el $ker(d_2)=im(d_3)$, aplicando
en cada caso el no ser divisor de cero. Vuelve a tenerse una ecuación similar
que demuestra $ker(d_1) = im(d_2)$. El caso de la proyección es trivial.
*** 15. Resolución de Z sobre Z[x,y]
Podemos encontrar una resolución como:

\[0 \longrightarrow 
\mathbb{Z}[x,y] \overset{\phi} \longrightarrow 
\mathbb{Z}[x,y]^2 \overset{\delta} \longrightarrow 
\mathbb{Z}[x,y] \overset{\pi} \longrightarrow 
\mathbb{Z} \longrightarrow 0 \]

Donde $\pi$ es un morfismo que cancela $x,y$. $\delta$ es un morfismo que lleva
cada una de las copias del $1$ a $x$ e $y$. Finalmente, $\phi$ es monomorfismo
que lleva $1$ a $(y,-x)$ que es generador de $ker(\delta)$.
