#+TITLE: Category theory foundations
#+DESCRIPTION: Short course by Steve Awodey on the Oregon Summer School 2012

#+SETUPFILE: config.setup
#+SETUPFILE: essay.setup
#+LANGUAGE: en
#+OPTIONS: toc:nil
#+TODO: TODO WIP | CHECK DONE

* Category theory foundations 1.0
Category theory is the abstract algebra of abstract functions.

** Functions on sets
In set theory, a function $f \colon A \to B$ is a subset of the cartesian
product $f \subset A \times B$, such that for all $a \in A$, there exists a unique
$b \in B$ such that $f(a) = b$.

Composition of functions is distributive and it has an identity.
Categories arise as an abstraction of this setting.

** Definition of category
A category is defined by a class of objects and a class of arrows.
A distributive composition with identity. The axioms of a category
are the distributivity and the identity as a neutral element.
** Isomorphisms
** Examples
*** Finite categories
*** Posets
*** Monoids
*** Category of all posets
*** Relations on sets
*** Category of proofs
The objects are logic formulas and arrows are deductions on the formal
system, from the assumptions to the conclusions, that can be composed.
* Category theory foundations 1.1
** Constructions on categories
*** Product category
*** Arrow category
${\cal C}^{\to}$, where objects are arrows on ${\cal C}$ and arrows
are commutative squares.
*** Slice category
**** Cat, the category of categories
** Functors
Preserve all the structure of a category.

*** Exponential functor on sets
Fix an object $A$, then $B \mapsto B^{A}$ is a functor on sets.

** Duality
*** Contravariant functors
**** Example: Hom-Functors
** Hom-sets
Assuming ${\cal C}$ small, $\mathrm{hom}(A,B)$ is the set of arrows from $A$ to $B$. If we fix $A$,
we get a functor $\mathrm{hom}(A,-)$; if we fix $B$, we get a contravariant functor $\mathrm{hom}(-,B)$.

* Category theory foundations 1.2
** Representable functors
A functor is representable if it can be written as an hom-set.

The currying of the $Hom$ functor is the Yoneda embedding. (!)

* Category theory foundations 2.0
** Universal mappings
*** Products (MacLane, 1949)
Products on categories, on posets...
*** Coproducts and duality
*** Exponentials
Suppose we have all products. An exponential for $A,B$ is
an object $B^{A}$ such that

\[\begin{tikzcd}
B^{A} & B^{A} \rar{e} \times A & B \\
X \uar[dashed]{\exists! f} & X \times A \uar{f \times 1} \urar[swap]{g} &
\end{tikzcd}\]

* Category theory foundations 2.1
In groups, the homomorphisms are not an exponential. Groupoids are!
They form a cartesian closed category.

** Cartesian closed category
A category is *cartesian closed* if it has

  * all products.
  * all exponentials.
  * the terminal object.
 
** Adjunction Product-Exponential
Observe that the universal mapping property of the exponent
implies that every time we have a map like $X \times A \to B$,
we can define $X \to B^{A}$. It exactly says that the two functors
are adjoints.

** Universal properties as rules of inference
Universal properties are like rules of inference

  * Product

    \begin{prooftree}
    \AxiomC{$X \to A$}
    \AxiomC{$X \to B$}
    \BinaryInfC{$X \to A \times  B$}
    \end{prooftree}

  * Coproduct

    \begin{prooftree}
    \AxiomC{$A \to X$}
    \AxiomC{$B \to X$}
    \BinaryInfC{$A + B \to X$}
    \end{prooftree}

  * Exponential

    \begin{prooftree}
    \AxiomC{$X \times A \to B$}
    \UnaryInfC{$X \to B^A$}
    \end{prooftree}

In the case where $X=1$, we get a particular case of the inference rules.

** Exponentials in a poset
Exponentials in a poset are implications on intuitionistic
propositional calculus. Rules of logic can be written as universal
properties.

*** Proof relation
A natural deduction logic is a category where deductions are morphisms
and propositions are objects. We can prove the adjunction on the rules.

*** Category of proofs
If we take the category of proofs, we get the lambda calculus.
This is a richer structure.

This is called *category of types* or *category of proofs*.

* Category theory foundations 2.2
** Category of types on \lambda-calculus is CCC
To make this a CCC, we need to identify certain proofs. We have to identify
some proofs to make this a CCC

  * $\mathrm{fst}(a,b) = a$
  * $\mathrm{snd}(a,b) = b$
  * $(\lambda x.b)a = b[a/x]$

This is simplification of proofs. 

** Theory in the \lambda-calculus
We have some basic types $A,B,\dots$, basic terms $a:X,b:Y,\dots$ and equations
between terms of the same type. That defines a theory.

You could formulate the theory of groups or any algebraic theory in
this way as a lambda theory. The theory of the reflexive domain is an
example of higher order theory that can be formulated as a lambda theory.

We can then define a model of such a theory in a CCC as an assignment of
objects to basic types and morphisms as functions.

  * $\llbracket A \rrbracket \in {\cal C}$, for any basic type
  * $\bbk{a} \colon 1 \to \bbk{X}$, for any basic term

and it can be extended to all terms as

  * $\bbk{t} \colon 1 \to A$, for any term $t \colon A$,
  * in particular, $f \colon A \to B$, $\bbk{f} \colon \bbk{A} \to \bbk{B}$.

That is, you can interpret this on any algebraic theory and a model of that
theory will arise.

** Completeness theorem of CCC for \lambda-calculus
For any theory $\mathbb{T}$ in \lambda-calculus

  1) for any closed terms $a,b\colon X$, $\mathbb{T} \vdash a = b$ if and only if $\bbk{a} = \bbk{b}$ in
     any CCC.
  2) there exists a closed term $t : X$ if and only if in every $\mathbb{T}$ model of in 
     a CCC, $1 \to \bbk{X}$.


This says that lambda calculus is really equivalent to the notion of a CCC.
\[
\lambda^{x,\to} \simeq CCC
\]

Propositional logic itself is exactly equivalent to the notion of a CCC Poset.
If we add the disjunction, we get a Heyting algebra.

Kripke models are a specialization to some special cartesian closed categories.

* Category theory foundations 3.0
** Arithmetic on a Cartesian Closed Category
All the usual arithmetic can be expressed on cartesian closed categories.
** Lambda calculus with sums on a CCC
Lambda calculus with sums can be expressed on a CCC with coproducts and
you can use it to prove equations on a CCC because of its soundness.
** Natural transformation
Represents the concept of a morphism independent of the choice
of objects. This is the notion of parametricity or uniformity.
*** Definition of natural transformation
*** Example of naturality: sets through time
Discrete time parametrized on the natural numbers. A function
between two sets through time should be a natural transformation
between the indexed family of sets.

If we see $\omega$ as the natural preorder, the category of sets through
time is $\mathtt{Set}^{\omega}$, the category of functors from $\omega$ to $\mathtt{Set}$.

** Definition of functor categories
*** Functor categories make Cat a CCC
*** Example: the arrow category
Can be seen as a functor category from a category with only
one morphism to the base category.
*** Example: product category
$\mathbb{C}^2 \cong \mathbb{C} \times \mathbb{C}$ where $2$ is a discrete category of two objects.
*** Example: graph category
*** Example: simplicial sets
* Category theory foundations 3.1
** The Yoneda embedding
Presheaves of the form $\mathtt{Sets}^{{\cal C}^{op}}$. If we assume ${\cal C}$ locally small, the functor
hom can be defined. The functor $\mathrm{Hom}$ can be curried to get a functor
$y \colon {\cal C} \to \mathtt{Sets}^{{\cal C}^{op}}$.

This functor takes a morphism to a natural transformation between two functors.
** Yoneda Lemma
Given any $c \in {\cal C}$ and $F \colon {\cal C}^{op}\to \mathtt{Sets}$, there is an isomorphism
\[
\mathrm{Hom}(yC,F) \cong FC.
\]

*** Proof of the Yoneda Lemma

*** Corollary
The isomorphism is natural on both arguments.

*** Utility of Yoneda
The category $\mathtt{Sets}^{{\cal C}^{op}}$ is a topos, has a nice logical structure; while the
category was ${\cal C}$ any category. If the Yoneda embedding preserves the structure,
that gives us a nice structure on ${\cal C}$.

** Examples of usage of the Yoneda Lemma
*** Product
Propositionally, the universal mapping property of the product
can be written as

\begin{prooftree}
\AxiomC{$X \to A$}
\AxiomC{$X \to B$}
\doubleLine
\BinaryInfC{$X \to A \times  B$}
\end{prooftree}

but this rule of inference goes both ways. And this is also a
bijection between the two sides;

\[
\mathrm{hom}(X,A) \times \mathrm{hom}(X,B) \cong \mathrm{hom}(X, A \times B).
\]

*** Example
Consider $\mathrm{hom}(X,-)$ and apply it to the product diagram.
We get

\[\begin{tikzcd}
& \mathrm{hom}(X,A \times B) \drar\dlar\dar[dashed]{\cong} & \\
\mathrm{hom}(X,A) & \mathrm{hom}(X,A) \times \mathrm{hom}(X,B) \lar{\pi}\rar{\pi} & \mathrm{hom}(X,B)
\end{tikzcd}\]

The universal properties can be expressed using hom-sets.

*** Claim
$yC \cong yD \implies C \cong D$

We can prove some equations using this technique.

\[
y({\cal C}^{A+B}) \cong y({\cal C}^A \times {\cal C}^B)
\]

**** Proof
$\mathrm{hom}(X\times (A+B), C) \cong \mathrm{hom}(X \times A,C) \times \mathrm{hom}(X \times B,C)$

This reduces the proof of ${\cal C}^{A+B} \cong {\cal C}^A \times {\cal C}^B$ to a much simpler algebraic
manipulation.

* Category theory foundations 3.2
** Laws in any CCC
Products distribute over coproducts. Exponentials make products distribute
over coproducts.

*** Proof
Using Yoneda.

*** Yoneda embedding preserves all the cartesian closed structure

* Category theory foundations 4.0
** Sets^C^op is a cartesian closed category
They are some kind of "variable sets"; sets that vary on a parameter
coming from the index category. These things have products and coproducts
defined pointwise. Exponentials could be also defined pointwise, but it has
a covariant and a contravariant component, so it is not useful to get a
definition of exponentials on morphisms. This does not work for exponentials.

** Yoneda to the rescue
We are trying to define a functor $B^A(X)$. If it exists, it has to be like
\[
B^A(X) \cong \mathrm{hom}(yX,B^{A}) \cong \mathrm{hom}(yX \times A, B).
\]

If we take this as the definition, $\mathrm{hom}(y- \times A,B)$ is a contravariant
function.

*** Corollary
As a corollary, $y \colon {\cal C} \to \mathtt{Set}^{{\cal C}^{op}}$ preserves CC structure.

**** Proof
We can prove using Yoneda lemma that $y(B^A) = y(B)^{y(A)}$.

** Completeness of \lambda-calculus
Every cartesian closed category can be embedded into a $\mathtt{Sets}^{{\cal C}^{op}}$.

#+begin_theorem
Completeness of \lambda-calculus with respect to variable sets.
Given any \lambda theory $\mathbb{T}$, and $s,t {:} X$
\[
\mathbb{T} \vdash s=t \iff \text{ for any interpretation}, \bbk{s} = \bbk{t}
\]

There is a $t \colon X$ iff in every model $\bbk{t} \colon 1 \to \bbk{X}$.
#+end_theorem

** Awodey's Theorem
Kripke completeness.

#+begin_theorem
The same thing happens to respect to $\mathtt{Sets}^{P}$, where $P$ is a poset.
#+end_theorem

** Adjointness
The following are examples of adjoints

  1. Products
  2. Exponentials
  3. Coproduct
  4. Induction
  5. Recursion
  6. Natural numbers
  7. Inductively defined types
  8. Logical connectives
  9. Quantifiers
  10. Sigma and Pi types

*** Product-exponential
The functors $F(X) = X \times A$ and $G(X) = Y^{A}$ are adjoints. There is a natural
isomorphism between $\mathrm{hom}(X \times A,Y) \cong \mathrm{hom}(X,Y^{A})$.

*** Product-diagonal
\[
\mathtt{hom}((X,X), (A,B)) \cong \mathtt{hom}(X,A \times B)
\]

*** Chain of adjoints

\[ + \dashv \Delta \dashv \times \dashv \mathrm{exp}
\]

* Category theory foundations 4.1
** Uniqueness of adjoints
Every universal property and every adjoint determine an object up
to isomorphism. Adjoints are unique up to isomorphism.

*** Proof of the uniqueness of adjoints
Using the Yoneda Lemma

** Unit and counit of and adjunction
*** Example: product-exponent
Evaluation is the counit.
*** Example: diagonal-product
The diagonal map is the unit.
** Example: adjoints in logic
In Propositional calculus, conjunction is an adjoint.
Entailment is reflexive and transitive, so proofs form a category.

\begin{prooftree}
\AxiomC{$\theta \vdash \varphi$}
\AxiomC{$\theta \vdash \rho$}
\doubleLine
\BinaryInfC{$\theta \vdash \varphi \times \rho$}
\end{prooftree}

\begin{prooftree}
\AxiomC{$\varphi \vdash \theta$}
\AxiomC{$\rho \vdash \theta$}
\doubleLine
\BinaryInfC{$\rho + \varphi \vdash \theta$}
\end{prooftree}

Terminal and initial objects can be written as adjoints. Implications
can be written as adjoints. This work is due to Lawvere. 

/Adjointness in Foundations/, W. Lawvere.

** Example: quantifiers
We will write formulas with individual variables; and we build up formulas
involving some variables in the usual way. We have a deduction system with
entailment and rules of inference.

There is an operation of adding a new variable to a context. If I have,
\[
x_1,\dots,x_n \vdash \varphi(x_1,\dots,x_n),
\]

I can get
\[
x_1,\dots,x_n,y \vdash \varphi(x_1,\dots,x_n) \vdash \psi(x_1,\dots,x_n,y).
\]


This operation has adjoints. Its right adjoint is $\ast \vdash \forall$

\begin{prooftree}
\AxiomC{$^{y\text{ in context}}\varphi(x_1,\dots,x_n) \vdash \psi(x_1,\dots,x_n,y)$}
\doubleLine
\UnaryInfC{$\varphi(x_1,\dots,x_n) \vdash \forall_y \psi(x_1,\dots,x_n,y)$} 
\end{prooftree}

and its left adjoint is $\exists \vdash \ast$

\begin{prooftree}
\AxiomC{$\varphi(x_1,\dots,x_n,y) \vdash ^{y\text{ in context}}\psi(x_1,\dots,x_n)$}
\doubleLine
\UnaryInfC{$\exists_y\varphi(x_1,\dots,x_n) \vdash \psi(x_1,\dots,x_n,y)$} 
\end{prooftree}

Unit and counit look like provable formulas.

** Proof theory of first order logic
The proof theory of propositional logic was the lambda calculus. The proof
theory of first order logic is dependent type theory (??).

*** Propositional logic

\begin{tabular}{c|c|c}
Propositional logic & Provability & Proof/type theory \\
\hline
Logical Point of view & Intuitionistic PL $\wedge,\vee$ & STLC with simple types $\times,+$ \\
CT & Poset CCC / Heyting algebra & CCC with sums \\
\hline
& Poset & Category
\end{tabular}

*** First order logic

\begin{tabular}{c|cc}
FOL & Provability & Proof/type theory \\
\hline
Logic & Intuitionistic FOL $\forall,\exists$ & Dependent Type theory $\Pi,\Sigma$ \\
CT & Heyting category & Locally cartesian closed category \\
\hline
& Poset & Category
\end{tabular}

A locally cartesian closed category is a category such that any slice is CCC.

*** Yoneda and CCC
If ${\cal C}$ is a CCC, the Yoneda embedding is also cartesian closed. It preserves the
interpretation of dependent type structure of a category.

We have the same Kripke completeness theorem for the full system of Martin-Lof
type theory.
