#+TITLE: Math drill cards
#+DESCRIPTION: Spaced-repetition cards for math subjects.
#+SETUPFILE: math.setup

* Category theory
** Universal arrow                                                   :drill:
SCHEDULED: <2017-05-01 Mon>
:PROPERTIES:
:ID:       f5c0c0db-7fd6-486d-9eab-d0f87b6f8d54
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2017-04-27 Thu 21:44]
:END:
Definition of universal arrow

*** Definition
If $S \colon D \to C$ is a functor and $c \in C$, its *universal arrow* is
$(r,u)$ such that for every pair $(d,f)$ there exists this unique diagram

\[\begin{tikzcd}
 & Sd \\
c \rar[swap]{u}\urar{f} & Sr \uar[swap, dashed]{\exists! S \widetilde f}
\end{tikzcd}\]

** Abelian category                                                  :drill:
SCHEDULED: <2017-04-30 Sun>
:PROPERTIES:
:ID:       ad9b7fc3-6fe9-44fb-8918-9a1a9ce60a3b
:DRILL_LAST_INTERVAL: 3.86
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 3
:DRILL_FAILURE_COUNT: 2
:DRILL_AVERAGE_QUALITY: 2.333
:DRILL_EASE: 2.36
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2017-04-26 Wed 23:45]
:END:
Definition of [[https://en.wikipedia.org/wiki/Abelian_category][abelian category]].

*** Definition
An abelian category is a preadditive category (every morphisms set is
an abelian group and the composition is bilineal on it), satisfiying

 1. it has a *null object*.
 2. there is a *biproduct* of two numbers.
 3. every morphism has kernel and cokernel.
 4. every monic is a kernel.
 5. every epic is a cokernel.

** Preadditive category                                              :drill:
SCHEDULED: <2017-04-30 Sun>
:PROPERTIES:
:ID:       01815e4d-7bf6-473c-a818-f5a4f3568967
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2017-04-26 Wed 23:44]
:END:
Definition of [[https://en.wikipedia.org/wiki/Preadditive_category][preadditive category]]

*** Definition
A category satisfiying

 * every $hom(a,b)$ is an *abelian group*.
 * composition is *bilinear* with the group operation:
   $f(g+h) = fg+hg$ y $h(f+g) = hf+hg$.

* Algebra
** Finite order divides maximal order in abelian groups              :drill:
Let $g \in G$ *abelian* be an element of maximal /finite/ order: if $h \in G$ 
has finite order, $|h| \leq |g|$. Prove that if $h$ has finite order in $G$ 
then $|h|$ divides $|g|$.

*** Proof
If $|h|$ does not divide $|g|$, then there is a prime $p$ such that

 * $|h| = p^{a+b}m$
 * $|g| = p^bn$, with $\mathrm{gcd}(n,p) = 1$.

then we know that $|h^m| = p^{a+b}$ and $|g^{p^b}| = n$. Using that we are in a
commutative group, we know that $|g^{p^b}h^m| = p^{a+b}n$, contradicting 
maximality.

** Order of commutative products                                     :drill:
If $g$ and $h$ commute, and $\mathrm{gcd}(|g|,|h|) = 1$, then $|gh| = |g||h|$.

*** Proof
We know $|gh| = N \mid |g||h|$, and

 * $1 = \left( g^{-1} \right)^{N|g|} = h^{N|g|}$
 * $1 = \left( h^{-1} \right)^{N|h|} = g^{N|h|}$

and then, $|h| \mid N|g|$ and they are coprimes, so $|h| \mid N$. Likewise, $|g| \mid N$.
Finally, $|gh| = \mathrm{lcm}(|h|,|g|) \mid N$.
* Analysis
* Topology
* Other
