#+TITLE: Institute for Advanced Study (talks)

#+latex_header: \usepackage{tikz-cd}

* Working group on Univalent Foundations - Michael Shulman

Categories can have an internal language or internal logic.

| Type theory    | Categories                                                            |
|----------------+-----------------------------------------------------------------------|
| Extensional TT | 1-categories (toposes, pretoposes, sheaves, realizability, gluing...) |
| Homotopy TT    | (∞,1)-categories, model categories, ∞-toposes                         |

The first example is the simplicial model of type theory.

** Type-theoretic fibration category
Two classes of examples

 1. Simplicial sets
 2. Sintactic category of a type theory

It should have

 * a terminal object,
 * fibrations (Kan fibrations, display maps) closed under composition and pullback.

Given a fibration $g \colon A \twoheadrightarrow B$, the pullback functor ${\cal C}/B \to {\cal C}/A$ has a right adjoint
taking fibrations to fibrations. (Pullback preserves acyclic cofibrations)

*** Weak factorization system
Two classes of maps $({\cal L}, {\cal R})$ and every morphism factors
as something in ${\cal L}$ and something in ${\cal R}$. Every square

\[\begin{tikzcd}
\cdot \rar{} \dar[swap]{{\cal L}} & \cdot \dar{{\cal R}} \\
\cdot\rar{} \urar[dashed] & \cdot 
\end{tikzcd}\]

factors as shown.
