#+TITLE: Math
#+DESCRIPTION: My math notes and exercises

#+SETUPFILE: config.setup
#+LANGUAGE: en


In this page I collect all my math notes and exercises. It has been created using =org-mode= 
with the =readtheorg= theme.

* In English
These are exercises I've written while reading books. They are still =WIP=.

 * [[file:categoriesfortheworking.org][Categories for the working mathematician]].

* In Spanish
Esta es una serie de apuntes tomados para las asignaturas del grado de matemáticas
e ingeniería informática de la Universidad de Granada.

 * [[file:algebraiii.org][Álgebra III]]. /Sobre teoría de Galois./
 * [[file:conmutativa.org][Álgebra conmutativa y computacional]]. /Sobre anillos conmutativos y bases de Gröbner./
 * [[file:inferencia.org][Inferencia estadística]]. /Curso básico de inferencia clásica y bayesiana./
 * [[file:topologiaii.org][Topología II]]. /Introducción a la topología algebraica./

* GitHub repository
You can read the source code in the [[https://github.com/M42/math][GitHub repository]] for this projects. If you find typos
or bugs or have any questions, you can [[https://github.com/M42/math/issues][open an issue]] there.
