#+TITLE: Introduction to categorical logic
#+DESCRIPTION: Notes on the course by Bauer and Awodey

#+SETUPFILE: math-en.setup
#+SETUPFILE: html.setup
#+SETUPFILE: essay.setup
#+LANGUAGE: en
#+OPTIONS: toc:nil
#+TODO: TODO WIP | CHECK DONE

* II. Type theories
** II.1. Algebraic theories
**** Signatures
A *signature* $\left\{ \Sigma_k \right\}$ is a family of sets of k-ary operations. Its *terms*
are constructed inductively knowing that

 * variables are terms.
 * given $\left( x_1,\dots,x_{k} \right)$ a k-uple of terms and $f \in \Sigma_k$, $f(x_1,\dots,x_{k})$ is a term.

**** Algebraic theories
An *algebraic theory* $\mathbb{A} = (\Sigma,A)$ is a signature and a set of equation
between its terms.

They are also called /equational theories/ and /Lawvere theories/.

***** Examples
****** Theory of groups
****** Theory of unital commutative rings
****** Theory of sets
****** Theory of pointed sets
****** Theory of R-modules
****** Counterexample: theory of fields
****** Theory of inductive datatypes

*** II.1.1. Many-sorted algebraic theories
**** Examples
***** Theory of left modules
***** Theory of graphs
***** Theory of symmetric graphs
***** Theory of a RAM
*** II.1.2. Models of algebraic theories
The motivation is to generalize the classical notions of algebraic
structures to morphisms and commutative diagrams.

**** Interpretation
An *interpretation* of a theory $\mathbb{A}$ on a category ${\cal C}$ with finite products
is given by an object $I\mathbb{A} \in \mathrm{obj}({\cal C})$ and a morphism for each operation of 
arity $k$,

\[
\forall f \in \Sigma_k,\qquad If : (I\mathbb{A})^k \to I\mathbb{A}.
\]

The interpretation of a term with a *context* of variables, $x_1,\dots,x_n \mid t$,
is given inductively by

 1. the interpretation of $x_i$ is the projection $\pi_i$.
 2. a term $f(t_1,\dots,t_k)$ is interpreted as the composition of the 
    interpretation of every subterm with the interpretation of $f$ as

    \[\begin{tikzcd}[column sep=huge]
    (I\mathbb{A})^n  \rar{(It_1,\dots,It_k)}  &
    (I\mathbb{A})^k  \rar{If}  &
    \mathbb{A}.
    \end{tikzcd}\]
    
Note that the interpretation of a term depends on the context.

**** Satisfacibility of equations
An equation $u=v$ of two terms in the same context is *satisfied*
by the interpretation $I$ if $Iu = Iv$ as morphisms.

**** Models of algebraic theories
A *model* is an interpretation that satisfies all the axioms of the
theory.

*** II.1.3. Algebraic theories as categories
The motivation is to have a general theory of what is a group,
independent from the choice of basic constants, operations and axioms.

**** Category of an algebraic theory
Given $\mathbb{A}$, we take as objects all the possible contexts $\left[ x_1,\dots,x_n \right]$ and
tuples $\langle t_1,\dots,t_n \rangle : [x_1,\dots,x_m] \to [x_1,\dots,x_n]$ of terms with context the
domain as morphisms.

Two morphisms are equal iff the axioms imply $t_k = t_{k}'$ on every $k$; and
the composition of morphisms $v = u \circ t$ is done by substitution

\[
v_i = u_i \left[ t_1,\dots,t_m / x_1,\dots,x_m \right].
\]

***** Closed to products
The product of $\left[ x_1,\dots,x_n \right]$ and $\left[x_1,\dots,x_m \right]$ exists as $\left[ x_1,\dots,x_{n+m} \right]$
in this category. Every object is a product of finitely many instances
of $[x_1]$.

**** Algebraic theory (alternative definition)
An *algebraic theory* is a small category with finite products whose
objects are $A^0,A^1,A^2,\dots$ such that $A^m\times A^n = A^{m+n}$.

***** Algebraic theory in the former sense
The basic operations of $\Sigma_k$ are the morphisms $A^k \to A$. An equation
$u = v$ is an axiom if the canonical interpretations of each morphism
being interpreted by itself coincide.

**** Examples
***** Algebraic theory of smooth maps
***** Algebraic theory of total recursive functions
***** Algebraic theory of an object
*** II.1.4. Models of algebraic theories as functors
**** Interpretations as functors
Given a model $M$ of $\mathbb{A}$ in ${\cal C}$, the interpretation is a functor $M : \mathbb{A} \to {\cal C}$
defined by

\[
M[x_1,\dots,x_k] = (M\mathbb{A})^k
\]

on objects and by the following rules on morphisms

 1) the morphism $\left\langle x_i \right\rangle : \left[ x_1,\dots,x_k \right] \to [x_1]$ is mapped to $\pi_i : (M\mathbb{A})^k \to M\mathbb{A}$.
 2) the morphism $\left\langle f(t_1,\dots,t_m) \right\rangle : [x_1,\dots,x_k] \to [x_{1}]$ is mapped into the
    composition

    \[\begin{tikzcd}[column sep=huge]
    (M\mathbb{A})^m \rar{(Mt_1,\dots,Mt_m)} &
    (M\mathbb{A})^k \rar{Mf} &
    \mathbb{A}
    \end{tikzcd}\]

 3) the morphism $\left\langle t_1,\dots,t_m \right\rangle : [x_1,\dots,x_k] \to [x_1,\dots,x_{m}]$ is mapped to the
    morphism $\left\langle Mt_1,\dots,Mt_m \right\rangle$, where $Mt_i$ is the value of $M\left\langle t_i \right\rangle$.

This interpretation is a in fact a functor.

***** The interpretation is a functor 
As $M$ is a model, all the equations of the theory are satisfied by
it. This preserves the identities given by composition of morphisms.

**** Model (alternative definition)
A *model* of $\mathbb{A}$ in ${\cal C}$ is a functor preserving finite products.

**** Category of models
The category $\mathtt{Mod}_{{\cal C}}(\mathbb{A})$ of models of the theory $\mathbb{A}$ in ${\cal C}$ has models
$M : \mathbb{A} \to {\cal C}$ as objects and natural transformations as morphisms.

**** Algebraic categories
An algebraic category is a category that is equivalent to a
category of models of an algebraic theory.

***** Examples
****** Category of groups
****** Category of C-rings
*** II.1.5. Completeness and universal models
**** Categorical logic
Categorical logic has two sides, the logical and the categorical.
The logic consists of

  1) A *type theory*, a calculus of types and terms. In the case
     of algebraic theories, there is only one type.
  2) A *logic*. In the case of algebraic theories, the logic only
     involves equations.
  3) A *theory* given by basic types, terms and axioms.
  4) *Interpretations and models*. The type theory and logic are
     interpreted denotationally in a category with enough structure.
     In the case of algebraic theories, those are categories with
     finite products.

There are special cases of simple logics

  * a /single-sorted logic/ if there is only one type.
  * a /type theory/ if there is only a very simple type system.
  * in /ML-type systems/, logic and types are identified.

And complementary to a logical system, we have its categorical
semantics

  1) Theories are categories. The structure of a category hides
     sintactic details and reflects types and logic.
  2) Models are functors. They go from theories to categories with
     richer structure, preserving the structure of the theory.
  3) Homomorphisms are natural transformations.
  4) Completeness and universal models. It is desirable for a
     categorical semantics to be complete or to have universal
     models.

**** Semantic completeness
The property that gives that if every model of $\mathbb{A}$ satisfies
an equation, the equation can be proved on the algebraic theory is
called *semantic completeness*.

**** Completeness for algebraic theories
Given $\mathbb{A}$ algebraic theory, exists a model $U \in \mathtt{Mod}_{{\cal A}}(\mathbb{A})$ called the
*universal model* for $\mathbb{A}$, such that,

\[
U \text{ satisfies } u = v
\iff
\mathbb{A} \text{ proves } u = v.
\]

As a corollary, categorical semantics of algebraic theories is
complete.

***** Proof
We can simply take $U = 1_{\mathbb{A}} : \mathbb{A} \to \mathbb{A}$ as a model, which clearly
identifies $1(f)=1(g)$ if and only if $f = g$.

**** Universal model on generalized sets
The Yoneda embedding $y : \mathbb{A} \to \widehat{\mathbb{A}}$ is a universal model for $\mathbb{A}$.

***** Proof
The embedding $y$ preserves limits and therefore, finite products.
It is a functor and a faithful one, which makes $\widehat{\mathbb{A}}$ an universal
model.

** II.2. Cartesian closed categories
*** II.2.1. Exponentials
**** Exponentials
In a category with binary products ${\cal C}$, an *exponential* is an object $B^A$
with an evaluation morphism $e : B^A \times A \to B$ such that for every $f : C \times A \to B$
exists a unique $\widetilde f : C \to B^A$ for which this diagram commutes

\[\begin{tikzcd}
B^A &
B^A \times A \drar{e} &
\\
C \uar[dashed]{\widetilde f} &
C \times A \uar{{\widetilde f} \times 1_A} \rar[swap]{f} &
B
\end{tikzcd}\]

This is the universal property of exponentials.

**** Exponentiable object
An object $A \in \mathrm{obj}({\cal C})$ is exponentiable if $B^A$ exists for every $B$.

**** Characterization of exponentiable objects
An object $A$ is exponentiable iff the functor $- \times A$ has a right
adjoint $-^{A}$.

***** TODO Proofs

**** Examples
***** Propositional calculus
*** II.2.2. Cartesian closed categories
**** Cartesian category
A *cartesian category* is a category that has finite products.

**** Cartesian closed category
A *cartesian closed category* is a cartesian category with
exponentials.

**** Characterization of cartesian closed categories by adjoints
The category ${\cal C}$ is cartesian closed if the following functors
have adjoints

 * the functor $! : {\cal C} \to 1$ to the terminal category.
 * the diagonal functor $\Delta : {\cal C} \to {\cal C} \times {\cal C}$.
 * the product by every object $-\times A : {\cal C} \to {\cal C}$.

***** TODO Proof

**** Characterization of cartesian closed categories by equations
A category ${\cal C}$ is cartesian closed if and only if

  1) $1 \in {\cal C}$ and exists a morphism $! : A \to 1$ for every $A \in {\cal C}$.
  2) a product $A \times B$ with projections and the universal property
     of the product.
  3) an exponential $B^A$ with an evaluation map and the universal
     property of the exponential.

We write the projections as $\pi_0,\pi_1$; the unique function from the product
as $\left\langle f,g \right\rangle$ and $f \times g = \left\langle f \circ \pi_0, g \circ \pi_1 \right\rangle$. The types satisfy

  1) for every $f : A \to 1$, $f = !$.
  2) for all functions $\pi_0 \circ \left\langle f,g \right\rangle = f$, $\pi_1 \circ \left\langle f,g \right\rangle = g$ and $\left\langle \pi_0\circ h, \pi_1\circ h \right\rangle = h$.
  3) for all functions $e \circ (\widetilde{f} \times 1) = f$ and $(e \circ (g \times 1))^{\sim} = g$.

**** Examples of cartesian closed categories
***** Sets with hom-objects
***** Categories with functor categories
***** Presheaf category of a small category
*** II.2.3. Frames
**** Complete poset is cocomplete poset
A poset is complete iff it is cocomplete.

***** TODO Proof
**** TODO Infinite distributive law
**** Frames
A *frame* is a complete and cartesian closed poset. That is, it
is a complete poset with the distributive law

\[ x \wedge \bigvee_{i\in I} y_i = \bigvee_{i\in I} x \wedge y_i.
\]

**** Frame morphisms
A *frame morphism* is a $f : L \to M$ between frames preserving finite
infima and arbitrary suprema.

*** II.2.4. Heyting algebras
**** Lattices
A *lattice* is a poset with finite limits and colimits.

**** Lattice homomorphisms
