#+TITLE: Koszul Pairs
#+AUTHOR: Mario Román
#+EMAIL: mromang08@gmail.com

#+OPTIONS: num:2
#+LANGUAGE: es
#+SETUPFILE: essay.setup
#+SETUPFILE: math-en.setup
#+SETUPFILE: html.setup

* Introduction
*Koszul algebras* have numerous applications in diverse fields of
Mathematics such as Algebraic Topology, Combinatorics, Representation
Theory or Algebraic Geometry, as it is showed in cite:polishchuk05,
and many of its fundamental properties still hold in *Koszul rings*,
a particular case of graded rings.

*Almost-Koszul pairs* are a tool for the study of Koszul rings; to
every strongly graded ring corresponds a canonical almost-Koszul pair.
Every almost-Koszul pair has three associate chain complexes and three
cochain complexes. If any of this six complexes is exact, all the others
are exact too; in this case, we call the pair a *Koszul pair*.

* Area of interest
In order to define Koszul pairs, we need to introduce some homological
algebra prerequsites. We will define abelian categories in general,
even if we are going to use later only the particular case of module
categories, where we will define projective, injective and flat
modules.

In particular, we will need to define *Hoschschild comohology*.

** Abelian categories
The theory of abelian categories was introduced by Buchsbaum and Grothendieck
in cite:grothendieck57 to unify the multiple cohomology theories at the time.

*** Additive category
The original motivation for additive categories is the category of abelian
groups, and, more generally, the category of momdules over a fixed ring $R$.
In these categories, morphisms between two objects form an abelian group;
and we can define functors preserving this group structure.

#+begin_definition
${\cal C}$ is an *additive category* if:

 - $\mathrm{Hom}(A,B)$ is an /abelian group/.
 - /Distributivity/ holds: $b \circ (f+g) = b\circ f + b \circ g$ and $(f+g)\circ a = f\circ a + g\circ a$.
 - Has a /zero object/.
 - Has finite /products/ and /coproducts/.

A functor $T$ between two additive categories is and *additive functor* 
if $T(f+g) = Tf+Tg$. cite:rotman08_setting
#+end_definition

*** Abelian category
Our interest is specifically on abelian categories. We will need to
assume that every morphism has a kernel and a cokernel in order to
prove results on homological algebra.

#+begin_definition
An *abelian category* is an /additive category/ such that

  * every morphism has a kernel and cokernel.
  * every monomorphism is a kernel.
  * every epimorphism is a cokernel.
#+end_definition

The category of $R\text{-modules}$ is an abelian category, but also
the category of chain complexes of an arbitrary abelian category,
$\mathtt{Ch}({\cal A})$, is an abelian category.

** Chain complexes and homology
/Homology/ was originally defined in algebraic topology as a rigorous
method allowing the topological distinction of manifolds with arbitrary
dimensional holes. The same construction can be translated into multiple
different homology theories.

$\quad$

In abelian categories, the homology provides a formal description of
the failure of a functor to be exact.

*** Chain complexes
/Chain complexes/ were initially a representation the relationships
between cycles and boundaries on a topological space; we will study
chain complexes in the abstract setting of module categories, devoided
of any explicit relation to its motivating example.

#+begin_definition
A *chain complex* is a family of $R\text{-modules}$ $\left\{ C_n \right\}$ and homomorphisms
$d_n \colon C_n \to C_{n-1}$ called /differentials/, such that each composite of
consecutive differentials is zero, i.e. $d_{n-1} \circ d_n = 0$.
#+end_definition

#+begin_theorem
Given an abelian category ${\cal A}$, the category $\mathtt{Ch}({\cal A})$ is an abelian category.
cite:weibel94_introd
#+end_theorem

*** Exact sequences
/Exact sequences/ provide a convenient framework for homological questions
such as the completion of the middle term of a particular sequence in such
a way that the homology groups are exactly zero. This kind of problems, in
particular in the category of groups, have been proven to be useful to the
resolution of problems such as the classification of finite simple groups.

#+begin_definition
A pair of composable morphisms is *exact* in the object where they can be
composed when $\mathrm{img}(f) = \mathrm{ker}(g)$. Equivalently, when $\mathrm{coker}(f) = \mathrm{coimg}(g)$.
#+end_definition

#+begin_definition
A *short exact sequence* is a diagram

\[
0 \longrightarrow
a \overset{f}\longrightarrow
b \overset{g}\longrightarrow
c \longrightarrow
0
\]

exact on $a$,$b$ and $c$.
#+end_definition

#+begin_definition
A *morphism of short exact sequences* is defined by three morphisms
$f,g,h$ making the following diagram commute

\[\begin{tikzcd}
0 \rar& 
\cdot \rar{m}\dar{f}& 
\cdot \rar{e}\dar{g}& 
\cdot \rar\dar{h}& 
0 \\
0 \rar& 
\cdot \rar{m'}& 
\cdot \rar{e'}& 
\cdot \rar& 
0 & .\\
\end{tikzcd}\]

The short exact sequences of an abelian category $A$ define a category with
these morphisms called $\mathtt{Ses}(A)$, which is preadditive with the component by 
component sum.
#+end_definition

*** Snake lemma
The /snake lemma/ will provide us with a tool to construct long exact sequences,
which will be used in the definition of derived functors. This is a first result
on algebraic homology theory.

#+begin_theorem
Given a morphism of short exact sequences $f,g,h$; there exists a morphism
$\delta \colon \operatorname{ker} h \to \operatorname{coker} f$ such that the following sequence is exact

\[\begin{tikzcd}
0 \rar &
\mathrm{ker}(f) \rar{m} &
\mathrm{ker}(g) \rar{e} &
\mathrm{ker}(h) \arrow[out = 0,in =180,swap]{dll}{\delta} \\&
\mathrm{coker}(f) \rar{m'} &
\mathrm{coker}(g) \rar{e'} &
\mathrm{coker}(h) \rar &
0
\end{tikzcd}\]
#+end_theorem
#+begin_proof
In this extended diagram

 \[ \begin{tikzcd}
	& 0 \dar              & 0 \dar            & 0 \dar           &   \\
 0 \rar & ker(f) \rar \dar  & ker(g) \rar \dar    & ker(h) \dar \ar[out=355, in=175,looseness=1, overlay, swap]{dddll}{\delta}       &   \\
 0 \rar & a \rar{m} \dar{f}  & b \rar{e} \dar{g} & c \rar \dar{h}        & 0 \\
 0 \rar & a' \rar{m'} \dar & b' \rar{e'} \dar & c' \rar \dar        & 0 \\
	& coker(f) \rar \dar & coker(g) \rar \dar  & coker(h) \rar \dar & 0 \\
	& 0                   & 0                 & 0                &
 \end{tikzcd} \]

we can first define the morphism $\delta$ using the properties of abelian categories
to prove that it exists and then prove that it is exact using again the
properties of monomorphisms and epimorphisms.
#+end_proof

*** Homology
The definition of /homology/ tries to capture the failure of the complex to be
exact as the quotient of the kernel and the image of the sucessive differential
maps.

#+begin_definition
Given a chain complex $\left\{ C_n \right\}$ with differentials $d_n$, we define the nth
homology group as

\[ H_n(C) \cong \mathrm{ker}(d_n) / \mathrm{im}(d_{n+1}).
\]
#+end_definition

It is important to notice that a sequence will be exact if and only if
all their homology groups are zero.

** Projective, injective and flat resolutions
Resolutions of injective modules are needed to define Hochschild
homology.

*** Definitions
#+begin_definition
An R-module $D$ is:

 1. *Projective* if $\mathrm{Hom}(D, -)$ is exact.
 2. *Injective* if $\mathrm{Hom}(-,D)$ is exact.
 3. *Flat* if $D \otimes -$ is exact.
#+end_definition

We know that $\mathrm{Hom}(D,-)$ and $\mathrm{Hom}(-,D)$ are left-exact and that
$D\otimes -$ is right-exact; so for them to be exact, we only need:

 - A module $D$ is *projective* when $B \longrightarrow C$ epimorphism induces
   $\mathrm{Hom}(D,B) \longrightarrow \mathrm{Hom}(D,C)$ epimorphism.

   \[ \begin{tikzcd}
               & B \dar[two heads] \\
   D \rar\urar[dashed]{\exists} & C
   \end{tikzcd} \]

 - A module $D$ is *injective* when $A \longrightarrow B$ epimorphism induces
   $\mathrm{Hom}(B,D) \longrightarrow \mathrm{Hom}(A,D)$ epimorphism.

   \[ \begin{tikzcd}
     & A \dar[two heads]\dlar \\
   D & B \lar[dashed]{\exists}
   \end{tikzcd} \]

 - A module $D$ is *flat* when $A \longrightarrow B$ monomorphism induces 
   $D\otimes A \longrightarrow D \otimes B$ monomorphism.

*** Resolutions
#+begin_definition
A *projective resolution* is a resolution

\[\dots\longrightarrow P_2\longrightarrow P_1\longrightarrow P_0
\longrightarrow M \longrightarrow 0\]

where every $P_i$ is projective.
#+end_definition

#+begin_definition
An *injective resolution* is a resolution

\[0 \longrightarrow M \longrightarrow E^0\longrightarrow E^1
\longrightarrow E^2 \longrightarrow \dots\]

where every $E^i$ is injective.
#+end_definition

#+begin_definition
A *flat resolution* is a resolution

\[\dots\longrightarrow F_2\longrightarrow F_1\longrightarrow F_0
\longrightarrow M \longrightarrow 0\]

where $F_i$ is flat.
#+end_definition

**** Explicit construction
Notice that, given a module $M$, we can always find
a surjection from a proyective module (if we have /enough
projectives/). So we can construct a projective resolution as

\[ \begin{tikzcd}[column sep=tiny]
&\ker f_2 \drar&&&&\ker \pi\drar &&& \\
\dots&&P_2 \drar[two heads]{f_2}&&P_1 \urar[two heads]{f_1} && P_0 \ar[two heads,rr]{\pi} && M \rar & 0\\
&&&\ker f_1 \urar&&&&
\end{tikzcd} \]

We can also reverse the arrows to obtain an injective resolution.

*** Derived functors
/Derived functors/ provide a canonical way to extend the image of an
exact sequence by a non two-sided exact functor.  We need an abelian
category $A$ with enough injectives to construct left-derived
functors; and we need enough projectives to construct right-derived
functors.

**** Construction of the right derived functor
Let $F$ be additive, covariant and left-exact. Let $0 \longrightarrow M \longrightarrow E^\bullet$ be an 
injective resolution with $M$ deleted; then $F(E^\bullet)$ is a complex, and we define:

\[R^i F(M) = H^i(F(E^\bullet)) = 
\frac{\ker \{F(E^i) \longrightarrow F(E^{i+1})\}}
{\im\{ F(E^{i-1}) \longrightarrow F(E^i)\}}\]

That is, if we take the /injective resolution/

\[ 0 \longrightarrow M \longrightarrow E^0 \longrightarrow E^1 
\longrightarrow \dots\]

we can delete $M$ and apply $F$ to get a (non neccesarily exact) complex where 
we can compute the homology

\[ 0 \longrightarrow F(E^0) \longrightarrow F(E^1)
\longrightarrow F(E^2) \longrightarrow \dots.\]

**** Construction of the left derived functor
Let $F$ be additive, contravariant and left-exact. Let 
$P^\bullet \longrightarrow M \longrightarrow 0$ be a projective resolution with $M$ deleted; 
then $F(P^\bullet)$ is a complex, and we define

\[R^i F(M) = H^i(F(P^\bullet)) = 
\frac{\ker \{F(P_i) \longrightarrow F(P_{i+1})\}}
{\im\{ F(P_{i-1}) \longrightarrow F(P_i)\}}\]

That is, if we take the /projective resolution/

\[\dots \longrightarrow P_2\longrightarrow P_1\longrightarrow P_0
\longrightarrow M \longrightarrow 0\]

Delete $M$ and apply $F$ to get a (non neccesarily exact) complex 
where we can compute the homology:

\[ 0 \longrightarrow F(P_0) \longrightarrow F(P_1)
\longrightarrow F(P_2) \longrightarrow \dots\]

** Hochschild homology
*** Preliminaries
Our main interest will be on a particular kind of homology and comology called
/Hochschild homology/. This section defines the preliminary necessary concepts
to develop the notion of Hochschild homology.

**** Opposite algebra.
The definition of an /opposite algebra/ is a trvial notion which will be crucial
to create the definition of a standard resolution of an algebra over a field.

#+begin_definition
If $A$ is an $R\text{-algebra}$, the *opposite algebra* of $A$, with a multiplication
given by yuxtaposition is $A^\ast$; an algebra with the same set of elements and where
the multiplication $\circ$ is defined as $x \circ y = yx$.
#+end_definition

**** Enveloping algebra.
#+begin_definition
Let $R$ be a $k\text{-algebra}$, the *enveloping algebra* of $R$ is the tensor
product $R^e = R \otimes R^{op}$, where the product is defined as

\[ (r_1 \otimes s_1)(r_2 \otimes s_2) = (r_1r_2) \otimes (s_2s_1).\]
#+end_definition

#+begin_theorem
Given any $k\text{-algebra}$, $R$, the following categories are isomorphic:

  - $(R;R)\text{-Mod}$
  - $R^e\text{-Mod}$
  - $\text{Mod-}R^e$
#+end_theorem
#+begin_proof
If $M$ is an $(R;R)\text{-module}$, we can provide it with $R^e\text{-module}$ structure
by defining $(r\otimes s)m = rms$. It is trivial to check that this structure is
compatible with our previously defined product, as

\[
(a\otimes b)(c \otimes d)m = acmdb = (ac \otimes bd)m.
\]

If $M$ is an $R^e\text{-module}$, we can provide it with $R;R\text{-module}$ structure
taking $rms = (r\otimes s) m$. Compatibility relation can be checked by the same
reasoning.
#+end_proof

**** Standard resolution.
#+begin_definition
Given $R$, a $k\text{-algebra}$ we define the *standard resolution* $(P_{\bullet},d_{\bullet})$ of $R$ in
$(R;R)\mathrm{-Mod}$ as

 - $P_n = R \otimes (R^{\otimes n}) \otimes R$
 - $d_{n} = \sum_{i=0}^n (-1)^id^i_n$

where

\[
d_n^i(a_0 \otimes \dots \otimes a_{n+1}) =
a_0 \otimes \dots \otimes a_ia_{i+1}\otimes \dots \otimes a_{n+1}
\]
#+end_definition

*** Hochschild homology
#+begin_definition
Given $R$, a $K\text{-algebra}$, and $M$, an $(R;R)\text{-module}$, we define:

  - The *Hochschild cohomology* of $R$ in $M$ as $HH^{\bullet}(R,M) = \operatorname{Ext}^\bullet_{R^e}(R,M)$.
  - The *Hochschild homology* of $R$ in $M$ as $HH_{\bullet}(R,M) = \operatorname{Tor}_\bullet^{R^e}(R,M)$.
#+end_definition

In order to compute the cohomology, we can take the following cochain
complex

\[
\mathrm{Hom}_K(K,M) \overset{b^0} \longrightarrow
\mathrm{Hom}_K(R,M) \overset{b^1} \longrightarrow
\mathrm{Hom}_K(R^{\otimes 2},M) \overset{b^2} \longrightarrow
\dots.
\]

where the $b^n$ are defined as

 - $b^0(m)(a) = am-ma$
 - $b^n = \sum^{n+1}_{i=0}(-1)^ib_i^n$

and the auxiliary morphisms $b_i^n$ are defined as

\[
b^n_i(f)(a_1\otimes \dots \otimes a_{n+1}) =
\left\{\begin{array}{ll} 
a_1f(a_2\otimes\dots\otimes a_{n+1})& \mbox{if } i=0  \\
f(a_1\otimes\dots\otimes a_ia_{i+1}\otimes\dots\otimes a_{n+1}}& \mbox{if } i=1,\dots,n \\
f(a_1\otimes\dots\otimes a_n)a_{n+1}& \mbox{if } i=n+1
\end{array}.
\right.
\]

* Methods
Our methodology is based on the review of the basic bibliography of the
subject. This article is an attempt to collect all the needed
prerequisites to work with homology and cohomology theory and
ultimately to work with Hochschild homology and Koszul pairs.

Apart from the bibliographic review, we have developed materials for
future students interested in the subject.

*** Wikipedia articles
In order to achieve a higher level of understanding of the topic and
to provide future students with accesible resources, we have written
the following articles for the Spanish wikipedia; they are published
using a Creative Commons license.

 * [[https://es.wikipedia.org/wiki/Compleci%C3%B3n_(%C3%A1lgebra)][Compleción (álgebra)]]
 * [[https://es.wikipedia.org/wiki/Lema_de_escisi%C3%B3n][Lema de escisión]]
 * [[https://es.wikipedia.org/wiki/Lema_de_la_serpiente][Lema de la serpiente]]
 * [[https://es.wikipedia.org/wiki/Funtor_Tor][Funtor Tor]]
 * [[https://es.wikipedia.org/wiki/Homolog%25C3%25ADa_de_Hochschild][Homología de Hochschild]]
 * [[https://es.wikipedia.org/wiki/Categor%25C3%25ADa_coma][Categoría coma]]
 
*** Student-organized seminars
Two student-organized seminars have been held in the university. In
those seminars, the author has lectured about category theory; giving
a basic introduction to mathematics and computer science students.

* Discussion
** Koszul algebra
/Koszul rings/ will be a generalization of /Koszul algebras/. A pair of a
ring and its categorical dual, a coring; toghether with certain coherence
relations, will constitute our definition of a Koszul pair.

#+begin_definition
A graded algebra $A$ is a *Koszul algebra* over a field $k$ if
every graded module has a graded projective resolution
$P_{\bullet}$ where the projective module $P_j$ is generated by homogeneous
elements of degree $j$.
#+end_definition

*** Quadratic algebras
Koszul algebras are a particular case of quadratic algebras. We can describe
them in full generality with the following definition.

#+begin_definition
A graded algebra $A$ is a *quadratic algebra* if the natural
application from its tensor algebra $T(A) \to A$ is surjective
and its kernel $J_A$ is generated from $J_{A} \cap (A^{1} \otimes A^1)$. cite:polishchuk05
#+end_definition

In other words, a graded quadratic algebra is determined as the
quotient of a vector space $A_{1}$ by a subspace of homogeneous
quadratic relations $S \subset V \otimes V$ as

\[
A = T(V) / \left\langle S \right\rangle.
\]

#+begin_theorem
Every Koszul $R\text{-ring}$ is a quadratic algebra.
#+end_theorem

** Almost-koszul pairs
Previous to the definition of Koszul pairs, we are going to define
/almost-koszul pairs/. Those will provide us with a weaker set of
requirements and we will be able to obtain a definition of Koszul
pairs suitable to every almost-koszul pair.

*** Graded rings
#+begin_definition 
A *graded ring* is a ring that can be written as a direct sum of
abelian groups

\[ A = \bigoplus_{n \in \mathbb{N}} A_n\]

such that $A_iA_j \subset A_{i+j}$.
#+end_definition

A *homogeneous element* is an element of any submodule $A_i$ of the
decomposition.

*** Koszul rings
#+begin_definition
A graded ring $A$ is a *Koszul ring* if $A^0$ is a semisimple ring 
and it has a resolution $P_\ast$ by projective graded left A-modules such 
that each $P_n$ is generated by homogeneous elements of degree $n$.
cite:jarastefan10
#+end_definition

*** R-rings
#+begin_definition
An $R\text{-ring}$ is an associative and unital algebra. It is an associative and
unital ring $A$ together with a morphism $u : R \longrightarrow A$.
#+end_definition

A R-ring is *graded* if it is equipped with a decomposition

\[A = \bigoplus_{n \in \mathbb{N}} A^n \]

such that multiplicaton $m^{p,q}$ maps $A^p \otimes A^q$ into $A^{p+q}$. It is *connected* 
when $A_0 = R$. It is *strongly graded* when $m^{1,p}$ is surjective. We 
call $\pi^n_A$ to the projection of $A$ onto $A^n$.

*** R-coring
Corings will be the categorical dual of rings. In order to define them, we
proceed by giving defitions of coalgebra and certain properties of this kind
of algebras. Those are also the dual notions to the preliminary definitions
we described at the start of this chapter.

#+begin_definition
A *coalgebra* over a field $K$ is a *vector space* $V$ together with linear
maps $\Delta : V \longrightarrow V \otimes V$ and $\varepsilon : V \longrightarrow K$ such that:

 1. $(id \otimes \Delta) \circ \Delta = (\Delta \otimes id) \circ \Delta$
 2. $(id \otimes \varepsilon) \circ \Delta = id 
    = (\varepsilon \otimes id) \circ \Delta$
#+end_definition

When writting in coalgebras, we will follow the *Sweedler
notation*. cite:underwood15_hopf

#+begin_definition
An $\mathbf{R\text{-coring}}$ is a /coassociative/ and /counital/ /coalgebra/. It is an 
$R\text{-bimodule}$ with a /comultiplication/ $\Delta : C \longrightarrow C \otimes C$ and  a /counit/
$\epsilon : C \longrightarrow R$.
#+end_definition

A $R\text{-coring}$ is *graded* if it is equipped with a decomposition 
$C = \bigoplus_{n \in \mathbb{N}} C_n$, such that

\[\Delta(C_n) \subset \bigoplus_{p=0}^n C_p \otimes C_{n-p}.\]

*** Almost-koszul pair
#+begin_definition
An *almost-Koszul pair* is a connected $R\text{-ring}$ and $R\text{-coring}$ $(A,C)$ 
with an isomorphism $\theta_{C,A} : C_1 \longrightarrow A^1$ that satisfies the relation

\[ m^{1,1} \circ (\theta_{C,A} \otimes \theta_{C,A}) \circ \Delta_{1,1}
= 0.\]
#+end_definition

Using Sweedler notation we can rewrite the condition as follows 


\[ \sum \theta_{C,A}(c_{(1,1)}) \theta_{C,A}(c_{(2,1)}) = 0,\]

for any $c \in C_2$.

** Almost-koszul pair complexes
Six complexes will be associated to any given Koszul pair. Its
exactness will be related, i.e., if any one of them is exact, the six
complexes will be exact. This provides a definition of Koszul
pairs relying only on this kind of complexes.

#+begin_definition
Let $(A,C)$ be an almost-Koszul pair, if we define

\[
K^{-1}_l(A,C) = R
\quad\text{ and }\quad
K^n_l(A,C) = C \otimes A^n,
\]

and the differential maps

\[
d^n_l(c \otimes a) = \sum c_{(1,p-1)} \otimes \theta_{C,A}(c_{(2,1)})a,
\]

with the exceptional case $n = -1$, where we take $d^n_l$ to be the canonical
bimodule morphisms $R \to C \otimes A^0$, mapping $1 \mapsto 1 \otimes 1 \in C_0 \otimes A^0$. We will
also define the same notion on the opposite pair as

\[
K_r^{\ast}(A,C) = K^{\ast}_l(A^{op},C^{op}).
\]
#+end_definition

#+begin_definition
Let $(A,C)$ be an almost-Koszul pair, we define

\[
K^{-1}(A,C) = C
\quad\text{ and }\quad
K^n(A,C) = C \otimes A^n\otimes C,
\]

and the differential relations given by $d^{-1} = \Delta$ and

\[
d^n = d^n_l \otimes I_C + (-1)^{n+1}I_C \otimes d^n_r.
\]
#+end_definition

#+begin_definition
Let $(A,C)$ be an almost-Koszul pair, if we define

\[
K^r_{-1}(A,C) = R
\quad\text{ and }\quad
K^r_n(A,C) = C_n \otimes A,
\]

and the differential maps

\[
d_n^r(c \otimes a) = \sum c_{(1,n-1)} \otimes \theta_{C,A}(c_{(2,1)})a.
\]

Appliying the same construction to the opposite almost-Koszul pair
gives us the complex $K^l_{\ast}$.
#+end_definition

#+begin_definition
Let $(A,C)$ be an almost-Koszul pair, we define

\[
K_{-1}(A,C) = A
\quad\text{ and }\quad
K_n(A,C) = A \otimes C_n \otimes A,
\]

and the differential relations given by $d_0$, induced by multiplication,
and

\[
d_n^{l}(a \otimes c) = \sum a\theta_{C,A}(c_{(1,1)}) \otimes c_{(2,n-1)};
\]

defining $d_n = d_n^l \otimes I_A + (-1)^nI_A\otimes d_n^r$.
#+end_definition

** Koszul pairs
#+begin_theorem
Given an almost-Koszul pair $(A,C)$, if one of these six complexes is
exact, all of them are exact, as it is showed in cite:jarastefan10.

 * $K^{l}_{\ast}(A,C)$.
 * $K^r_{\ast}(A,C)$.
 * $K_{\ast}(A,C)$.
 * $K^{\ast}_l(A,C)$.
 * $K_r^{\ast}(A,C)$.
 * $K^{\ast}(A,C)$.
#+end_theorem

#+begin_definition
An almost-Koszul pair $(A,C)$ is said to be *Koszul* if and only if the
previously discussed complexes are exact.
#+end_definition

* Conclusions
Starting from a very basic undergraduate mathematical level, all the
necessary definitions of categories, chain complexes and homology have
been developed in this work. This constitutes a reference for students
interested on the specific field of Koszul pairs and sets the ground
for future developments and undergraduate and graduate-level research.

$\quad$

In particular, future work should be able to find new
characterizations of Koszul pairs in terms of homology and cohomology
apart from the known characterizations found on cite:jarastefan10.

* References
bibliographystyle:unsrt
bibliography:math.bib
