#+TITLE: Álgebra III
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS:
#+LANGUAGE: es

#+LaTeX: \setcounter{secnumdepth}{0}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{fact}{Proposición}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}


* Extensiones de cuerpos
** La cúbica
*** Polinomios cúbicos
Toda ecuación cúbica polinómica puede escribirse en la forma
\(Y^3 + pY + q\), tomando un cambio de variable desde la original
\(X \mapsto - \frac{1}{3} b\). Esto se llama una cúbica deprimida.

El método de Vieta toma \(t = w - \frac{p}{3w}\), y llega a la ecuación:

\[w^3 + q - \frac{p^3}{27w^3} = 0\]

Ahora podemos resolver esa cuadrática y resolver luego la ecuación
en $w^3$.

* Anillos de polinomios
** Polinomios simétricos
#+begin_definition
*Polinomio simétrico*. Invariante por $f_\sigma$ para cualquier $\sigma \in S_r$, donde 
$f_\sigma (X_i) = X_{\sigma i}$. Llamamos $Sim(A[X_1\dots X_n])$ al subanillo de polinomios simétricos.
#+end_definition

Llamamos *componente homogénea* a cada sumando homogéneo maximal de un polinomio.
Un polinomio es simétrico si y sólo si cada una de sus componentes lo es.

#+begin_definition
*Polinomios simétricos elementales*. De la forma:
\[e_i = \sum_{i_1 < \dots < i_i} X_i_1 X_i_2 \dots X_i_i\]
#+end_definition
#+begin_theorem
*Teorema fundamental de los polinomios simétricos*. Los polinomios elementales
generan $Sim(A[X_1\dots X_n])$.
#+end_theorem
#+begin_proofs
Damos una relación de orden lexicográfica entre los monomios de un polinomio
simétrico homogéneo. Al mayor de ellos, llamado $X_1^{k_1} \dots X_r^{k_r}$ le restamos 
$e^{b1}_1 e^{b2}_2 \dots e^{br}_r$, donde $b_i = k_i - k_{i+1}$. Nos quedará $0$ u otro polinomio simétrico de 
igual grado pero menor en el orden lexicográfico. Este proceso debe ser finito.
#+end_proofs
