#+TITLE: Álgebra III
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS:
#+LANGUAGE: es

#+LaTeX: \setcounter{secnumdepth}{0}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{fact}{Proposición}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}


* Tema 1
** La cúbica
*** Polinomios cúbicos
Toda ecuación cúbica polinómica puede escribirse en la forma
\(Y^3 + pY + q\), tomando un cambio de variable desde la original
\(X \mapsto - \frac{1}{3} b\). Esto se llama una cúbica deprimida.

El método de Vieta toma \(t = w - \frac{p}{3w}\), y llega a la ecuación:

\[w^3 + q - \frac{p^3}{27w^3} = 0\]

Ahora podemos resolver esa cuadrática y resolver luego la ecuación
en $w^3$.

** Anillos de polinomios
*** Polinomios simétricos
#+begin_definition
*Polinomio simétrico*. Invariante por $f_\sigma$ para cualquier $\sigma \in S_r$, donde 
$f_\sigma (X_i) = X_{\sigma i}$. Llamamos $Sim(A[X_1\dots X_n])$ al subanillo de polinomios simétricos.
#+end_definition

Llamamos *componente homogénea* a cada sumando homogéneo maximal de un polinomio.
Un polinomio es simétrico si y sólo si cada una de sus componentes lo es.

*** Polinomios simétricos elementales
#+begin_definition
*Polinomios simétricos elementales*. De la forma:
\[e_i = \sum_{i_1 < \dots < i_i} X_i_1 X_i_2 \dots X_i_i\]
#+end_definition
#+begin_theorem
*Teorema fundamental de los polinomios simétricos*. Los polinomios elementales
generan cada polinomio $Sim(A[X_1\dots X_n])$ de forma única. En particular,

\[\omega : A[X_1,\dots,X_r] \longrightarrow Sim(A[X_1,\dots,X_r])\]

con $\omega(a) = a$ y $\omega(X_i) = e_i$ es un isomorfismo.
#+end_theorem
#+begin_proofs
Damos una relación de orden lexicográfica entre los monomios de un polinomio
simétrico homogéneo. Al mayor de ellos, llamado $X_1^{k_1} \dots X_r^{k_r}$ le restamos 
$e^{b1}_1 e^{b2}_2 \dots e^{br}_r$, donde $b_i = k_i - k_{i+1}$. 
Nos quedará $0$ u otro polinomio simétrico de 
igual grado pero menor en el orden lexicográfico. Este proceso debe ser finito.

La unicidad se obtiene con $0 = h(e_1\dots e_r) - k(e_1\dots e_r) = l(e_1 \dots e_r)$.
#+end_proofs

*** Resultante
#+begin_definition
*Resultante*. Es el determinante solución de $pq' - qp' = 0$ dados $p$ y $q$.

\[R(p,q) = \left| \begin{matrix}
a_0 & a_1 & \dots & a_n & 0 & \dots &\\
0   & a_0 & \dots & a_{n-1} & a_n & 0 & \dots \\
0   &   0 & a_0 & \dots & a_{n-1} & a_n & \dots \\
    &     &     &\dots & & & \\
b_0 & b_1 & \dots & b_m & 0 & \dots &\\
0   & b_0 & \dots & b_{m-1} & b_m & 0 & \dots \\
0   &   0 & b_0 & \dots & b_{m-1} & b_m & \dots \\
\end{matrix} \right|
\]

Y llamamos *matriz resultante* a la matriz de la que es determinante.
#+end_definition

#+begin_definition
*Discriminante*. El discriminante de un polinomio con raíces
$\alpha_1, \dots, \alpha_n$ en una clausura algebraica es:

\[\text{Discr}(p) = a^{2n-2} \prod_{i>j}(\alpha_i-\alpha_j)^2\]
#+end_definition

#+begin_fact
\[R(p,p') = (-1)^{\frac{n(n-1)}{2}}a_n \text{Discr}(p)\]
#+end_fact

* Tema 2
** 1. Teoría de cuerpos
*** Extensiones de cuerpos
#+begin_definition
*Extensión de cuerpos*. Subcuerpo $K$ de $F$, se nota por $F/K$. Llamamos *grado*
a la dimensión de $F$ como espacio vectorial.
#+end_definition

#+begin_theorem
*Teorema de Lagrange para extensiones de cuerpos*. Sea $K \subset F \subset E$,
extensiones de cuerpos, se tiene que:

\[ [E:K] = [E:F][F:K] \]
#+end_theorem

*** Elementos algebraicos
#+begin_definition
*Elemento algebraico*. $\alpha \in F$ es *algebraico* sobre $K$ si existe polinomio $f \in K[x]$
tal que $f(\alpha) = 0$. Un no algebraico es *trascendente* y una extensión es *algebraica*
si lo son todos sus elementos.
#+end_definition

#+begin_theorem
*Polinomio irreducible*. Dado $F/K$ con $\alpha \in F$ algebraico. Existe un único polinomio
irreducible del que $\alpha$ es raíz salvo asociados, llamado $Irr(\alpha)$.
#+end_theorem
#+begin_proofs
Tomo el núcleo del homomorfismo que evalúa un polinomio en $\alpha$. Por ser un
ideal en PID, estará generado por algún polinomio $f$ no nulo y no constante.

Este será irreducible, porque si no lo fuera, con $f = g_1g_2$ se tendría:

\[0 = f(\alpha) = g_1(\alpha)g_2(\alpha)\]

Un polinomio de grado mínimo debería estar dentro del ideal, y por tanto ser 
asociado de $f$, que lo genera.
#+end_proofs

#+begin_theorem
*Grado del irreducible*. Si $grad(Irr(\alpha,K)) = n$, entonces $[K(\alpha) : K] = n$ y 
una base de $K(\alpha)$ es $\{1,\alpha,\alpha^2,\dots,\alpha^{n-1}\}$.
#+end_theorem

#+begin_theorem
*Las extensiones finitas son algebraicas*.
#+end_theorem

** 2. Clausura algebraica
*** Existencia de clausura
#+begin_theorem
*Teorema de Steinitz*. Todo cuerpo tiene una extensión algebraicamente cerrada.
#+end_theorem

*** Homomorfismos sobre un cuerpo
#+begin_theorem
*Homomorfismo sobre un cuerpo*. Un homomorfismo sobre cuerpos $K,K'$ con extensiones
$F,F'$ con un isomorfismo $\omega : K \longrightarrow K'$ debe cumplir: $\phi|_K = \omega$. Cuando no se especifica,
se asume la identidad.

\[ \phi : F/K \longrightarrow F'/K' \]
#+end_theorem

#+begin_theorem
*Automorfismos entre extensiones*. Sea $\phi : F/K \longrightarrow F/K$ homomorfismo respetando $K$
#+end_theorem
