#+TITLE: Álgebra III
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS:
#+LANGUAGE: es

#+LaTeX: \setcounter{secnumdepth}{0}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{fact}{Proposición}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \newcommand{\twopartdef}[4]{\left\{\begin{array}{ll} #1 & \mbox{if } #2 \\ #3 & \mbox{if } #4 \end{array} \right.}
#+latex_header: \newcommand{\threepartdef}[6]{\left\{\begin{array}{lll} #1 & \mbox{if } #2 \\ #3 & \mbox{if } #4 \\ #5 & \mbox{if } #6 \end{array} \right.}

* Polinomios simétricos
** La cúbica
*** Polinomios cúbicos
Toda ecuación cúbica polinómica puede escribirse en la forma
\(Y^3 + pY + q\), tomando un cambio de variable desde la original
\(X \mapsto - \frac{1}{3} b\). Esto se llama una cúbica deprimida.

El método de Vieta toma \(t = w - \frac{p}{3w}\), y llega a la ecuación:

\[w^3 + q - \frac{p^3}{27w^3} = 0\]

Ahora podemos resolver esa cuadrática y resolver luego la ecuación
en $w^3$.

** Anillos de polinomios
*** Polinomios simétricos
#+begin_definition
*Polinomio simétrico*. Invariante por $f_\sigma$ para cualquier $\sigma \in S_r$, donde 
$f_\sigma (X_i) = X_{\sigma i}$. Llamamos $Sim(A[X_1\dots X_n])$ al subanillo de polinomios simétricos.
#+end_definition

Llamamos *componente homogénea* a cada sumando homogéneo maximal de un polinomio.
Un polinomio es simétrico si y sólo si cada una de sus componentes lo es.

*** Polinomios simétricos elementales
#+begin_definition
*Polinomios simétricos elementales*. De la forma:
\[e_i = \sum_{i_1 < \dots < i_i} X_i_1 X_i_2 \dots X_i_i\]
#+end_definition
#+begin_theorem
*Teorema fundamental de los polinomios simétricos*. Los polinomios elementales
generan cada polinomio $Sim(A[X_1\dots X_n])$ de forma única. En particular,

\[\omega : A[X_1,\dots,X_r] \longrightarrow Sim(A[X_1,\dots,X_r])\]

con $\omega(a) = a$ y $\omega(X_i) = e_i$ es un isomorfismo.
#+end_theorem
#+begin_proofs
Damos una relación de orden lexicográfica entre los monomios de un polinomio
simétrico homogéneo. Al mayor de ellos, llamado $X_1^{k_1} \dots X_r^{k_r}$ le restamos 
$e^{b1}_1 e^{b2}_2 \dots e^{br}_r$, donde $b_i = k_i - k_{i+1}$. 
Nos quedará $0$ u otro polinomio simétrico de 
igual grado pero menor en el orden lexicográfico. Este proceso debe ser finito.

La unicidad se obtiene con $0 = h(e_1\dots e_r) - k(e_1\dots e_r) = l(e_1 \dots e_r)$.
#+end_proofs

*** Resultante
#+begin_definition
*Resultante*. Es el determinante solución de $pq' - qp' = 0$ dados $p$ y $q$.

\[R(p,q) = \left| \begin{matrix}
a_0 & a_1 & \dots & a_n & 0 & \dots &\\
0   & a_0 & \dots & a_{n-1} & a_n & 0 & \dots \\
0   &   0 & a_0 & \dots & a_{n-1} & a_n & \dots \\
    &     &     &\dots & & & \\
b_0 & b_1 & \dots & b_m & 0 & \dots &\\
0   & b_0 & \dots & b_{m-1} & b_m & 0 & \dots \\
0   &   0 & b_0 & \dots & b_{m-1} & b_m & \dots \\
\end{matrix} \right|
\]

Y llamamos *matriz resultante* a la matriz de la que es determinante.
#+end_definition

#+begin_definition
*Discriminante*. El discriminante de un polinomio con raíces
$\alpha_1, \dots, \alpha_n$ en una clausura algebraica es:

\[\text{Discr}(p) = a^{2n-2} \prod_{i>j}(\alpha_i-\alpha_j)^2\]
#+end_definition

#+begin_fact
\[R(p,p') = (-1)^{\frac{n(n-1)}{2}}a_n \text{Discr}(p)\]
#+end_fact

* Extensiones de cuerpos
** 1. Teoría de cuerpos
*** Extensiones de cuerpos
*Extensión de cuerpos*. Subcuerpo $K$ de $F$, se nota por $F/K$. Llamamos *grado*
a la dimensión de $F$ como espacio vectorial.

*** Teorema de Lagrange para extensiones de cuerpos
*Teorema de Lagrange para extensiones de cuerpos*. Sea $K \subset F \subset E$,
extensiones de cuerpos, se tiene que:

\[ [E:K] = [E:F][F:K] \]

*** Elementos algebraicos
*Elemento algebraico*. $\alpha \in F$ es *algebraico* sobre $K$ si existe polinomio $f \in K[x]$
tal que $f(\alpha) = 0$. Un no algebraico es *trascendente* y una extensión es *algebraica*
si lo son todos sus elementos.

*** Polinomios irreducibles
#+begin_theorem
*Polinomio irreducible*. Dado $F/K$ con $\alpha \in F$ algebraico. Existe un único polinomio
irreducible del que $\alpha$ es raíz salvo asociados, llamado $Irr(\alpha)$.
#+end_theorem
#+begin_proofs
Tomo el núcleo del homomorfismo que evalúa un polinomio en $\alpha$. Por ser un
ideal en PID, estará generado por algún polinomio $f$ no nulo y no constante.

Este será irreducible, porque si no lo fuera, con $f = g_1g_2$ se tendría:

\[0 = f(\alpha) = g_1(\alpha)g_2(\alpha)\]

Un polinomio de grado mínimo debería estar dentro del ideal, y por tanto ser 
asociado de $f$, que lo genera.
#+end_proofs

#+begin_theorem
*Grado del irreducible*. Si $grad(Irr(\alpha,K)) = n$, entonces $[K(\alpha) : K] = n$ y 
una base de $K(\alpha)$ es $\{1,\alpha,\alpha^2,\dots,\alpha^{n-1}\}$.
#+end_theorem

#+begin_theorem
*Las extensiones finitas son algebraicas*.
#+end_theorem

** 2. Clausura algebraica
*** Existencia de clausura
#+begin_theorem
*Teorema de Steinitz*. Todo cuerpo tiene una extensión algebraicamente cerrada.
#+end_theorem

*** Homomorfismos sobre un cuerpo
#+begin_theorem
*Homomorfismo sobre un cuerpo*. Un homomorfismo sobre cuerpos $K,K'$ con extensiones
$F,F'$ con un isomorfismo $\omega : K \longrightarrow K'$ debe cumplir: $\phi|_K = \omega$. Cuando no se especifica,
se asume la identidad.

\[ \phi : F/K \longrightarrow F'/K' \]
#+end_theorem

#+begin_theorem
*Automorfismos entre extensiones*. Sea $\phi : F/K \longrightarrow F/K$ homomorfismo respetando $K$
#+end_theorem
* Cuerpos de descomposición
** Teorema de Kronecker
#+begin_theorem
*Teorema de Kronecker*. Sea $f$ de grado positivo sobre $K$, entonces existe
una extensión $F/K$ tal que existe $u \in F$ con $f(u) = 0$.
#+end_theorem
#+begin_proofs
Puedo descomponer en irreducibles $f = f_1f_2\dots f_m$; y tener una extensión cumpliendo
lo pedido:

\[ F = \frac{K[X]}{(f_1)}\]

\[u = x + (f_1)\]
#+end_proofs

** Extensión de homomorfismos
#+begin_definition
*Extensión de un homomorfismo*. $\tau : F_1 \longrightarrow F_2$ es extensión de 
$\sigma : K_1 \longrightarrow K_2$ cuando son dos extensiones $F/K$ y se cumple
que $\tau |_K_1 = \sigma$.

Cuando $\sigma = 1$, llamamos a $\tau$ *homomorfismo sobre K*.
#+end_definition

*** Extensión a polinomios
#+begin_theorem
*Extensión a polinomios*. Dado $\sigma : K_1 \longrightarrow K_2$ isomorfismo de cuerpos, hay una única
extensión a $\sigma : K_1[X] \longrightarrow K_2[X]$ cumpliendo $\sigma(x) = x$, que conserva:

 - los grados
 - los polinomios irreducibles
 - las raíces de un polinomio sobre extensiones
#+end_theorem

*** Automorfismos de una extensión
#+begin_theorem
*Automorfismos de una extensión*. Sea $\sigma : F/K \longrightarrow F/K$, entonces,
$\sigma$ es automorfismo.
#+end_theorem
#+begin_proofs
Para $u\in F$, tomamos $K(u_1,\dots,u_k)$ la extensión finita generada por todas 
las raíces del irreducible sobre $u$. Como $\sigma$ respeta raíces, puede restringirse
a esta extensión; y será inyectivo en ella por ser morfismo de cuerpos.

Como esta extensión es finita y esto es una aplicación lineal, la aplicación 
restringida es sobreyectiva.
#+end_proofs

*** Número de extensiones
#+begin_theorem
*Número de extensiones*. Teniendo $u_1$ de irreducible a $f_1$, hay tantas
extensiones $\tau : K_1[u_1] \longrightarrow F_2$ como raíces tenga su imagen $f_2$; ya que están 
completamente determinadas por la imagen de $u_1$.
#+end_theorem
#+begin_proofs
Existe un único isomorfismo llevando $\tau(u_1) = u_2$, tomando este diagrama de
isomorfismos:

\[ \begin{tikzcd}
K_1(u) \rar{\tau} & K_2(u) \\
\frac{K_1[X]}{(f_1)} \uar{p_1} \rar{\overline\sigma} &
\frac{K_2[X]}{(f_2)} \uar{p_2}
\end{tikzcd} \]

Donde $\sigma$ es inducido por el isomorfismo de extensión a polinomios.
#+end_proofs

** Cuerpo de descomposición
*** Descomposición
#+begin_definition
Un polinomio $f \in K[X]$ *descompone* en una extensión $E$ si factoriza como polinomios
lineales en $E[X]$. Llamamos *cuerpo de descomposición* a un cuerpo extensión
de $K$ minimal en el que descompone.
#+end_definition

Propiedades:

 - Sea $E$ cuerpo de descomposición, entonces $E = K(\alpha_1,\alpha_2,\dots,\alpha_n)$, siendo una
   extensión finita con grado acotado por $n!$.
 - Todo polinomio tiene cuerpo de descomposición sobre $K$, ya que podemos tomar
   una clausura algebraica y crear $K(\alpha_1,\dots,\alpha_n)$ con sus raíces.

*** Lema de isomorfismo entre cuerpos de descomposición
#+begin_theorem
Sean $E_1/K$, $E_2/K$ dos cuerpos de descomposición de $f$ sobre $K$.
Entonces existe un isomorfismo $\sigma : E_1/K \longrightarrow E_2/K$.
#+end_theorem
#+begin_proofs
Aplicamos inducción sobre el grado del polinomio irreducible de dos raíces
cualquiera y descomponemos siempre como: $f_i = (X-u_i)g_i$. Sé que hay siempre un
isomorfismo $K_1(u_1) \cong K_2(u_2)$ respetando $\sigma(u_1) = u_2$ a cada paso; y el caso de grado $0$
es trivial.
#+end_proofs

* Extensiones normales y separables
** Elementos conjugados y extensiones conjugadas
*** Elementos conjugados
Sean $u,v \in \overline{K}$, clausura algebraica. Equivalen:

 - $Irr(u,K) = Irr(v,K)$
 - $\exists \tau : K(u) \longrightarrow K(v)$ *isomorfismo* con $\tau(u) = v$.
 - $\exists\sigma : K(u) \longrightarrow \overline{K}$ *homomorfismo* con $\sigma(u) = v$.
 - $\exists \sigma : \overline{K} \longrightarrow \overline{K}$ *automorfismo* con $\sigma(u) = v$.

Estos elementos se llaman *elementos conjugados*.

*** Extensiones conjugadas
Sean $F_1/K$, $F_2/K$ extensiones algebraicas, equivalen:

 - $\exists \sigma: F_1 \longrightarrow F_2$ *isomorfismo* sobre $K$.
 - $\exists \sigma : F_1 \longrightarrow \overline{K}$, *homomorfismo* sobre $K$ con $\sigma(F_1) = F_2$.
 - $\sigma : \overline{K} \longrightarrow \overline{K}$, *isomorfismo* tal que $\sigma(F_1) = F_2$.

Estas extensiones se llaman *extensiones conjugadas*.

** Extensiones normales
*** Extensiones normales
Sea $F/K$ extensión subcuerpo de $\overline{K}$, equivalen:

 - $\sigma : F \longrightarrow \overline{K}$, me da $\sigma(F) = F$.
 - Todo irreducible de $K[X]$ con raíz en $F$ descompone en lineales en $F[X]$.
 - $F$ es cuerpo de descomposición de algún polinomio.

A una extensión de este tipo se le llama *extensión normal*.

*** Caracterización de extensiones normales
#+begin_theorem
*Caracterización de extensiones normales*. Sea $E/K$ extensión finita, equivalen:

  - $E/K$ es extensión normal.
  - Para cada $\sigma : E/K \longrightarrow \overline{K}/K$, se tiene $\sigma(E) = E$. Equivalentemente, para cada
    $\sigma : \overline{K}/K \longrightarrow \overline{K}/K$, se tiene $\sigma(E) = E$.
  - Todo irreducible $f \in K[X]$ con una raíz en $E$ descompone en $E$.
#+end_theorem

*** Caracterización de extensiones normales en torres
#+begin_theorem
Sea $K\subset F \subset E$ extensiones finitas, $E$ extensión normal. Equivalen:

  - $F/K$ es normal.
  - Para cada $\sigma : E/K \longrightarrow E/K$, se tiene $\sigma(F) = F$.
#+end_theorem

Sea $F/K$ normal, podemos cambiar el dominio y codominio para tener un
$\sigma : F/K \longrightarrow \overline{K}/K$. Por ser $F$ normal, $\sigma(F) = F$.

Sea $\sigma : F/K \longrightarrow \overline{K}/K$, podemos extenderla finitamente hasta $E$ como $\overline\sigma$. Como $E/K$ es
normal, $\overline\sigma(E) = E$; y así tengo un $\overline\sigma : E/K \longrightarrow E/K$, que me da $\sigma(F)=\overline\sigma(F) = F$.

* Teoría de Galois Finita
** Grupos de automorfismos
*** Lema de Dedekind
Sean n homomorfismos de cuerpos distintos $F_1 \longrightarrow F_2$, entonces son 
linealmente independientes sobre $F_2$.

*** Grupo de extensión
Para toda extensión finita $F/K$ llamamos *grupo de la extensión* a:

\[ G(F/K) = \{ \sigma \in \Aut(F) \mid \forall u \in K : \sigma(u) = u\}\]

Y se verifica que $|G(F/K)| \leq [F : K]$.
*** Teorema de Artin
Llamamos *cuerpo fijo* al subcuerpo al que no afecta $G$:

\[ E^G = \{ u \in E \mid \forall\sigma\in G: \sigma(u) = u\}\]

El *Teorema de Artin* afirma que para un subgrupo finito de $Aut(E)$, entonces
$[E : E^G] = |G|$.
*** Extensión de Galois
Una extensión finita $E/K$ es *de Galois* si existe $G$ tal que $E^G = K$. En este
caso, llamamos a $G$ el *grupo de Galois* de la extensión, $Gal(E/K)$.

Una extensión es de Galois ssi es normal y separable.

** Correspondencia de Galois, caso finito
*** Correspondencia
Definimos una correspondencia entre los subgrupos de una extensión de Galois
y los cuerpos intermedios como:

\[ H^\ast = E^H = \{u \in E \mid \forall\sigma\in H: \sigma(u)=u\}\]
\[F^\ast = Gal(E/F) = \{\sigma\in G \mid \forall u\in F: \sigma(u) = u\}\]
* Cuerpos finitos
** Estructura de los cuerpos finitos
*** Propiedades de un cuerpo finito
Sea $F$ cuerpo finito con $|F| = q$,

 - $car(F) = p$ es un primo
 - $<1>$ es isomorfo a $\mathbb{Z}/p\mathbb{Z}$
 - $F/\mathbb{Z}_p$ es extensión finita
 - $[ F : \mathbb{Z}_p] = n$, entonces $q = p^n$
 - $F^\times$ es cíclico de orden $q-1$

*** Existencia de cuerpos finitos
#+begin_theorem
Para $p$ primo, existe cuerpo de $p^n$ elementos.
#+end_theorem
#+begin_proofs
Sea $f(x) = x^{p^n}-x$ polinomio en $\mathbb{Z}_p$. Su derivada no tiene raíces, luego él tiene sólo
raíces simples. Vemos que con sólo añadir las raíces del polinomio, llega a ser
cuerpo de descomposición.

Sean $u,v \in S$, conjunto de raíces:

 - $(u+v)^{p^n} - (u+v) = u^{p^n}-u+v^{p^n}-v = 0$
 - $(uv)^{p^n}-uv = u^{p^n}v^{p^n} - uv = 0$
 - $(-u)^q - (-u) = 0$
 - $(u^{-1})^q-u^{-1} = 0$
#+end_proofs

*** Teorema de Moore
Para cada $p^n$ existe exactamente un cuerpo con $p^n$ elementos; que es el cuerpo de
descomposición de $x^{p^n}-x$ sobre $\mathbb{Z}_p$. No existen otros cuerpos finitos.
** Factorización de polinomios
*** Clasificación de polinomios irreducibles
#+begin_theorem
Los factores irreducibles de $x^{p^n}-x$ son exactamente los polinomios irreducibles de
$\mathbb{F}_p[X]$ cuyo grado divida a $n$.
#+end_theorem
* Extensiones ciclotómicas
** Raíces de la unidad
*** Subgrupos finitos del grupo multiplicativo
Todo subgrupo finito del grupo multiplicativo $K^\times$ es cíclico.

*** Grupo de raíces n-ésimas
Llamamos *grupo de raíces n-ésimas* de la unidad al grupo siguiente. Cualquier
generador del grupo se llama una *raíz primitiva* de la unidad.

\[ \mu_n = \{\zeta\in K \mid \zeta^n = 1\} \]

** Polinomios ciclotómicos
*** Definición
Se llama *polinomio ciclotómico* al polinomio:

\[\Phi_n = \prod_{\zeta \text{ primitiva}} (X -\zeta)\]

Se cumple que $\operatorname{grad}(\Phi_n) = \phi(n)$.

*** Cálculo de los polinomios ciclotómicos
Tenemos que:

\[\Phi_n  = \frac{X^n-1}{\prod_{d|n, d\neq n} \phi_d}\]

*** Función de Möbius
Se define $\mu : \mathbb{N} \longrightarrow \mathbb{Z}$ como:

\[\mu(n) = \threepartdef
{0}{\exists p: \text{ primo con } p^2|n}
{(-1)^r}{n = p_1p_2\dots p_n \text{ primos distintos}}
{1}{n=1}\]

** Extensiones ciclotómicas
