#+TITLE: Análisis funcional
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS:
#+LANGUAGE: es

#+LaTeX: \setcounter{secnumdepth}{0}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{fact}{Proposición}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \newtheorem{proofs}{Demostración}
#+latex_header: \setlength{\parindent}{0pt}

* 1. Espacios normados
*** Norma
#+begin_definition
*Norma*. Función $\|\_\| : X \longrightarrow \mathbb{R}$ verficando:

- $\|x\| = 0 \Leftrightarrow x = 0$

- $\|ax\| = |a| \|x\|$

- $\|x+y\| \leq \|x\|+\|y\|$
#+end_definition

Desde la norma se puede definir una distancia asociada $d(x,y) = \|x-y\|$, que hace a $X$ un 
/espacio métrico/. Además, será /espacio topológico/ desde esa distancia con abiertos:

\[\tau = \{G \subset X \;|\; \forall a \in G: \exists r > : B(x,r) \subset G\}\]

#+begin_theorem
*Todo espacio vectorial es normado*. Cualquier espacio vectorial sobre $\mathbb{R}$ o
$\mathbb{C}$ admite una norma.
#+end_theorem
#+begin_proofs
Dada una base \(\{e_i\}\) del espacio, podemos escribir $x = \sum \alpha_i e_i$ y definirla como:

\[ \|x\| = \sum |\alpha_i|\]
#+end_proofs

*** Espacios de Banach
#+begin_definition
*Espacio de Banach*. Espacio normado completo.
#+end_definition

#+begin_theorem
*La norma es continua*. La norma, la suma y el producto por
escalar son continuas.
#+end_theorem
#+begin_proofs
Usando la desigualdad triangular vemos que la norma es lispchitziana 
y por tanto, continua:

\[ |\|x\| -  \|y\|| \leq \|x-y\| \]

Usando que la convergencia en el producto es la convergencia por coordenadas:

\[\|(x_n+y_n) - (x+y)\| \leq \|x-x_n\| + \|y-y_n\| \longrightarrow 0\]
\[\|ax_n - ax\| = |a| \|x_n - x\| \longrightarrow 0\] 
#+end_proofs

Como corolario, lo son las homotecias y translaciones, todas las bolas cerradas
son homeomorfas a la bola unidad.

#+begin_theorem
*Normado es conexo*.
#+end_theorem
#+begin_proofs
La bola unidad es arcoconexa con la curva recta entre dos puntos, que
queda dentro de la bola:

\[ \|tx - (1-t)y\| \leq t\|x\| + (1-t)\|y\| \leq 1 \]

Así, el espacio es localmente arcoconexo y por tanto conexo.
#+end_proofs
*** Equivalencia de normas
#+begin_theorem
*Equivalencia proporcional*. $\|.\|$ y $\|.\|_\ast$ son equivalentes si:

\[\exists m,M \in \mathbb{R^+}:\; m \|x\| \leq \|x\|_\ast \leq M \|x\|\]
#+end_theorem

#+begin_theorem
*Desigualdad de Young*. Para $p>1$ con $\frac{1}{p}+\frac{1}{q} = 1$ se tiene:

\[ab \leq \frac{a^p}{p}+\frac{b^q}{q}\]
#+end_theorem

#+begin_theorem
*Desigualdades de Hölder y Minkowski*. Para 
$a_1\dots a_nb_1\dots b_n \in \mathbb{R}^+_0$ se tiene:

- *Desigualdad de Hölder*. Con $\frac{1}{p} +\frac{1}{q} = 1$ se verifica:

\[\sum a_kb_k \leq \left(\sum a_k^p\right)^{1/p}\left(\sum b_k^q\right)^{1/q}\]

- *Desigualdad de Minkowski*. La desigualdad triangular para discretos:

\[\left(\sum (a_k+b_k)^p \right)^{1/p} = \left(\sum a_k^p \right)^{1/p} + \left(\sum b_k^p \right)^{1/p} \]
#+end_theorem

** Ejemplos de espacios normados
*** Espacios de dimensión finita
Solemos notar por ${\mathcal L}_p^n$ al espacio de Banach sobre $\mathbb{R}^n$ o $\mathbb{C}^n$ que da la norma

\[\|x\|_p = \left(\sum |x_{(k)}|^p \right)^{1/p}\]

Nótese el caso especial ${\cal L}^n_\infty$ que da la norma del máximo.

*** Espacios de sucesiones
Sobre las *sucesiones* podemos definir las normas $\|.\|_p$ de forma similar
sobre los siguientes espacios de Banach:

\[{\cal L}_p = \left\{ x : \mathbb{N} \longrightarrow \mathbb{K}\ \left|\ \sum |x(n)|^p \right\}\]

Siendo un caso particular el de la norma del máximo sobre *sucesiones acotadas*:

\[{\cal L}_\infty = \left\{ x : \mathbb{N} \longrightarrow \mathbb{K}\ \left|\ x(n) \text{ acotada} \right\}\]

Que además cuenta con subespacios usando la misma norma:

- *Sucesiones convergentes*. Cerrado, y por tanto, de Banach.

\[c = \left\{ x : \mathbb{N} \longrightarrow \mathbb{K}\ \left|\ \{x(n)\} \text{ convergente } \right\}\]

- *Sucesiones nulas*. También cerrado.

\[c_0 = \left\{ x : \mathbb{N} \longrightarrow \mathbb{K}\ \left|\ \{x(n)\} \longrightarrow 0 \right\}\]

- *Sucesiones casi-nulas*. Que no es cerrado.

\[c_{00} = \left\{ x : \mathbb{N} \longrightarrow \mathbb{K}\ \left|\ 
\exists m: \forall n \geq m:\  x(n) = 0 \right\}\]

*** Espacios de funciones continuas

*** Espacios de funciones derivables
