#+TITLE: Topología II
#+SUBTITLE: Apuntes de teoría
#+AUTHOR: Mario Román
#+OPTIONS:
#+LANGUAGE: es

#+LaTeX: \setcounter{secnumdepth}{0}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \newtheorem{theorem}{Teorema}
#+latex_header: \newtheorem{fact}{Proposición}
#+latex_header: \newtheorem{definition}{Definición}
#+latex_header: \newtheorem{proofs}{Demostración}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \newcommand{\twopartdef}[4]{\left\{\begin{array}{ll} #1 & \mbox{if } #2 \\ #3 & \mbox{if } #4 \end{array} \right. }

* 1. El grupo fundamental
*** Arcoconexión
#+begin_definition
*Arcoconexión*. Las curvas definen relación de equivalencia cuando unen dos puntos.

 \[\exists f\ \text{arco}: f(0) = x, f(1) = y \Rightarrow x \sim y\]

Cada componente de esta partición es una *componente arcoconexa*. Un espacio es
*arcoconexo* cuando tiene una sola componente.
#+end_definition
#+begin_proof
Las propiedades de la relación de equivalencia se cumplen por:

 - 1. *Reflexividad*. Arco constante, $f(t) = x$, lleva a $x \sim x$.
 - 2. *Simetría*. Arco inverso, $\widetilde f(t) = f(1-t)$, lleva a $x\sim y \Rightarrow y \sim x$.
 - 3. *Transitividad*. Composición de arcos $f \ast g$.

La composición de arcos se define como:

\[f \ast g = \twopartdef{f(2t)}{t \leq \frac{1}{2}}{g(2t-1)}{t \geq \frac{1}{2}}\]
#+end_proof

#+begin_theorem
*Arcoconexión implica conexión*. Pero no en sentido contrario.
#+end_theorem
#+begin_proofs
Dado un punto en un espacio arcoconexo, los caminos a los demás serán conexos y
compartirán un punto, luego su unión será conexa.

Sin embargo, hay un contraejemplo de espacio conexo no arcoconexo en el
[[https://es.wikipedia.org/wiki/Seno_del_top%25C3%25B3logo][seno del topólogo]].
#+end_proofs


*** Lazos y homotopía
#+begin_definition
*Lazo alrededor de un punto*. Un arco con $f(0) = f(1) = x$ es un lazo alrededor de $x$.
#+end_definition
#+begin_definition
*Lazos homotópicos*. Tenemos $f \sim g$ cuando $\exists H: [0,1] \longrightarrow [0,1] \longrightarrow X$,
cumpliendo

 - $H$ continua.
 - $H(0) = f$
 - $H(1) = g$
 - $H(s,0) = H(s,1) = x_0$

En ocasiones usaremos =(flip . uncurry) H=.
#+end_definition

** Aplicaciones
*** Teorema fundamental del álgebra
#+begin_theorem
*Teorema fundamental del álgebra*. Todo polinomio con coeficientes
en $\mathbb{C}$ de grado $n$ tiene $n$ raíces en $\mathbb{C}$.
#+end_theorem
#+begin_proof
Supongamos un $P$ que no tuviera raíz en $\mathbb{C}$.

Fijado un $r$, restringimos el polinomio desde la circunferencia de
radio $r$ a la circunferencia unidad, girándolo
además para que en $0$ valga $1$.

\[f_r(t) = \frac{|P(r)|}{P(r)} \frac{P(re^{2\pi it})}{|P(re^{2\pi it})|}\]

Tenemos una homotopía de este lazo al constante, definida como:

\[H(t,s) = f_{(1-s)r}(t)\]

Y por tanto, $deg(f_r) = 0$.

Por otro lado, sea ahora $R > 1, \sum |a_i|$, y tomemos $|z| = R$, tenemos
por un lado:

\[|z^n| 
= R^n > R^{n-1}\left(\sum |a_i|\right) 
\geq |a_1z^{n-1} + \dots + a_n|\]

Y por otro lado, si tomo un $t \in [0,1]$, puedo definir una familia
de polinomios $P_s(z) = z^n + t(a_1z^{n-1} + \dots + a_n) = 0$, que no tienen raíces
porque, por otro lado:

\[|z^n| = |t||a_1z^{n-1} + \dots + a_n| \leq |a_1z^{n-1} + \dots + a_n|\]

Luego esta familia de polinomios no tiene raíces en el círculo 
de radio $R$. Podemos ahora definir otra homotopía:

\[H(t,s) = \frac{P_s(Re^{2\pi it})}{|P_s(Re^{2\pi it})|}  \frac{|P_s(R)|}{P_s(R)}\]

Que es homotopía entre $e^{2\pi int}$ y $f_R(t)$. Luego $deg(f_R) = n$.
#+end_proof
